"use client";

import { useEffect, useRef, useState } from 'react';
import {
  X,
  MapPin,
  Send,
  AlertTriangle,
  Loader2,
  ChevronDown,
  Sparkles,
  ExternalLink,
  Stethoscope,
} from 'lucide-react';
import { useRegionalIntelligenceStore, type ChatMessage } from '@/stores/regional-intelligence-store';
import { useRegionalIntelligence } from '@/hooks/useRegionalIntelligence';
import {
  AI_GENERATED_DISCLAIMER,
  AI_GENERATED_LABEL,
  isRegionalEvidenceSource,
  regionalEvidenceFreshnessState,
  type EvidenceOrigin,
  type RegionalIntelligenceResponse,
} from '@/lib/regional-intelligence';

// ---------------------------------------------------------------------------
// Presentation helpers
// ---------------------------------------------------------------------------

const ORIGIN_LABELS: Record<EvidenceOrigin, string> = {
  warehouse: 'Observed data',
  web: 'Web source',
  model_inference: 'AI inference',
};

const ORIGIN_STYLES: Record<EvidenceOrigin, string> = {
  warehouse: 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200',
  web: 'bg-sky-100 text-sky-900 dark:bg-sky-950 dark:text-sky-200',
  model_inference: 'bg-violet-100 text-violet-900 dark:bg-violet-950 dark:text-violet-200',
};

function humanize(value: string): string {
  return value.replace(/_/g, ' ');
}

function OriginBadge({
  origin,
  source,
}: {
  origin: EvidenceOrigin;
  source?: string;
}) {
  return (
    <span
      className={`inline-flex items-center rounded px-1.5 py-0.5 text-[11px] font-medium ${ORIGIN_STYLES[origin]}`}
      title={
        origin === 'model_inference'
          ? 'Generated by the AI from general knowledge, not from measured data.'
          : undefined
      }
    >
      {ORIGIN_LABELS[origin]}
      {source ? ` · ${humanize(source)}` : ''}
    </span>
  );
}

function AiGeneratedBanner() {
  return (
    <div className="flex items-start gap-2 rounded-lg border border-violet-300 bg-violet-50 p-3 text-xs leading-5 text-violet-900 dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-200">
      <Sparkles aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0" />
      <p>
        <span className="font-semibold">{AI_GENERATED_LABEL}.</span>{' '}
        {AI_GENERATED_DISCLAIMER}
      </p>
    </div>
  );
}

function RiskSummaryCard({ data }: { data: RegionalIntelligenceResponse['riskSummary'] }) {
  const colors: Record<string, string> = {
    low: 'bg-green-100 text-green-900 dark:bg-green-950 dark:text-green-100',
    moderate: 'bg-yellow-100 text-yellow-900 dark:bg-yellow-950 dark:text-yellow-100',
    high: 'bg-orange-100 text-orange-900 dark:bg-orange-950 dark:text-orange-100',
    critical: 'bg-red-100 text-red-900 dark:bg-red-950 dark:text-red-100',
  };
  return (
    <div className={`rounded-lg p-4 ${colors[data.level] ?? 'bg-gray-100 text-gray-800'}`}>
      <div className="flex items-center gap-2 font-semibold">
        <AlertTriangle aria-hidden="true" className="h-4 w-4" />
        Risk: {data.level.toUpperCase()}
      </div>
      <p className="mt-1 text-sm">{data.headline}</p>
      {data.factors.length > 0 && (
        <ul className="mt-2 flex flex-wrap gap-1">
          {data.factors.map((factor) => (
            <li key={factor} className="rounded-full bg-white/60 px-2 py-0.5 text-xs dark:bg-black/20">
              {factor}
            </li>
          ))}
        </ul>
      )}
      <div className="mt-2">
        <OriginBadge origin={data.evidenceOrigin} />
      </div>
    </div>
  );
}

function ObservationsList({
  observations,
}: {
  observations: RegionalIntelligenceResponse['observations'];
}) {
  if (!observations.length) return null;
  return (
    <section className="space-y-2">
      <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500">
        What the data shows
      </h4>
      <ul className="space-y-1.5">
        {observations.map((observation, index) => (
          <li
            key={index}
            className="rounded bg-gray-50 p-2 text-sm dark:bg-gray-800"
          >
            <p>{observation.statement}</p>
            <div className="mt-1">
              <OriginBadge
                origin={observation.evidenceOrigin}
                source={observation.evidenceSource}
              />
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}

function RemediationCard({
  item,
}: {
  item: RegionalIntelligenceResponse['remediation'][number];
}) {
  const timeframeStyles: Record<string, string> = {
    immediate: 'border-red-400',
    short_term: 'border-amber-400',
    long_term: 'border-blue-400',
  };
  const timeframeLabels: Record<string, string> = {
    immediate: 'Now',
    short_term: 'This season',
    long_term: 'Multi-year',
  };

  return (
    <article
      className={`rounded border-l-4 bg-white p-3 dark:bg-gray-800 ${timeframeStyles[item.timeframe] ?? 'border-gray-400'}`}
    >
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="rounded bg-gray-100 px-1.5 py-0.5 text-[11px] font-medium dark:bg-gray-700">
          {timeframeLabels[item.timeframe] ?? item.timeframe}
        </span>
        <span className="rounded bg-gray-100 px-1.5 py-0.5 text-[11px] dark:bg-gray-700">
          {humanize(item.strategy)}
        </span>
        <span className="text-[11px] text-gray-500">
          {item.confidence} confidence
        </span>
      </div>
      <h5 className="mt-1.5 text-sm font-semibold">{item.title}</h5>
      <p className="mt-1 text-sm text-gray-600 dark:text-gray-300">{item.rationale}</p>
      {item.consultProfessionals.length > 0 && (
        <p className="mt-2 flex items-start gap-1.5 text-xs text-gray-600 dark:text-gray-400">
          <Stethoscope aria-hidden="true" className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <span>
            Confirm with a{' '}
            {item.consultProfessionals.map((discipline) => humanize(discipline)).join(', ')}{' '}
            before acting.
          </span>
        </p>
      )}
      <div className="mt-2">
        <OriginBadge origin={item.evidenceOrigin} source={item.evidenceSource} />
      </div>
    </article>
  );
}

/**
 * One chip per recommended strategy, built from the model's own `remediation` items -- the only
 * strategy data this panel actually receives (the server never streams `strategyContext` down;
 * see `src/lib/server/services/regional-context.ts`). Renders nothing when there is nothing to
 * show, and never a percentage or an effect-size number: `evidenceOrigin` is the strongest claim
 * a chip is allowed to make about where a strategy came from.
 */
function StrategyChips({
  remediation,
}: {
  remediation: RegionalIntelligenceResponse['remediation'];
}) {
  if (!remediation.length) return null;
  return (
    <div aria-label="Suggested strategy chips" className="flex flex-wrap gap-1">
      {remediation.map((item, index) => (
        <span
          key={`${item.strategy}-${index}`}
          className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-xs font-mono bg-emerald-500/20 text-emerald-800 dark:text-emerald-300"
        >
          {humanize(item.strategy)}
          <span className="rounded bg-white/50 px-1 text-[10px] font-sans font-medium dark:bg-black/30">
            {ORIGIN_LABELS[item.evidenceOrigin]}
          </span>
        </span>
      ))}
    </div>
  );
}

/** Renders the report as readable Markdown, mirroring the JSON export's structure. */
function reportToMarkdown(response: RegionalIntelligenceResponse): string {
  const lines: string[] = [];
  lines.push(`# Remediation report — ${AI_GENERATED_LABEL}`);
  lines.push('');
  lines.push(AI_GENERATED_DISCLAIMER);
  lines.push('');
  lines.push(`## Risk: ${response.riskSummary.level.toUpperCase()}`);
  lines.push(response.riskSummary.headline);
  if (response.riskSummary.factors.length) {
    lines.push('');
    for (const factor of response.riskSummary.factors) lines.push(`- ${factor}`);
  }
  lines.push('');
  lines.push(`_Evidence origin: ${ORIGIN_LABELS[response.riskSummary.evidenceOrigin]}_`);

  if (response.observations.length) {
    lines.push('');
    lines.push('## What the data shows');
    for (const observation of response.observations) {
      const source = observation.evidenceSource ? ` (${humanize(observation.evidenceSource)})` : '';
      lines.push(`- ${observation.statement} — _${ORIGIN_LABELS[observation.evidenceOrigin]}${source}_`);
    }
  }

  lines.push('');
  lines.push('## Suggested remediation');
  if (response.remediation.length) {
    for (const item of response.remediation) {
      lines.push('');
      lines.push(`### ${item.title}`);
      lines.push(
        `Strategy: ${humanize(item.strategy)} · Timeframe: ${humanize(item.timeframe)} · Confidence: ${item.confidence}`
      );
      lines.push('');
      lines.push(item.rationale);
      if (item.consultProfessionals.length) {
        lines.push('');
        lines.push(
          `Consult: ${item.consultProfessionals.map((discipline) => humanize(discipline)).join(', ')}`
        );
      }
      lines.push('');
      lines.push(`_Evidence origin: ${ORIGIN_LABELS[item.evidenceOrigin]}_`);
    }
  } else {
    lines.push('');
    lines.push(
      'The assistant did not find enough here to suggest a remediation strategy. Treat this as an absence of evidence, not an all-clear.'
    );
  }

  lines.push('');
  lines.push('## Professional consultation');
  lines.push(response.professionalConsultation);

  if (response.webSources.length) {
    lines.push('');
    lines.push('## Web sources consulted');
    for (const source of response.webSources) lines.push(`- [${source.title}](${source.url})`);
  }

  return lines.join('\n');
}

function WebSourcesList({
  sources,
}: {
  sources: RegionalIntelligenceResponse['webSources'];
}) {
  if (!sources.length) return null;
  return (
    <section className="space-y-1">
      <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500">
        Web sources consulted
      </h4>
      <ul className="space-y-1">
        {sources.map((source) => (
          <li key={source.url}>
            <a
              href={source.url}
              target="_blank"
              rel="noopener noreferrer nofollow"
              className="inline-flex items-start gap-1 text-xs text-blue-600 underline hover:text-blue-800 dark:text-blue-400"
            >
              <ExternalLink aria-hidden="true" className="mt-0.5 h-3 w-3 shrink-0" />
              {source.title}
            </a>
          </li>
        ))}
      </ul>
    </section>
  );
}

function DataFreshnessFooter({ freshness }: { freshness: Record<string, string> }) {
  const [open, setOpen] = useState(false);
  const entries = Object.entries(freshness);
  if (!entries.length) return null;

  return (
    <div className="border-t pt-2 dark:border-gray-700">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        aria-controls="regional-intelligence-freshness"
        className="flex min-h-11 items-center gap-1 rounded text-xs text-gray-500 hover:text-gray-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"
      >
        <ChevronDown
          aria-hidden="true"
          className={`h-3 w-3 transition-transform ${open ? 'rotate-180' : ''}`}
        />
        Data sources ({entries.length})
      </button>
      {open && (
        <div id="regional-intelligence-freshness" className="mt-1 space-y-0.5">
          {entries.map(([source, value]) => {
            const freshnessState = isRegionalEvidenceSource(source)
              ? regionalEvidenceFreshnessState(source, value)
              : 'unavailable';
            const timestamp = Date.parse(value);
            const observedAt = Number.isFinite(timestamp)
              ? new Date(timestamp).toLocaleString()
              : null;
            const state =
              freshnessState === 'available'
                ? {
                    label: observedAt ?? 'Available',
                    color: 'text-green-600 dark:text-green-400',
                    dot: 'bg-green-400',
                  }
                : freshnessState === 'pending'
                  ? {
                      label: 'Awaiting validated publication',
                      color: 'text-amber-600 dark:text-amber-400',
                      dot: 'bg-amber-400',
                    }
                  : freshnessState === 'stale'
                    ? {
                        label: `Stale${observedAt ? ` (${observedAt})` : ''}`,
                        color: 'text-amber-600 dark:text-amber-400',
                        dot: 'bg-amber-400',
                      }
                    : {
                        label: 'Not observed',
                        color: 'text-gray-500',
                        dot: 'bg-gray-400',
                      };
            return (
              <div key={source} className="flex items-center gap-2 text-xs">
                <span aria-hidden="true" className={`h-1.5 w-1.5 rounded-full ${state.dot}`} />
                <span className="text-gray-500">{humanize(source)}</span>
                <span className={state.color}>{state.label}</span>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function MessageBubble({ message }: { message: ChatMessage }) {
  if (message.role === 'user') {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">
          {message.content}
        </div>
      </div>
    );
  }

  const response = message.parsedResponse;
  if (response) {
    const downloadReport = (content: string, mimeType: string, extension: string) => {
      const reportBlob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(reportBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `remediation-report-${Date.now()}.${extension}`;
      link.click();
      URL.revokeObjectURL(url);
    };
    const handleExportJson = () =>
      downloadReport(JSON.stringify(response, null, 2), "application/json", "json");
    const handleExportMarkdown = () =>
      downloadReport(reportToMarkdown(response), "text/markdown", "md");

    return (
      <div className="space-y-3">
        <AiGeneratedBanner />
        <div className="flex items-center justify-between gap-2">
          <StrategyChips remediation={response.remediation} />
          <div className="flex shrink-0 gap-1.5">
            <button
              onClick={handleExportJson}
              className="px-2.5 py-1 text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white rounded transition"
            >
              Export JSON
            </button>
            <button
              onClick={handleExportMarkdown}
              className="px-2.5 py-1 text-xs font-semibold bg-gray-600 hover:bg-gray-500 text-white rounded transition"
            >
              Export Markdown
            </button>
          </div>
        </div>
        <RiskSummaryCard data={response.riskSummary} />
        <ObservationsList observations={response.observations} />
        {response.remediation.length > 0 ? (
          <section className="space-y-2">
            <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              Suggested remediation
            </h4>
            {response.remediation.map((item, index) => (
              <RemediationCard key={`${item.strategy}-${index}`} item={item} />
            ))}
          </section>
        ) : (
          <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">
            The assistant did not find enough here to suggest a remediation
            strategy. Treat this as an absence of evidence, not an all-clear.
          </p>
        )}
        <div className="flex items-start gap-2 rounded-lg border border-gray-300 bg-gray-50 p-3 text-sm dark:border-gray-700 dark:bg-gray-800">
          <Stethoscope aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-gray-500" />
          <p>{response.professionalConsultation}</p>
        </div>
        <WebSourcesList sources={response.webSources} />
      </div>
    );
  }

  return (
    <div
      role={message.isStreaming ? 'status' : undefined}
      className="whitespace-pre-wrap rounded-lg bg-gray-50 px-3 py-2 text-sm dark:bg-gray-800"
    >
      {message.content || 'Reviewing this location…'}
      {message.isStreaming && <span className="ml-1 animate-pulse">|</span>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main panel component
// ---------------------------------------------------------------------------

export default function RegionalIntelligencePanel() {
  const isOpen = useRegionalIntelligenceStore((s) => s.isOpen);
  const selectedLocation = useRegionalIntelligenceStore((s) => s.selectedLocation);
  const messages = useRegionalIntelligenceStore((s) => s.messages);
  const isLoading = useRegionalIntelligenceStore((s) => s.isLoading);
  const error = useRegionalIntelligenceStore((s) => s.error);
  const errorRetryable = useRegionalIntelligenceStore((s) => s.errorRetryable);
  const analysisCancelled = useRegionalIntelligenceStore((s) => s.analysisCancelled);
  const dataFreshness = useRegionalIntelligenceStore((s) => s.dataFreshness);
  const toolActivity = useRegionalIntelligenceStore((s) => s.toolActivity);
  const closePanel = useRegionalIntelligenceStore((s) => s.closePanel);
  const cancelAnalysis = useRegionalIntelligenceStore((s) => s.cancelAnalysis);
  const setError = useRegionalIntelligenceStore((s) => s.setError);
  const { sendFollowUp, retryLastRequest } = useRegionalIntelligence();

  const [input, setInput] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const panelRef = useRef<HTMLElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    if (!isOpen) return;
    previousFocusRef.current =
      document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const focusFrame = window.requestAnimationFrame(() => {
      (inputRef.current ?? panelRef.current)?.focus();
    });
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closePanel();
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      window.cancelAnimationFrame(focusFrame);
      document.removeEventListener('keydown', handleKeyDown);
      previousFocusRef.current?.focus();
      previousFocusRef.current = null;
    };
  }, [closePanel, isOpen]);

  if (!isOpen || !selectedLocation) return null;

  const coordinatePrecision = selectedLocation.precision === 'exact' ? 6 : 2;

  const handleSend = async () => {
    const question = input.trim();
    if (!question || isLoading) return;
    setInput('');
    await sendFollowUp(question);
  };

  return (
    <aside
      ref={panelRef}
      role="dialog"
      tabIndex={-1}
      aria-labelledby="regional-intelligence-title"
      aria-busy={isLoading}
      className="absolute right-0 top-0 z-50 flex h-full w-full flex-col border-l bg-white shadow-xl sm:w-96 dark:border-gray-700 dark:bg-gray-900"
    >
      <div role="status" aria-live="polite" aria-atomic="true" className="sr-only">
        {isLoading
          ? toolActivity ?? 'Regional analysis in progress.'
          : messages.some((message) => message.parsedResponse)
            ? 'Regional analysis complete.'
            : ''}
      </div>

      {/* Header */}
      <div className="flex items-center justify-between border-b p-3 dark:border-gray-700">
        <div className="flex min-w-0 items-center gap-2">
          <MapPin aria-hidden="true" className="h-4 w-4 shrink-0 text-blue-500" />
          <div className="min-w-0">
            <h2 id="regional-intelligence-title" className="truncate text-sm font-medium">
              {selectedLocation.lat.toFixed(coordinatePrecision)}°,{' '}
              {selectedLocation.lon.toFixed(coordinatePrecision)}°
            </h2>
            <p className="text-[11px] text-gray-500">{AI_GENERATED_LABEL} advisor</p>
          </div>
        </div>
        <button
          type="button"
          onClick={closePanel}
          aria-label="Close regional intelligence analysis"
          className="flex min-h-11 min-w-11 items-center justify-center rounded hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 dark:hover:bg-gray-800"
        >
          <X aria-hidden="true" className="h-4 w-4" />
        </button>
      </div>

      {/* Messages */}
      <div className="flex-1 space-y-3 overflow-y-auto p-3">
        {messages.length === 0 && !isLoading && (
          <div className="flex h-full items-center justify-center p-4 text-center text-sm text-gray-500">
            Ask about this location to get AI-generated remediation suggestions.
          </div>
        )}
        {messages.map((message) => (
          <MessageBubble key={message.id} message={message} />
        ))}
        {toolActivity && isLoading && (
          <p className="flex items-center gap-2 text-xs text-gray-500">
            <Loader2 aria-hidden="true" className="h-3 w-3 animate-spin" />
            {toolActivity}
          </p>
        )}
        {analysisCancelled && !isLoading && (
          <div role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">
            <p>Analysis was canceled. No analysis was completed.</p>
            <button
              type="button"
              onClick={() => void retryLastRequest()}
              className="mt-1 flex min-h-11 items-center rounded px-2 text-xs underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500"
            >
              Resume analysis
            </button>
          </div>
        )}
        {error && (
          <div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-600 dark:bg-red-900/20">
            <p>{error}</p>
            <div className="mt-1 flex gap-2">
              {errorRetryable && (
                <button
                  type="button"
                  onClick={() => void retryLastRequest()}
                  disabled={isLoading}
                  className="flex min-h-11 items-center rounded px-2 text-xs underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 disabled:opacity-50"
                >
                  Retry
                </button>
              )}
              <button
                type="button"
                onClick={() => setError(null)}
                className="flex min-h-11 items-center rounded px-2 text-xs underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500"
              >
                Dismiss
              </button>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Data freshness */}
      <div className="px-3 pb-1">
        <DataFreshnessFooter freshness={dataFreshness} />
      </div>

      {/* Input */}
      <div className="border-t p-3 dark:border-gray-700">
        <div className="mb-2 flex items-center justify-between gap-3">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            {AI_GENERATED_LABEL} — not professional advice. Verify before acting.
          </p>
          {isLoading && (
            <button
              type="button"
              onClick={cancelAnalysis}
              className="flex min-h-11 min-w-11 shrink-0 items-center justify-center rounded px-3 text-xs font-medium text-blue-600 underline hover:text-blue-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 dark:text-blue-400"
            >
              Cancel
            </button>
          )}
        </div>
        <div className="flex gap-2">
          <label htmlFor="regional-intelligence-question" className="sr-only">
            Ask a follow-up question about this location
          </label>
          <input
            id="regional-intelligence-question"
            ref={inputRef}
            type="text"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            onKeyDown={(event) => event.key === 'Enter' && void handleSend()}
            placeholder="Ask a follow-up question..."
            maxLength={1000}
            disabled={isLoading}
            className="min-h-11 flex-1 rounded-lg border bg-gray-50 px-3 py-2 text-sm outline-none focus-visible:border-blue-500 focus-visible:ring-2 focus-visible:ring-blue-500 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800"
          />
          <button
            type="button"
            aria-label="Send follow-up question"
            onClick={() => void handleSend()}
            disabled={isLoading || !input.trim()}
            className="flex min-h-11 min-w-11 items-center justify-center rounded-lg bg-blue-600 px-3 py-2 text-white hover:bg-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:opacity-50"
          >
            {isLoading ? (
              <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
            ) : (
              <Send aria-hidden="true" className="h-4 w-4" />
            )}
          </button>
        </div>
      </div>
    </aside>
  );
}
