"""Plant-suitability rule engine (regional-guide pools x USDA PLANTS envelope); see AGENTS.md in this directory."""

from agri_data_service.warehouse.plant_suitability.config import PRODUCTION, V0_FROZEN, RuleConfig
from agri_data_service.warehouse.plant_suitability.engine import (
    CANDIDATE_OUTPUT_SCHEMA,
    ENGINE_VERSION,
    GUILD_STATUSES,
    MAX_CELL_TAXON_PAIRS,
    MAX_CELLS_PER_CALL,
    METADATA_ADMITTED_SOURCES,
    METADATA_ENGINE_VERSION,
    METADATA_EXCLUDED_SOURCES,
    METADATA_INPUTS_SHA256,
    METADATA_KEYS,
    METADATA_NO_FIRE_CLAIM,
    METADATA_PICK_DEFINITION,
    METADATA_RULE_CONFIG,
    METADATA_SITE_INPUTS,
    METADATA_WITHHELD_SITE_INPUTS,
    STATUS_LICENCE_EXCLUDED,
    STATUS_NO_ELIGIBLE_TAXA,
    STATUS_NO_REGIONAL_GUIDE,
    STATUS_SCORED,
    PreparedEngine,
    candidates_for_cell,
    evaluate_cells,
    prepare,
)
from agri_data_service.warehouse.plant_suitability.labels import (
    FireTextAllowList,
    assert_no_fire_claims,
    find_fire_claims,
    served_allow_list,
)
from agri_data_service.warehouse.plant_suitability.licences import (
    ALL_RIGHTS_RESERVED,
    CC0,
    CC_BY,
    CC_BY_NC,
    CC_BY_NC_SA,
    CC_BY_ND,
    COMMERCIAL_USE_LICENCES,
    KNOWN_LICENCES,
    PUBLIC_DOMAIN,
    RESTRICTED_LICENCES,
    UNRECORDED,
    US_GOVERNMENT_WORK,
)
from agri_data_service.warehouse.plant_suitability.schemas import (
    CELL_RECOMMENDATIONS_SCHEMA,
    EXCLUSION_SCHEMA,
    GUIDE_ROW_SCHEMA,
    NWPL_RESOLUTION_COLUMN,
    SITE_CONDITIONS_SCHEMA,
    SITE_INPUT_GROUPS,
    SPECIES_ENVELOPE_SCHEMA,
    STRUCTURAL_SITE_COLUMNS,
    WETLAND_LIST_SCHEMA,
)
from agri_data_service.warehouse.plant_suitability.site import SiteInputProvenance, SiteInputSource
from agri_data_service.warehouse.plant_suitability.wetland import resolve_wetland_ratings

__all__ = [
    "ALL_RIGHTS_RESERVED",
    "CANDIDATE_OUTPUT_SCHEMA",
    "CC0",
    "CC_BY",
    "CC_BY_NC",
    "CC_BY_NC_SA",
    "CC_BY_ND",
    "CELL_RECOMMENDATIONS_SCHEMA",
    "COMMERCIAL_USE_LICENCES",
    "ENGINE_VERSION",
    "EXCLUSION_SCHEMA",
    "GUIDE_ROW_SCHEMA",
    "GUILD_STATUSES",
    "KNOWN_LICENCES",
    "MAX_CELLS_PER_CALL",
    "MAX_CELL_TAXON_PAIRS",
    "METADATA_ADMITTED_SOURCES",
    "METADATA_ENGINE_VERSION",
    "METADATA_EXCLUDED_SOURCES",
    "METADATA_INPUTS_SHA256",
    "METADATA_KEYS",
    "METADATA_NO_FIRE_CLAIM",
    "METADATA_PICK_DEFINITION",
    "METADATA_RULE_CONFIG",
    "METADATA_SITE_INPUTS",
    "METADATA_WITHHELD_SITE_INPUTS",
    "NWPL_RESOLUTION_COLUMN",
    "PRODUCTION",
    "PUBLIC_DOMAIN",
    "RESTRICTED_LICENCES",
    "SITE_CONDITIONS_SCHEMA",
    "SITE_INPUT_GROUPS",
    "SPECIES_ENVELOPE_SCHEMA",
    "STATUS_LICENCE_EXCLUDED",
    "STATUS_NO_ELIGIBLE_TAXA",
    "STATUS_NO_REGIONAL_GUIDE",
    "STATUS_SCORED",
    "STRUCTURAL_SITE_COLUMNS",
    "UNRECORDED",
    "US_GOVERNMENT_WORK",
    "V0_FROZEN",
    "WETLAND_LIST_SCHEMA",
    "FireTextAllowList",
    "PreparedEngine",
    "RuleConfig",
    "SiteInputProvenance",
    "SiteInputSource",
    "assert_no_fire_claims",
    "candidates_for_cell",
    "evaluate_cells",
    "find_fire_claims",
    "prepare",
    "resolve_wetland_ratings",
    "served_allow_list",
]
