-- `ai_conversations.geohash` was declared varchar(12) -- the length of a real precision-12 geohash.
-- The producer never wrote a geohash: `regional-context.ts` builds `${lat.toFixed(2)}_${lon.toFixed(2)}`,
-- which is 13 characters for any 3-digit longitude and 14 with a negative latitude as well.
--
-- So EVERY location in the Americas failed this insert with
--     value too long for type character varying(12)
-- which the route caught and returned as 503 "Could not start the conversation". The feature could
-- only ever have worked at |longitude| < 100 -- Europe and Africa. Proven 2026-09-08 by inserting
-- '47.61_-122.33' inside a rolled-back transaction against production.
--
-- Widening rather than shortening the value on purpose: dropping a decimal would silently merge
-- distinct locations into one conversation key, and the table holds ZERO rows, so there is nothing
-- to migrate and no consumer relying on the old width.
ALTER TABLE "ai_conversations" ALTER COLUMN "geohash" TYPE varchar(24);
