[mypy]
python_version = 3.12
strict = true
plugins =
    sqlalchemy.ext.mypy.plugin,

[mypy-geoalchemy2.*]
ignore_missing_imports = True

[mypy-pgvector.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-sanic_ext.*]
ignore_missing_imports = True
