"""SQLAlchemy ORM models for the regenerative agriculture data warehouse."""

from agri_data_service.models.forecasting import (
    ForecastBacktestMetric,
    ForecastEntityState,
    ForecastFeatureSnapshot,
    ForecastHindcastRun,
    ForecastHindcastValue,
    ForecastInputRecordedAt,
    ForecastIteration,
    ForecastIterationActual,
    ForecastIterationActualInput,
    ForecastIterationValue,
    ForecastModel,
    ForecastObservation,
    ForecastPublication,
    ForecastPublicationItem,
    ForecastQualityPolicy,
    ForecastReceipt,
    ForecastRun,
    ForecastSeries,
    ForecastTrainingRun,
    ForecastValue,
)
from agri_data_service.models.geospatial import (
    AnalysisSubject,
    InterventionAnalysisRun,
    InterventionEvidenceInput,
    InterventionEvidenceLineage,
    NormalizedSourceFeature,
)
from agri_data_service.models.historical import (
    CellSourceCrosswalk,
    DroughtPolygonSnapshot,
    SignalCoverageAudit,
    SignalObservation,
    SourceCoverageAudit,
    SpatialCell,
)
from agri_data_service.models.historical_promotion import (
    HistoricalPromotionArtifactReceipt,
    HistoricalPromotionBundle,
    HistoricalPromotionChunkReceipt,
    HistoricalPromotionDataSourceReceipt,
    HistoricalPromotionSourceReleaseReceipt,
    HistoricalPromotionState,
)
from agri_data_service.models.jobs import (
    JobAttempt,
    JobCheckpoint,
    JobDefinition,
    JobDependency,
    JobEvent,
    JobIncident,
    JobOutbox,
    JobOutput,
    JobRun,
    JobWorkItem,
    PublicationPointer,
)
from agri_data_service.models.knowledge import KnowledgeChunk
from agri_data_service.models.location import Location
from agri_data_service.models.profiles import (
    ClimateProfile,
    LandUseSnapshot,
    SoilProfile,
    TopographyProfile,
    WaterProfile,
)
from agri_data_service.models.provenance import (
    Artifact,
    DataSource,
    ReleaseSet,
    ReleaseSetItem,
    SourceRelease,
)
from agri_data_service.models.species import CompanionRelationship, Species
from agri_data_service.models.strategy import Strategy

__all__ = [
    "AnalysisSubject",
    "Artifact",
    "CellSourceCrosswalk",
    "ClimateProfile",
    "CompanionRelationship",
    "DataSource",
    "DroughtPolygonSnapshot",
    "ForecastBacktestMetric",
    "ForecastEntityState",
    "ForecastFeatureSnapshot",
    "ForecastHindcastRun",
    "ForecastHindcastValue",
    "ForecastInputRecordedAt",
    "ForecastIteration",
    "ForecastIterationActual",
    "ForecastIterationActualInput",
    "ForecastIterationValue",
    "ForecastModel",
    "ForecastObservation",
    "ForecastPublication",
    "ForecastPublicationItem",
    "ForecastQualityPolicy",
    "ForecastReceipt",
    "ForecastRun",
    "ForecastSeries",
    "ForecastTrainingRun",
    "ForecastValue",
    "HistoricalPromotionArtifactReceipt",
    "HistoricalPromotionBundle",
    "HistoricalPromotionChunkReceipt",
    "HistoricalPromotionDataSourceReceipt",
    "HistoricalPromotionSourceReleaseReceipt",
    "HistoricalPromotionState",
    "InterventionAnalysisRun",
    "InterventionEvidenceInput",
    "InterventionEvidenceLineage",
    "JobAttempt",
    "JobCheckpoint",
    "JobDefinition",
    "JobDependency",
    "JobEvent",
    "JobIncident",
    "JobOutbox",
    "JobOutput",
    "JobRun",
    "JobWorkItem",
    "KnowledgeChunk",
    "LandUseSnapshot",
    "Location",
    "NormalizedSourceFeature",
    "PublicationPointer",
    "ReleaseSet",
    "ReleaseSetItem",
    "SignalCoverageAudit",
    "SignalObservation",
    "SoilProfile",
    "SourceCoverageAudit",
    "SourceRelease",
    "SpatialCell",
    "Species",
    "Strategy",
    "TopographyProfile",
    "WaterProfile",
]
