"""Guard the declarative ``db/`` tree against drift from the Alembic migrations.

Two layers:

* ``test_manifest_matches_tree`` runs everywhere (no database). It proves the
  committed ``manifest.sql`` references exactly the object files on disk and
  every file carries the generated banner -- catching orphaned or unreferenced
  files after a hand edit.
* ``test_declarative_tree_matches_migrations`` is the real parity gate. Point
  ``AGRI_TEST_DATABASE_URL`` at a disposable database migrated to head; it
  captures the schema with ``pg_dump``, re-splits it, and asserts the result is
  byte-identical to the committed tree. Skips when the env var is unset, like
  the other PostgreSQL contract tests; once it is set, a missing ``pg_dump``
  toolchain is a hard failure, not a silent skip.
* ``test_cross_major_tree_matches_migrations`` is the same gate against a
  server of a *different* major (``AGRI_CROSS_MAJOR_DATABASE_URL``), after the
  enumerated normalisation in ``dump_schema``. It additionally proves each
  normalised-away NOT NULL constraint name is a real catalogue row on that
  server, so the rule cannot degrade into a blanket rewrite.

The canonical-major path applies **no** normalisation at all -- it asserts the
raw dump needs none -- so the pg16 byte-exact guarantee is unchanged. See
``db/AGENTS.md`` (*Toolchain and major-version awareness*).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import psycopg2
import pytest

_SERVICE_ROOT = Path(__file__).resolve().parents[1]
_DB_ROOT = _SERVICE_ROOT / "db"
sys.path.insert(0, str(_DB_ROOT / "tools"))

import dump_schema  # noqa: E402  (db/tools is added to sys.path above)
import split_schema  # noqa: E402

_GENERATED_MARK = "-- GENERATED by db/tools/split_schema.py"
CROSS_MAJOR_DATABASE_URL_ENV = "AGRI_CROSS_MAJOR_DATABASE_URL"
# pg_dump cannot dump a server newer than itself. When no local client is new enough,
# these two point the dump at the client shipped with the server (e.g. inside its
# container); the DSN then has to be the one *that* client can reach.
CROSS_MAJOR_PG_DUMP_ARGV_ENV = "AGRI_CROSS_MAJOR_PG_DUMP_ARGV"
CROSS_MAJOR_DUMP_DSN_ENV = "AGRI_CROSS_MAJOR_DUMP_DSN"
# Every NOT NULL whose stored name differs from the derivable <table>_<column>_not_null.
_NON_DERIVABLE_NOT_NULL_SQL = """
SELECT constraint_row.conname
FROM pg_constraint AS constraint_row
JOIN pg_attribute AS column_row
  ON column_row.attrelid = constraint_row.conrelid
 AND column_row.attnum = constraint_row.conkey[1]
WHERE constraint_row.contype = 'n'
  AND constraint_row.connamespace = 'agri'::regnamespace
  AND constraint_row.conname <> (
      regexp_replace(constraint_row.conrelid::regclass::text, '^agri[.]', '')
      || '_' || column_row.attname || '_not_null'
  )
"""


def _server_major(dsn: str) -> int:
    connection = psycopg2.connect(dsn)
    try:
        with connection.cursor() as cursor:
            cursor.execute("SHOW server_version_num")
            return int(cursor.fetchone()[0]) // 10000
    finally:
        connection.close()


def _non_derivable_not_null_names(dsn: str) -> set[str]:
    connection = psycopg2.connect(dsn)
    try:
        with connection.cursor() as cursor:
            cursor.execute(_NON_DERIVABLE_NOT_NULL_SQL)
            return {row[0] for row in cursor.fetchall()}
    finally:
        connection.close()


def _assert_tree_matches(regenerated: dict[str, str], committed: dict[str, str], hint: str) -> None:
    regenerated_paths = set(regenerated)
    committed_paths = set(committed)
    assert regenerated_paths == committed_paths, (
        "object set drifted from migrations:\n"
        f"  new (add to db/): {sorted(regenerated_paths - committed_paths)}\n"
        f"  stale (remove from db/): {sorted(committed_paths - regenerated_paths)}\n"
        f"{hint}"
    )
    mismatched = [rel for rel in committed if committed[rel] != regenerated[rel]]
    assert not mismatched, (
        f"{len(mismatched)} object file(s) differ from the migration head (e.g. {mismatched[:5]}). {hint}"
    )


def _committed_tree() -> dict[str, str]:
    tree: dict[str, str] = {}
    for path in sorted(_DB_ROOT.rglob("*.sql")):
        if "tools" in path.relative_to(_DB_ROOT).parts:
            continue
        rel = path.relative_to(_DB_ROOT).as_posix()
        tree[rel] = path.read_text(encoding="utf-8")
    return tree


def test_manifest_matches_tree() -> None:
    manifest = (_DB_ROOT / "manifest.sql").read_text(encoding="utf-8")
    referenced = {line.split(maxsplit=1)[1].strip() for line in manifest.splitlines() if line.startswith("\\i ")}
    on_disk = {
        p.relative_to(_DB_ROOT).as_posix()
        for p in _DB_ROOT.rglob("*.sql")
        if p.name != "manifest.sql" and "tools" not in p.relative_to(_DB_ROOT).parts
    }
    assert referenced == on_disk, (
        f"manifest/tree mismatch:\n  only in manifest: {sorted(referenced - on_disk)}"
        f"\n  only on disk: {sorted(on_disk - referenced)}"
    )
    for rel, content in _committed_tree().items():
        if rel == "manifest.sql":
            continue
        assert content.startswith(_GENERATED_MARK), f"{rel} is missing the generated banner"


def test_declarative_tree_matches_migrations(agri_db_dsn: str) -> None:
    """Byte-exact parity on the canonical major, with no normalisation applied."""
    server_major = _server_major(agri_db_dsn)
    dumper_major = dump_schema.pg_dump_major()
    assert dumper_major >= server_major, (
        f"pg_dump {dumper_major} cannot dump a PostgreSQL {server_major} server; set PG_DUMP/PGBIN to a newer client"
    )
    if server_major != dump_schema.CANONICAL_SERVER_MAJOR:
        pytest.fail(
            f"AGRI_TEST_DATABASE_URL is a PostgreSQL {server_major} server, but the committed tree is canonical "
            f"against PostgreSQL {dump_schema.CANONICAL_SERVER_MAJOR}. Use {CROSS_MAJOR_DATABASE_URL_ENV} for a "
            "different major; that path is normalised and documented."
        )

    dump = dump_schema.dump_agri(agri_db_dsn)
    _, normalised_away = dump_schema.normalize_named_not_null(dump)
    assert not normalised_away, (
        "the canonical-major dump must need no cross-major normalisation, but inline NOT NULL constraint "
        f"names were present: {sorted(set(normalised_away))[:5]}"
    )
    _assert_tree_matches(
        split_schema.build_tree_text(dump),
        _committed_tree(),
        "Run: uv run python db/tools/regenerate.py --admin-dsn <admin-dsn>",
    )


@pytest.mark.agri_db_cross_major
def test_cross_major_tree_matches_migrations() -> None:
    """The same tree, rebuilt from a different server major after enumerated normalisation."""
    dsn = os.environ.get(CROSS_MAJOR_DATABASE_URL_ENV)
    if not dsn:
        pytest.skip(
            f"set {CROSS_MAJOR_DATABASE_URL_ENV} to a head-migrated database on a PostgreSQL major other than "
            f"{dump_schema.CANONICAL_SERVER_MAJOR} (needs its own server; see plans/postgresql-18-migration-rehearsal)"
        )
    server_major = _server_major(dsn)
    assert server_major != dump_schema.CANONICAL_SERVER_MAJOR, (
        f"{CROSS_MAJOR_DATABASE_URL_ENV} points at the canonical major {server_major}; "
        "it exists to exercise a *different* major"
    )
    raw_argv = os.environ.get(CROSS_MAJOR_PG_DUMP_ARGV_ENV)
    argv_prefix = json.loads(raw_argv) if raw_argv else None
    dump_dsn = os.environ.get(CROSS_MAJOR_DUMP_DSN_ENV, dsn)
    dumper_major = dump_schema.pg_dump_major(argv_prefix=argv_prefix)
    assert dumper_major >= server_major, (
        f"pg_dump {dumper_major} cannot dump a PostgreSQL {server_major} server; set "
        f"{CROSS_MAJOR_PG_DUMP_ARGV_ENV} to the client shipped with the server "
        "(see plans/postgresql-18-migration-rehearsal for the exact podman invocation)"
    )

    dump = dump_schema.dump_agri(dump_dsn, argv_prefix=argv_prefix)
    normalised, normalised_away = dump_schema.normalize_named_not_null(dump)

    if server_major >= dump_schema.FIRST_CATALOGUED_NOT_NULL_MAJOR:
        # Prove the rule is narrow: every name it removed is a real catalogue row whose
        # stored name a restore could not have derived. Nothing else may be removed.
        catalogued = _non_derivable_not_null_names(dsn)
        assert set(normalised_away) == catalogued, (
            "normalisation removed NOT NULL constraint names that are not non-derivable catalogue rows:\n"
            f"  removed but not catalogued: {sorted(set(normalised_away) - catalogued)}\n"
            f"  catalogued but not removed: {sorted(catalogued - set(normalised_away))}"
        )
    else:
        assert not normalised_away

    _assert_tree_matches(
        split_schema.build_tree_text(normalised),
        _committed_tree(),
        f"A PostgreSQL {server_major} server produced a different schema than the canonical "
        f"PostgreSQL {dump_schema.CANONICAL_SERVER_MAJOR} tree, beyond the enumerated normalisation. "
        "This is a real portability difference, not a formatting one -- investigate before deploying.",
    )
