"""Disposable-PostgreSQL proof that the NDVI registration guard fires and rolls back.

Gated on ``AGRI_TEST_DATABASE_URL`` through the shared ``tests/conftest.py`` fixture, which
verifies the Alembic head and refuses the persistent ``plantgeo`` warehouse. Everything runs
inside one transaction that is rolled back, so the database is left exactly as it was found.

``geo.features``/``geo.layers`` are NOT part of the agri Alembic tree -- they belong to the
application's own schema -- so this test creates a minimal stand-in inside the same rolled-back
transaction. It is **column- and property-faithful, not type-faithful**: it carries exactly the
columns the three vegetation statements read (``properties``, ``geom``, ``created_at``,
``layer_id``, and the layer's ``name``) and the property keys they index, but production types
those key columns as ``uuid``/``varchar`` where this uses ``bigint``/``text``. That divergence
cannot mask a bind-type error in this lane, because no bind parameter in the three statements
under test touches those columns -- they are joined on, never parameterised. Widen the fixture
before reusing it for anything that does bind them.

Why this test exists rather than another stubbed-session one: it is the only thing that exercises
the real SQL against a real planner AND proves the refusal unwinds its own release. See the
project note on stubbed sessions letting bind-type errors reach production.
"""

from __future__ import annotations

from datetime import UTC, date, datetime
from typing import TYPE_CHECKING

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

from agri_data_service.execution.vegetation_ndvi_plane import (
    DATA_SOURCE_KEY,
    EMPTY_RELEASE_REASON,
    EMPTY_SELECTION_REASON,
    SOURCE_LAYER_NAME,
    EmptyGovernedReleaseError,
    ReleaseSetManifestConflictError,
    all_requested_cells_materialised,
    forward_release_set_logical_key,
    measure_release_materialisation,
    register_governed_forward_plane,
    register_governed_plane,
    release_set_logical_key,
)

if TYPE_CHECKING:
    import uuid

CUTOFF_DAY = date(2026, 8, 8)
OBSERVED_DAYS = (date(2026, 8, 6), date(2026, 8, 7), date(2026, 8, 8))
SEEDED_CELL_KEYS = ("43.1250:-116.1250", "43.3750:-116.3750")
# Deliberately absent from geo.features: the typo / re-keyed-upstream case the guard exists for.
UNRESOLVABLE_CELL_KEYS = ("99.8750:-179.8750",)
EXPECTED_CELL_DAYS = len(SEEDED_CELL_KEYS) * len(OBSERVED_DAYS)
EXPECTED_RELEASE_COUNT_AFTER_AMENDMENT = 2

# One statement per entry: asyncpg prepares every statement it is given and refuses a script.
_CREATE_GEO_FIXTURE = (
    "CREATE SCHEMA geo",
    """
    CREATE TABLE geo.layers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL UNIQUE
    )
    """,
    """
    CREATE TABLE geo.features (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        layer_id bigint NOT NULL REFERENCES geo.layers (id),
        properties jsonb NOT NULL,
        geom public.geometry(Polygon, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
    )
    """,
)
_INSERT_FIXTURE_LAYER = "INSERT INTO geo.layers (name) VALUES (:layer_name)"

_INSERT_FIXTURE_FEATURE = """
INSERT INTO geo.features (layer_id, properties, geom, created_at)
SELECT
    layer.id,
    jsonb_build_object(
        'cellKey', CAST(:cell_key AS text),
        'observedAt', CAST(:observed_at AS text),
        'ndvi', CAST(:ndvi AS double precision),
        'sampleCount', 25,
        'cloudCover', 4.5,
        'sceneId', CAST(:scene_id AS text),
        'resolutionMetres', 27750
    ),
    -- Every corner is cast: an untyped parameter reused in a bare `+ 0.25` deduces as numeric on
    -- one side and double precision on the other, which asyncpg refuses outright.
    ST_SetSRID(
        ST_MakeEnvelope(
            CAST(:min_lon AS double precision),
            CAST(:min_lat AS double precision),
            CAST(:min_lon AS double precision) + 0.25,
            CAST(:min_lat AS double precision) + 0.25
        ),
        4326
    ),
    CAST(:created_at AS timestamptz)
FROM geo.layers AS layer
WHERE layer.name = :layer_name
"""

_COUNT_RELEASES = """
SELECT count(*)
FROM agri.source_release AS release
INNER JOIN agri.data_source AS source ON source.id = release.data_source_id
WHERE source.key = :data_source_key
"""

_COUNT_RELEASE_SET_ITEMS = """
SELECT count(*)
FROM agri.release_set_item AS item
INNER JOIN agri.release_set AS release_set ON release_set.id = item.release_set_id
WHERE release_set.logical_key = :logical_key
"""

_RELEASE_SET_SNAPSHOT = """
SELECT manifest_checksum, state, validated_at
FROM agri.release_set
WHERE logical_key = :logical_key
"""


async def _seed_vegetation_features(session: AsyncSession) -> None:
    """Create the minimal geo stand-in and fill it with one feature per seeded cell per day."""
    for ddl in _CREATE_GEO_FIXTURE:
        await session.execute(text(ddl))
    await session.execute(text(_INSERT_FIXTURE_LAYER), {"layer_name": SOURCE_LAYER_NAME})
    statement = text(_INSERT_FIXTURE_FEATURE)
    for cell_index, cell_key in enumerate(SEEDED_CELL_KEYS):
        latitude, longitude = (float(part) for part in cell_key.split(":"))
        for day_index, observed_day in enumerate(OBSERVED_DAYS):
            await session.execute(
                statement,
                {
                    "layer_name": SOURCE_LAYER_NAME,
                    "cell_key": cell_key,
                    "observed_at": f"{observed_day.isoformat()}T18:31:07Z",
                    "ndvi": 0.40 + 0.01 * (cell_index + day_index),
                    "scene_id": f"S2A_TEST_{cell_index}_{day_index}",
                    "min_lat": latitude,
                    "min_lon": longitude,
                    "created_at": datetime(2026, 8, 9, 6, 0, tzinfo=UTC),
                },
            )


async def _release_count(session: AsyncSession) -> int:
    result = await session.execute(text(_COUNT_RELEASES), {"data_source_key": DATA_SOURCE_KEY})
    return int(result.scalar_one())


async def _release_set_snapshot(session: AsyncSession, logical_key: str) -> tuple[object, object, object]:
    result = await session.execute(text(_RELEASE_SET_SNAPSHOT), {"logical_key": logical_key})
    row = result.one()
    return row[0], row[1], row[2]


@pytest.mark.asyncio
async def test_registration_guard_refuses_an_unlanded_pass_and_unwinds_its_own_release(
    agri_db_async_dsn: str,
) -> None:
    """Both refusal branches fire, the happy path lands, and a refused pass leaves no release."""
    engine = create_async_engine(agri_db_async_dsn)
    try:
        async with AsyncSession(bind=engine, expire_on_commit=False) as session:
            transaction = await session.begin()
            try:
                await _seed_vegetation_features(session)
                await _assert_empty_release_is_refused_and_rolled_back(session)
                plane_release_id = await _assert_seeded_cells_land(session)
                await _assert_unresolvable_cells_are_refused_against_a_full_release(session, plane_release_id)
                await _assert_changed_corpus_uses_a_distinct_forward_release_set(session)
            finally:
                await transaction.rollback()
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_forward_registration_materialises_only_explicit_touched_days(
    agri_db_async_dsn: str,
) -> None:
    engine = create_async_engine(agri_db_async_dsn)
    try:
        async with AsyncSession(bind=engine, expire_on_commit=False) as session:
            transaction = await session.begin()
            try:
                await _seed_vegetation_features(session)
                touched_pairs = (
                    (SEEDED_CELL_KEYS[0], OBSERVED_DAYS[0]),
                    (SEEDED_CELL_KEYS[1], OBSERVED_DAYS[-1]),
                )
                summary = await register_governed_forward_plane(
                    session,
                    cutoff_day=CUTOFF_DAY,
                    cell_days=touched_pairs,
                )
                assert summary.observation_count == len(touched_pairs)
                assert summary.materialisation.observation_count == len(touched_pairs)
                assert summary.materialisation.first_observed_day == OBSERVED_DAYS[0]
                assert summary.materialisation.last_observed_day == OBSERVED_DAYS[-1]
            finally:
                await transaction.rollback()
    finally:
        await engine.dispose()


async def _assert_empty_release_is_refused_and_rolled_back(session: AsyncSession) -> None:
    """A pass whose cells resolve to nothing, from a clean state, refuses and leaves no release."""
    assert await _release_count(session) == 0
    nested = await session.begin_nested()
    with pytest.raises(EmptyGovernedReleaseError) as caught:
        await register_governed_plane(session, cutoff_day=CUTOFF_DAY, cell_keys=UNRESOLVABLE_CELL_KEYS)
    # Nothing landed anywhere, so this is the release-wide branch, not the selection branch.
    assert caught.value.reason_code == EMPTY_RELEASE_REASON
    assert caught.value.release_observation_count == 0
    await nested.rollback()
    # The refusal happened after insert_source_release.sql already ran, so this is the assertion
    # that the raise really unwinds a registered release rather than merely reporting on it.
    assert await _release_count(session) == 0


async def _assert_seeded_cells_land(session: AsyncSession) -> uuid.UUID:
    """The happy path over cells that do have features, so the guard is proved non-trivial.

    Registered with a deliberately duplicated key. `--cell-key` is `multiple=True` and dedupes
    nothing, and the selection read is batched over an `ANY(array)` that matches a value once per
    batch however often it appears, so an undeduped duplicate would report fewer covered cells
    than were requested and turn `all_requested_cells_materialised` false on a healthy pass.
    """
    duplicated = (*SEEDED_CELL_KEYS, SEEDED_CELL_KEYS[0])
    summary = await register_governed_plane(session, cutoff_day=CUTOFF_DAY, cell_keys=duplicated)
    assert summary.requested_cell_count == len(SEEDED_CELL_KEYS)
    assert summary.observation_count == EXPECTED_CELL_DAYS
    assert summary.selection.observation_count == EXPECTED_CELL_DAYS
    assert summary.selection.series_count == len(SEEDED_CELL_KEYS)
    assert all_requested_cells_materialised(
        selection=summary.selection,
        requested_cell_count=summary.requested_cell_count,
    )
    assert summary.materialisation.observation_count == EXPECTED_CELL_DAYS
    assert summary.materialisation.last_observed_day == CUTOFF_DAY
    assert await _release_count(session) == 1
    return summary.plane.source_release_id


async def _assert_unresolvable_cells_are_refused_against_a_full_release(
    session: AsyncSession,
    plane_release_id: uuid.UUID,
) -> None:
    """The regression this guard was rewritten for: a release-wide count would have passed here."""
    release_wide = await measure_release_materialisation(session, source_release_id=plane_release_id)
    # Stated as an assertion, not a comment: a release-wide gate sees a full release at this moment
    # and would wave the pass through. Only the selection-scoped count can refuse it.
    assert release_wide.observation_count == EXPECTED_CELL_DAYS

    nested = await session.begin_nested()
    with pytest.raises(EmptyGovernedReleaseError) as caught:
        await register_governed_plane(session, cutoff_day=CUTOFF_DAY, cell_keys=UNRESOLVABLE_CELL_KEYS)
    assert caught.value.reason_code == EMPTY_SELECTION_REASON
    assert caught.value.release_observation_count == EXPECTED_CELL_DAYS
    assert caught.value.requested_cell_count == len(UNRESOLVABLE_CELL_KEYS)
    await nested.rollback()
    # The corpus is unchanged, so this pass rejoined the existing release rather than making one.
    assert await _release_count(session) == 1


async def _assert_changed_corpus_uses_a_distinct_forward_release_set(session: AsyncSession) -> None:
    """The full set stays frozen while forward registration versions the same-cutoff amendment."""
    latitude, longitude = (float(part) for part in SEEDED_CELL_KEYS[0].split(":"))
    await session.execute(
        text(_INSERT_FIXTURE_FEATURE),
        {
            "layer_name": SOURCE_LAYER_NAME,
            "cell_key": SEEDED_CELL_KEYS[0],
            "observed_at": f"{CUTOFF_DAY.isoformat()}T20:11:00Z",
            # The seeded value for this cell-day is also 0.42. The amendment leaves the daily mean
            # unchanged, so only a digest that fingerprints governed evidence notices the change.
            "ndvi": 0.42,
            "scene_id": "S2A_TEST_CHANGED_SAME_CUTOFF",
            "min_lat": latitude,
            "min_lon": longitude,
            "created_at": datetime(2026, 8, 9, 6, 0, tzinfo=UTC),
        },
    )
    logical_key = release_set_logical_key(CUTOFF_DAY)
    before_items = int(
        (
            await session.execute(
                text(_COUNT_RELEASE_SET_ITEMS),
                {"logical_key": logical_key},
            )
        ).scalar_one()
    )
    assert before_items == 1
    before_set = await _release_set_snapshot(session, logical_key)
    assert before_set[1] == "validated"

    nested = await session.begin_nested()
    with pytest.raises(ReleaseSetManifestConflictError, match="immutable manifest"):
        await register_governed_plane(session, cutoff_day=CUTOFF_DAY, cell_keys=SEEDED_CELL_KEYS)
    await nested.rollback()

    assert await _release_count(session) == 1
    after_items = int(
        (
            await session.execute(
                text(_COUNT_RELEASE_SET_ITEMS),
                {"logical_key": logical_key},
            )
        ).scalar_one()
    )
    assert after_items == before_items
    assert await _release_set_snapshot(session, logical_key) == before_set

    summary = await register_governed_forward_plane(
        session,
        cutoff_day=CUTOFF_DAY,
        cell_days=tuple((cell_key, CUTOFF_DAY) for cell_key in SEEDED_CELL_KEYS),
    )
    forward_logical_key = forward_release_set_logical_key(CUTOFF_DAY, summary.plane.payload_checksum)
    assert forward_logical_key != logical_key
    assert summary.observation_count == len(SEEDED_CELL_KEYS)
    assert await _release_count(session) == EXPECTED_RELEASE_COUNT_AFTER_AMENDMENT
    assert (
        int(
            (
                await session.execute(
                    text(_COUNT_RELEASE_SET_ITEMS),
                    {"logical_key": logical_key},
                )
            ).scalar_one()
        )
        == before_items
    )
    assert (
        int(
            (
                await session.execute(
                    text(_COUNT_RELEASE_SET_ITEMS),
                    {"logical_key": forward_logical_key},
                )
            ).scalar_one()
        )
        == 1
    )
    assert await _release_set_snapshot(session, logical_key) == before_set

    repeated = await register_governed_forward_plane(
        session,
        cutoff_day=CUTOFF_DAY,
        cell_days=tuple((cell_key, CUTOFF_DAY) for cell_key in SEEDED_CELL_KEYS),
    )
    assert repeated.plane.release_set_id == summary.plane.release_set_id
    assert repeated.plane.source_release_id == summary.plane.source_release_id
    assert repeated.observation_count == 0
    assert await _release_set_snapshot(session, logical_key) == before_set
