"""Guard the declarative ``db/`` tree against drift from the Alembic migrations.

Two layers:

* ``test_manifest_matches_tree`` runs everywhere (no database). It proves the
  committed ``manifest.sql`` references exactly the object files on disk and
  every file carries the generated banner -- catching orphaned or unreferenced
  files after a hand edit.
* ``test_declarative_tree_matches_migrations`` is the real parity gate. Point
  ``AGRI_TEST_DATABASE_URL`` at a disposable database migrated to head; it
  captures the schema with ``pg_dump``, re-splits it, and asserts the result is
  byte-identical to the committed tree. Skips when the env var is unset, like
  the other PostgreSQL contract tests; once it is set, a missing ``pg_dump``
  toolchain is a hard failure, not a silent skip.
"""

from __future__ import annotations

import sys
from pathlib import Path

_SERVICE_ROOT = Path(__file__).resolve().parents[1]
_DB_ROOT = _SERVICE_ROOT / "db"
sys.path.insert(0, str(_DB_ROOT / "tools"))

import dump_schema  # noqa: E402  (db/tools is added to sys.path above)
import split_schema  # noqa: E402

_GENERATED_MARK = "-- GENERATED by db/tools/split_schema.py"


def _committed_tree() -> dict[str, str]:
    tree: dict[str, str] = {}
    for path in sorted(_DB_ROOT.rglob("*.sql")):
        if "tools" in path.relative_to(_DB_ROOT).parts:
            continue
        rel = path.relative_to(_DB_ROOT).as_posix()
        tree[rel] = path.read_text(encoding="utf-8")
    return tree


def test_manifest_matches_tree() -> None:
    manifest = (_DB_ROOT / "manifest.sql").read_text(encoding="utf-8")
    referenced = {line.split(maxsplit=1)[1].strip() for line in manifest.splitlines() if line.startswith("\\i ")}
    on_disk = {
        p.relative_to(_DB_ROOT).as_posix()
        for p in _DB_ROOT.rglob("*.sql")
        if p.name != "manifest.sql" and "tools" not in p.relative_to(_DB_ROOT).parts
    }
    assert referenced == on_disk, (
        f"manifest/tree mismatch:\n  only in manifest: {sorted(referenced - on_disk)}"
        f"\n  only on disk: {sorted(on_disk - referenced)}"
    )
    for rel, content in _committed_tree().items():
        if rel == "manifest.sql":
            continue
        assert content.startswith(_GENERATED_MARK), f"{rel} is missing the generated banner"


def test_declarative_tree_matches_migrations(agri_db_dsn: str) -> None:
    dump = dump_schema.dump_agri(agri_db_dsn)
    regenerated = split_schema.build_tree_text(dump)
    committed = _committed_tree()

    regenerated_paths = set(regenerated)
    committed_paths = set(committed)
    assert regenerated_paths == committed_paths, (
        "object set drifted from migrations:\n"
        f"  new (add to db/): {sorted(regenerated_paths - committed_paths)}\n"
        f"  stale (remove from db/): {sorted(committed_paths - regenerated_paths)}\n"
        "Run: uv run python db/tools/regenerate.py --admin-dsn <admin-dsn>"
    )
    mismatched = [rel for rel in committed if committed[rel] != regenerated[rel]]
    assert not mismatched, (
        f"{len(mismatched)} object file(s) differ from the migration head "
        f"(e.g. {mismatched[:5]}). Regenerate the declarative tree."
    )
