"""Explode a ``pg_dump --schema-only`` file into a per-object declarative tree.

This is the deterministic half of the declarative schema project: given the
ground-truth DDL that the Alembic migrations produce (captured with
``pg_dump``), it writes one canonical ``.sql`` file per database object under a
target root, plus an ordered ``manifest.sql`` that rebuilds the whole schema
from scratch.

It is intentionally dependency-free (stdlib only) so both the regeneration
command and the parity test can call it. See ``db/AGENTS.md`` for the routing
rules, the manifest wave ordering, and the forward-load workflow.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path

# pg_dump prefixes every object with a three-line banner:
#     --
#     -- Name: <name>; Type: <TYPE>; Schema: <schema>; Owner: <owner>
#     --
_HEADER = re.compile(
    r"(?m)^--\n-- Name: (?P<name>.+?); Type: (?P<type>.+?); "
    r"Schema: (?P<schema>.+?); Owner: (?P<owner>.*?)\n--\n"
)
_ON_TARGET = re.compile(r"\bON(?:\s+ONLY)?\s+agri\.(?P<rel>\"?[A-Za-z0-9_]+\"?)")
_OWNED_BY = re.compile(r"OWNED BY agri\.(?P<rel>\"?[A-Za-z0-9_]+\"?)\.")
_ALTER_TARGET = re.compile(r"ALTER TABLE(?:\s+ONLY)?\s+agri\.(?P<rel>\"?[A-Za-z0-9_]+\"?)")
# pg_dump sprinkles these session GUCs between objects; they are not object DDL.
# We strip them from bodies and set them once in the manifest preamble.
_SESSION_SET = re.compile(r"(?m)^SET (?:default_tablespace|default_table_access_method) = .*;\n?")
# pg18's pg_dump brackets its output with \restrict/\unrestrict psql meta-commands.
# The closing one lands after the final object header, so it would otherwise be
# swept into the last object file. Stripped here too, so feeding this module a raw
# pg18 dump file (split_schema.main) behaves like dump_schema.dump_agri.
_PSQL_META = re.compile(r"(?m)^\\(?:un)?restrict [A-Za-z0-9]+[ \t]*\n?")

# Directory buckets for the on-disk tree.
PHASES = (
    "schema",
    "sequences",
    "functions",
    "procedures",
    "tables",
    "views",
    "materialized_views",
    "foreign_keys",
    "triggers",
    "partitions",
)
# Manifest waves. CORE objects are interleaved by pg_dump's own dependency-sorted
# emission order (tables<->functions depend on each other bidirectionally via
# rowtype returns and CHECK/GENERATED function calls, so no coarse phase split is
# valid). TRAILING statements reference other objects and are deferred.
_CORE_PHASES = (
    "schema",
    "sequences",
    "functions",
    "procedures",
    "tables",
    "views",
    "materialized_views",
)
_TRAILING_PHASES = ("foreign_keys", "partitions", "triggers")

_GENERATED_BANNER = (
    "-- GENERATED by db/tools/split_schema.py from the Alembic migration head.\n"
    "-- Canonical declarative source of truth. Do NOT hand-edit to change the\n"
    "-- live schema: edit here AND add a migration that loads this file\n"
    "-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with\n"
    "-- db/tools/regenerate.py; the schema-parity test guards drift.\n"
)


@dataclass
class Block:
    name: str
    type: str
    body: str
    order: int


@dataclass
class ObjectFile:
    """A destination file accumulating one or more statement blocks."""

    phase: str
    stem: str
    order: int  # smallest emission order routed here (its primary CREATE)
    segments: list[tuple[str, str]] = field(default_factory=list)  # (label, sql)

    def render(self) -> str:
        parts = [_GENERATED_BANNER]
        for label, sql in self.segments:
            parts.append(f"\n-- {label}\n{sql}\n" if label else f"\n{sql}\n")
        return "".join(parts).rstrip() + "\n"


def _rel(name: str) -> str:
    return name.strip().strip('"')


def _first_token(name: str) -> str:
    return _rel(name.split(" ", 1)[0])


def parse_blocks(dump: str) -> list[Block]:
    matches = list(_HEADER.finditer(dump))
    blocks: list[Block] = []
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(dump)
        body = dump[start:end]
        body = re.sub(r"\n?--\n-- PostgreSQL database dump complete\n--\s*$", "", body)
        body = _PSQL_META.sub("", _SESSION_SET.sub("", body)).strip()
        if body:
            blocks.append(Block(name=m.group("name"), type=m.group("type"), body=body, order=i))
    return blocks


def split(dump: str) -> dict[str, ObjectFile]:  # noqa: PLR0912, PLR0915 - flat pg_dump type dispatch
    """Route every dump block to its canonical per-object file.

    Returns a mapping of ``"<phase>/<stem>"`` -> :class:`ObjectFile`.
    """
    blocks = parse_blocks(dump)
    matview_names = {_rel(b.name) for b in blocks if b.type == "MATERIALIZED VIEW"}
    files: dict[str, ObjectFile] = {}

    def dest(phase: str, stem: str, order: int) -> ObjectFile:
        key = f"{phase}/{stem}"
        of = files.get(key)
        if of is None:
            of = files[key] = ObjectFile(phase=phase, stem=stem, order=order)
        elif order < of.order:
            of.order = order
        return of

    for b in blocks:
        t = b.type
        if t == "SCHEMA":
            dest("schema", "schema", b.order).segments.append(("", b.body))
        elif t == "SEQUENCE":
            if b.body.lstrip().upper().startswith("CREATE SEQUENCE"):
                dest("sequences", _rel(b.name), b.order).segments.append((t, b.body))
            else:
                # An IDENTITY column, emitted as ``ALTER TABLE ... ADD GENERATED
                # ... AS IDENTITY``; it needs the owning table to already exist.
                m = _ALTER_TARGET.search(b.body)
                owner = _rel(m.group("rel")) if m else _rel(b.name)
                dest("tables", owner, b.order).segments.append((f"IDENTITY: {b.name}", b.body))
        elif t == "SEQUENCE OWNED BY":
            m = _OWNED_BY.search(b.body)
            owner = _rel(m.group("rel")) if m else _rel(b.name)
            dest("tables", owner, b.order).segments.append((f"{t}: {b.name}", b.body))
        elif t == "FUNCTION":
            stem = _rel(b.name.split("(", 1)[0])
            of = dest("functions", stem, b.order)
            if of.segments:  # overload collision -> deterministic disambiguation
                of = dest("functions", f"{stem}__{b.order}", b.order)
            of.segments.append(("", b.body))
        elif t == "PROCEDURE":
            dest("procedures", _rel(b.name.split("(", 1)[0]), b.order).segments.append(("", b.body))
        elif t == "TABLE":
            dest("tables", _rel(b.name), b.order).segments.append(("", b.body))
        elif t in ("DEFAULT", "CONSTRAINT"):
            dest("tables", _first_token(b.name), b.order).segments.append((f"{t}: {b.name}", b.body))
        elif t == "INDEX":
            m = _ON_TARGET.search(b.body)
            rel = _rel(m.group("rel")) if m else _rel(b.name)
            phase = "materialized_views" if rel in matview_names else "tables"
            dest(phase, rel, b.order).segments.append((f"INDEX: {b.name}", b.body))
        elif t == "TRIGGER":
            dest("triggers", _first_token(b.name), b.order).segments.append((f"TRIGGER: {b.name}", b.body))
        elif t in ("TABLE ATTACH", "INDEX ATTACH"):
            dest("partitions", "attach", b.order).segments.append((f"{t}: {b.name}", b.body))
        elif t == "FK CONSTRAINT":
            dest("foreign_keys", _first_token(b.name), b.order).segments.append((f"{t}: {b.name}", b.body))
        elif t == "VIEW":
            dest("views", _rel(b.name), b.order).segments.append(("", b.body))
        elif t == "MATERIALIZED VIEW":
            dest("materialized_views", _rel(b.name), b.order).segments.append(("", b.body))
        elif t == "COMMENT":
            dest("tables", _first_token(b.name), b.order).segments.append((f"COMMENT: {b.name}", b.body))
        else:
            raise ValueError(f"Unhandled pg_dump object type {t!r} for {b.name!r}")

    return files


_MANIFEST_PREAMBLE = """\
-- GENERATED by db/tools/split_schema.py. Rebuilds the agri schema from the
-- canonical declarative tree in dependency order. Run against an empty database
-- that already has the reviewed extensions (infra/local-warehouse/enable-extensions.sql).
\\set ON_ERROR_STOP on
SET check_function_bodies = false;
SET default_tablespace = '';
SET default_table_access_method = heap;
SELECT pg_catalog.set_config('search_path', '', false);
"""


def render_manifest(files: dict[str, ObjectFile]) -> str:
    lines = [_MANIFEST_PREAMBLE]

    def phase_files(*phases: str) -> list[ObjectFile]:
        return sorted((f for f in files.values() if f.phase in phases), key=lambda f: (f.order, f.stem))

    def emit(header: str, group: list[ObjectFile]) -> None:
        if not group:
            return
        lines.append(f"\n-- ==== {header} ====")
        lines.extend(f"\\i agri/{f.phase}/{f.stem}.sql" for f in group)

    # Schema, then every standalone sequence (a CREATE SEQUENCE depends on
    # nothing, and table column defaults reference them), then the remaining
    # core objects interleaved by pg_dump's dependency-sorted emission order.
    emit("schema", phase_files("schema"))
    emit("sequences", phase_files("sequences"))
    emit(
        "core objects (pg_dump dependency order)",
        phase_files("functions", "procedures", "tables", "views", "materialized_views"),
    )
    for phase in _TRAILING_PHASES:
        emit(phase, phase_files(phase))

    return "\n".join(lines).rstrip() + "\n"


def build_tree_text(dump: str) -> dict[str, str]:
    """Return the full tree as ``{relative_posix_path: content}`` without touching disk."""
    files = split(dump)
    out = {f"agri/{f.phase}/{f.stem}.sql": f.render() for f in files.values()}
    out["manifest.sql"] = render_manifest(files)
    return out


def write_tree(files: dict[str, ObjectFile], root: Path) -> list[Path]:
    written: list[Path] = []
    agri = root / "agri"
    for f in files.values():
        target = agri / f.phase / f"{f.stem}.sql"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f.render(), encoding="utf-8", newline="\n")
        written.append(target)
    manifest = root / "manifest.sql"
    manifest.write_text(render_manifest(files), encoding="utf-8", newline="\n")
    written.append(manifest)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("dump", type=Path, help="pg_dump --schema-only output file")
    ap.add_argument("root", type=Path, help="declarative tree root (e.g. db/)")
    args = ap.parse_args(argv)
    written = write_tree(split(args.dump.read_text(encoding="utf-8")), args.root)
    print(f"Wrote {len(written)} files under {args.root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
