-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE VIEW agri.v_forecast_iteration_outcome AS
 SELECT iteration.id AS iteration_id,
    iteration.iteration_key,
    iteration.purpose,
    iteration.availability_mode,
    iteration.method,
    iteration.series_id,
    series.series_key,
    series.entity_type,
    series.entity_key,
    series.metric_name,
    series.metric_unit,
    series.spatial_cell_id,
    series.spatial_support_kind,
    series.source_spatial_resolution_m,
    series.output_spatial_resolution_m,
    iteration.release_set_id,
    iteration.input_release_checksum,
    iteration.contract_checksum,
    iteration.history_checksum,
    iteration.parameter_checksum,
    iteration.as_of_time,
    iteration.cutoff_time,
    iteration.history_start,
    iteration.horizon_days,
    iteration.simulation_count,
    iteration.simulation_seed,
    iteration.gap_policy,
    iteration.lower_bound,
    iteration.upper_bound,
    iteration.recorded_at AS forecast_available_at,
    iteration.receipt_checksum,
    value.valid_time,
    value.horizon_step,
    value.low_value,
    value.median_value,
    value.high_value,
    actual.actual_value,
    actual.actual_release_set_id,
    actual.actual_input_release_checksum,
    actual.actual_digest_version,
    actual.data_available_at AS actual_data_available_at,
    actual.recorded_at AS actual_recorded_at,
    (actual.actual_value - value.median_value) AS residual_actual_minus_forecast,
    (value.median_value - actual.actual_value) AS forecast_error,
    abs((actual.actual_value - value.median_value)) AS absolute_error,
    ((actual.actual_value - value.median_value) * (actual.actual_value - value.median_value)) AS squared_error,
    ((actual.actual_value >= value.low_value) AND (actual.actual_value <= value.high_value)) AS interval_covered,
    value.value_checksum,
    actual.actual_checksum,
    'forecast_iteration_signal_v1'::text AS signal_contract_version
   FROM (((agri.forecast_iteration iteration
     JOIN agri.forecast_iteration_value value ON ((value.iteration_id = iteration.id)))
     JOIN agri.forecast_series series ON ((series.id = iteration.series_id)))
     LEFT JOIN agri.forecast_iteration_actual actual ON ((actual.iteration_value_id = value.id)))
  WHERE ((iteration.status)::text = 'finalized'::text);
