-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: analysis_subject trg_analysis_subject_immutable
CREATE TRIGGER trg_analysis_subject_immutable BEFORE DELETE OR UPDATE ON agri.analysis_subject FOR EACH ROW EXECUTE FUNCTION agri.reject_geospatial_evidence_mutation();
