-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: data_source forecast_input_record_data_source
CREATE TRIGGER forecast_input_record_data_source AFTER INSERT OR UPDATE ON agri.data_source FOR EACH ROW EXECUTE FUNCTION agri.record_forecast_input_change();
