-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: expert_label expert_label_review_guard
CREATE TRIGGER expert_label_review_guard BEFORE INSERT OR DELETE OR UPDATE ON agri.expert_label FOR EACH ROW EXECUTE FUNCTION agri.guard_expert_label_review_change();
