-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_backtest_metric forecast_backtest_change_guard
CREATE TRIGGER forecast_backtest_change_guard BEFORE INSERT OR DELETE OR UPDATE ON agri.forecast_backtest_metric FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_backtest_change();
