-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_value forecast_value_write_guard
CREATE TRIGGER forecast_value_write_guard BEFORE INSERT OR DELETE OR UPDATE ON agri.forecast_value FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_value_write();
