-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_series forecast_input_record_series
CREATE TRIGGER forecast_input_record_series AFTER INSERT OR UPDATE ON agri.forecast_series FOR EACH ROW EXECUTE FUNCTION agri.record_forecast_input_change();

-- TRIGGER: forecast_series forecast_series_immutable
CREATE TRIGGER forecast_series_immutable BEFORE DELETE OR UPDATE ON agri.forecast_series FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_immutable_rows();
