-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_model forecast_model_immutable
CREATE TRIGGER forecast_model_immutable BEFORE DELETE OR UPDATE ON agri.forecast_model FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_immutable_rows();
