-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_iteration forecast_iteration_change_guard
CREATE TRIGGER forecast_iteration_change_guard BEFORE DELETE OR UPDATE ON agri.forecast_iteration FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_iteration_change();

-- TRIGGER: forecast_iteration forecast_iteration_finalized_verify
CREATE TRIGGER forecast_iteration_finalized_verify AFTER UPDATE OF status ON agri.forecast_iteration FOR EACH ROW EXECUTE FUNCTION agri.verify_forecast_iteration_finalization();
