-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_observation forecast_input_record_observation_delete
CREATE TRIGGER forecast_input_record_observation_delete AFTER DELETE ON agri.forecast_observation REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_delete();

-- TRIGGER: forecast_observation forecast_input_record_observation_insert
CREATE TRIGGER forecast_input_record_observation_insert AFTER INSERT ON agri.forecast_observation REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_insert();

-- TRIGGER: forecast_observation forecast_input_record_observation_update
CREATE TRIGGER forecast_input_record_observation_update AFTER UPDATE ON agri.forecast_observation REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_update();

-- TRIGGER: forecast_observation forecast_observation_immutable
CREATE TRIGGER forecast_observation_immutable BEFORE DELETE OR UPDATE ON agri.forecast_observation FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_immutable_rows();

-- TRIGGER: forecast_observation forecast_observation_lineage_guard
CREATE TRIGGER forecast_observation_lineage_guard BEFORE INSERT ON agri.forecast_observation FOR EACH ROW EXECUTE FUNCTION agri.enforce_forecast_input_lineage();
