-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_iteration_actual_input forecast_iteration_actual_input_change_guard
CREATE TRIGGER forecast_iteration_actual_input_change_guard BEFORE DELETE OR UPDATE ON agri.forecast_iteration_actual_input FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_iteration_actual_change();

-- TRIGGER: forecast_iteration_actual_input forecast_iteration_actual_input_lineage_verify
CREATE CONSTRAINT TRIGGER forecast_iteration_actual_input_lineage_verify AFTER INSERT ON agri.forecast_iteration_actual_input DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION agri.verify_forecast_iteration_actual_lineage();
