-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_entity_state forecast_entity_state_immutable
CREATE TRIGGER forecast_entity_state_immutable BEFORE DELETE OR UPDATE ON agri.forecast_entity_state FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_immutable_rows();

-- TRIGGER: forecast_entity_state forecast_input_record_entity_state_delete
CREATE TRIGGER forecast_input_record_entity_state_delete AFTER DELETE ON agri.forecast_entity_state REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_delete();

-- TRIGGER: forecast_entity_state forecast_input_record_entity_state_insert
CREATE TRIGGER forecast_input_record_entity_state_insert AFTER INSERT ON agri.forecast_entity_state REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_insert();

-- TRIGGER: forecast_entity_state forecast_input_record_entity_state_update
CREATE TRIGGER forecast_input_record_entity_state_update AFTER UPDATE ON agri.forecast_entity_state REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_update();
