-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_hindcast_run forecast_hindcast_finalization_policy_guard
CREATE TRIGGER forecast_hindcast_finalization_policy_guard BEFORE UPDATE OF status ON agri.forecast_hindcast_run FOR EACH ROW WHEN ((((new.status)::text = 'finalized'::text) AND ((old.status)::text <> 'finalized'::text))) EXECUTE FUNCTION agri.enforce_forecast_hindcast_finalization_policy();

-- TRIGGER: forecast_hindcast_run forecast_hindcast_finalized_verify
CREATE TRIGGER forecast_hindcast_finalized_verify AFTER UPDATE OF status ON agri.forecast_hindcast_run FOR EACH ROW EXECUTE FUNCTION agri.verify_forecast_hindcast_finalization();

-- TRIGGER: forecast_hindcast_run forecast_hindcast_insert_contract
CREATE TRIGGER forecast_hindcast_insert_contract BEFORE INSERT ON agri.forecast_hindcast_run FOR EACH ROW EXECUTE FUNCTION agri.enforce_forecast_hindcast_insert_contract();

-- TRIGGER: forecast_hindcast_run forecast_hindcast_run_change_guard
CREATE TRIGGER forecast_hindcast_run_change_guard BEFORE DELETE OR UPDATE ON agri.forecast_hindcast_run FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_hindcast_run_change();
