-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: forecast_quality_policy forecast_quality_policy_finalized_receipt_guard
CREATE TRIGGER forecast_quality_policy_finalized_receipt_guard BEFORE DELETE OR UPDATE ON agri.forecast_quality_policy FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_quality_policy_change();
