-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: intervention_evidence_lineage trg_intervention_evidence_lineage_immutable
CREATE TRIGGER trg_intervention_evidence_lineage_immutable BEFORE DELETE OR UPDATE ON agri.intervention_evidence_lineage FOR EACH ROW EXECUTE FUNCTION agri.reject_geospatial_evidence_mutation();

-- TRIGGER: intervention_evidence_lineage trg_intervention_lineage_release_membership
CREATE TRIGGER trg_intervention_lineage_release_membership BEFORE INSERT ON agri.intervention_evidence_lineage FOR EACH ROW EXECUTE FUNCTION agri.enforce_intervention_lineage_release_membership();
