-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: intervention_analysis_run trg_intervention_analysis_release_set
CREATE TRIGGER trg_intervention_analysis_release_set BEFORE INSERT ON agri.intervention_analysis_run FOR EACH ROW EXECUTE FUNCTION agri.enforce_intervention_analysis_release_set();

-- TRIGGER: intervention_analysis_run trg_intervention_analysis_run_immutable
CREATE TRIGGER trg_intervention_analysis_run_immutable BEFORE DELETE OR UPDATE ON agri.intervention_analysis_run FOR EACH ROW EXECUTE FUNCTION agri.reject_geospatial_evidence_mutation();
