-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: normalized_source_feature trg_normalized_feature_artifact_release
CREATE TRIGGER trg_normalized_feature_artifact_release BEFORE INSERT ON agri.normalized_source_feature FOR EACH ROW EXECUTE FUNCTION agri.enforce_normalized_feature_artifact_release();

-- TRIGGER: normalized_source_feature trg_normalized_source_feature_immutable
CREATE TRIGGER trg_normalized_source_feature_immutable BEFORE DELETE OR UPDATE ON agri.normalized_source_feature FOR EACH ROW EXECUTE FUNCTION agri.reject_geospatial_evidence_mutation();
