-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: release_set_item forecast_input_record_release_set_item_delete
CREATE TRIGGER forecast_input_record_release_set_item_delete AFTER DELETE ON agri.release_set_item REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_set_item_delete();

-- TRIGGER: release_set_item forecast_input_record_release_set_item_insert
CREATE TRIGGER forecast_input_record_release_set_item_insert AFTER INSERT ON agri.release_set_item REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_set_item_insert();

-- TRIGGER: release_set_item forecast_input_record_release_set_item_update
CREATE TRIGGER forecast_input_record_release_set_item_update AFTER UPDATE ON agri.release_set_item REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_set_item_update();
