-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: signal_observation forecast_input_record_signal_observation_delete
CREATE TRIGGER forecast_input_record_signal_observation_delete AFTER DELETE ON agri.signal_observation REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_delete();

-- TRIGGER: signal_observation forecast_input_record_signal_observation_insert
CREATE TRIGGER forecast_input_record_signal_observation_insert AFTER INSERT ON agri.signal_observation REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_insert();

-- TRIGGER: signal_observation forecast_input_record_signal_observation_update
CREATE TRIGGER forecast_input_record_signal_observation_update AFTER UPDATE ON agri.signal_observation REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION agri.record_forecast_release_content_update();
