-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: source_release forecast_input_record_source_release
CREATE TRIGGER forecast_input_record_source_release AFTER INSERT OR UPDATE ON agri.source_release FOR EACH ROW EXECUTE FUNCTION agri.record_forecast_input_change();
