-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: strategy_selection_candidate strategy_selection_candidate_immutable
CREATE TRIGGER strategy_selection_candidate_immutable BEFORE DELETE OR UPDATE ON agri.strategy_selection_candidate FOR EACH ROW EXECUTE FUNCTION agri.guard_forecast_immutable_rows();
