-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: strategy_outcome_definition strategy_outcome_definition_immutable
CREATE TRIGGER strategy_outcome_definition_immutable BEFORE DELETE OR UPDATE ON agri.strategy_outcome_definition FOR EACH ROW EXECUTE FUNCTION agri.guard_strategy_review_change();

-- TRIGGER: strategy_outcome_definition strategy_outcome_definition_initial_state
CREATE TRIGGER strategy_outcome_definition_initial_state BEFORE INSERT ON agri.strategy_outcome_definition FOR EACH ROW EXECUTE FUNCTION agri.require_strategy_initial_state();
