-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- TRIGGER: strategy_label_release strategy_label_release_initial_state
CREATE TRIGGER strategy_label_release_initial_state BEFORE INSERT ON agri.strategy_label_release FOR EACH ROW EXECUTE FUNCTION agri.require_strategy_initial_state();
