"""Fire-detections lane constants."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING, Final

from agri_data_service.pipeline.constants import FIRE_DETECTIONS_DIRECT_WRITER_START_DAY, LANE_BASE_ZOOM_TIER
from agri_data_service.warehouse.parquet.tiers import DERIVED_ZOOM_TIERS
from agri_data_service.warehouse.schemas.fire_detections import FIRE_DETECTIONS_CELL_SIZE_DEGREES

if TYPE_CHECKING:
    from agri_data_service.foundation.parquet.zoom import ZoomTier

FIRE_DIRECT_KIND: Final = "observed"
FIRE_DIRECT_ALL_TIERS: Final[tuple[ZoomTier, ...]] = (LANE_BASE_ZOOM_TIER, *DERIVED_ZOOM_TIERS)
FIRE_DIRECT_RUN_ID_PREFIX: Final = "fire-detections-forward:"

FIRE_DIRECT_DEFAULT_LOOKBACK_DAYS: Final = 5
FIRE_DIRECT_MAX_LOOKBACK_DAYS: Final = 5
FIRE_DIRECT_DEFAULT_MAX_DAYS: Final = 5
FIRE_DIRECT_MAX_DAYS: Final = 5
FIRE_DIRECT_DEFAULT_MAX_RECORDS_PER_DAY: Final = 50_000
FIRE_DIRECT_DEFAULT_RETRY_ATTEMPTS: Final = 8
FIRE_DIRECT_MAX_RETRY_ATTEMPTS: Final = 20
FIRE_DIRECT_DEFAULT_RETRY_BASE_SECONDS: Final = 5.0
FIRE_DIRECT_DEFAULT_RETRY_MAX_SECONDS: Final = 60.0
FIRE_DIRECT_DEFAULT_CONTENTION_TIMEOUT_SECONDS: Final = 900.0
FIRE_DIRECT_MAX_RETRY_BASE_SECONDS: Final = 60.0
FIRE_DIRECT_MAX_RETRY_MAX_SECONDS: Final = 300.0
FIRE_DIRECT_MAX_CONTENTION_TIMEOUT_SECONDS: Final = 3_600.0
FIRE_DIRECT_STATEMENT_TIMEOUT_SECONDS: Final = 120
FIRE_DIRECT_MIN_DELAY_SECONDS: Final = 0.1
MONTHS_PER_YEAR: Final = 12
POINT_COORDINATE_COUNT: Final = 2
CELL_SIZE: Final = Decimal(str(FIRE_DETECTIONS_CELL_SIZE_DEGREES))

__all__ = [
    "CELL_SIZE",
    "FIRE_DETECTIONS_DIRECT_WRITER_START_DAY",
    "FIRE_DIRECT_ALL_TIERS",
    "FIRE_DIRECT_DEFAULT_CONTENTION_TIMEOUT_SECONDS",
    "FIRE_DIRECT_DEFAULT_LOOKBACK_DAYS",
    "FIRE_DIRECT_DEFAULT_MAX_DAYS",
    "FIRE_DIRECT_DEFAULT_MAX_RECORDS_PER_DAY",
    "FIRE_DIRECT_DEFAULT_RETRY_ATTEMPTS",
    "FIRE_DIRECT_DEFAULT_RETRY_BASE_SECONDS",
    "FIRE_DIRECT_DEFAULT_RETRY_MAX_SECONDS",
    "FIRE_DIRECT_KIND",
    "FIRE_DIRECT_MAX_CONTENTION_TIMEOUT_SECONDS",
    "FIRE_DIRECT_MAX_DAYS",
    "FIRE_DIRECT_MAX_LOOKBACK_DAYS",
    "FIRE_DIRECT_MAX_RETRY_ATTEMPTS",
    "FIRE_DIRECT_MAX_RETRY_BASE_SECONDS",
    "FIRE_DIRECT_MAX_RETRY_MAX_SECONDS",
    "FIRE_DIRECT_MIN_DELAY_SECONDS",
    "FIRE_DIRECT_RUN_ID_PREFIX",
    "FIRE_DIRECT_STATEMENT_TIMEOUT_SECONDS",
    "MONTHS_PER_YEAR",
    "POINT_COORDINATE_COUNT",
]
