"""Machine-readable North American intervention-evidence source-adapter manifest registry.

This module transcribes every row of `docs/north-america-intervention-source-matrix.md` (the
human-reviewed register) into one typed `InterventionSourceManifest`, keyed by `source_key`. Field
names mirror that document's own "Governance decisions from the matrix" section vocabulary
(`coverage_geometry`, licence snapshot/checksum, access policy, maximum inference scale) rather than
inventing parallel terms. Exactly the three sources `execution/geospatial_pilot.py` has actually
captured and validated (Census TIGERweb Boise boundary, the OSM Hillside to Hollow Reserve way, and
the USFS 2020 WUI AOI clip) carry `adapter_status="implemented"`; every other row is `planned` unless
the matrix names an explicit, current access barrier (a bolded "Blocked" verdict, a licence the matrix
says is unverified/unresolved, or a restrictive non-commercial licence), in which case it is `blocked`
with that reason preserved. Two matrix rows describing an entirely absent public data fabric (Canada
and Mexico WUI/water infrastructure) have no stated access barrier to preserve verbatim; they are
marked `blocked` as the conservative reading, noted here rather than asserted silently.
"""

from __future__ import annotations

from typing import Final, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from agri_data_service.execution.contracts import SHA256_PATTERN

SOURCE_KEY_PATTERN = r"^[a-z0-9][a-z0-9-]{1,98}$"

Jurisdiction = Literal[
    "us-federal",
    "us-state",
    "canada-federal",
    "canada-provincial",
    "mexico-federal",
    "mexico-state",
    "local",
    "continental",
]
AdapterStatus = Literal["implemented", "planned", "blocked"]
AccessPolicy = Literal["open", "registration", "blocked"]
# Mirrors the matrix's own legend (line 5-7): S/P/N/C/R -> structure, parcel/property,
# neighborhood, city/landscape, regional support. "unknown" is a valid result per the matrix's
# governance decisions; it is used wherever a row states no explicit support code.
MaximumInferenceScale = Literal[
    "structure",
    "parcel",
    "neighborhood",
    "city_landscape",
    "regional",
    "unknown",
]


class InterventionSourceManifest(BaseModel):
    """One register row's machine-readable adapter manifest."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    source_key: str = Field(pattern=SOURCE_KEY_PATTERN)
    name: str = Field(min_length=1, max_length=255)
    jurisdiction: Jurisdiction
    adapter_status: AdapterStatus
    licence_identifier: str = Field(min_length=1, max_length=255)
    licence_snapshot_reference: str | None = Field(default=None, max_length=500)
    licence_snapshot_checksum: str | None = Field(default=None, pattern=SHA256_PATTERN)
    access_policy: AccessPolicy
    coverage_geometry: str = Field(min_length=1, max_length=500)
    native_resolution_scale: str = Field(min_length=1, max_length=255)
    maximum_inference_scale: MaximumInferenceScale
    refresh_cadence: str = Field(min_length=1, max_length=255)
    blocking_reason: str | None = Field(default=None, max_length=1000)
    attribution: str = Field(min_length=1, max_length=500)
    attribute_allowlist: tuple[str, ...] = Field(default=())
    domain_allowlist: tuple[str, ...] = Field(default=())

    @model_validator(mode="after")
    def status_and_gating_fields_agree(self) -> InterventionSourceManifest:
        if self.adapter_status == "blocked" and not self.blocking_reason:
            raise ValueError(f"{self.source_key}: adapter_status=blocked requires a blocking_reason")
        if self.adapter_status != "blocked" and self.blocking_reason:
            raise ValueError(f"{self.source_key}: blocking_reason is only valid when adapter_status=blocked")
        if self.adapter_status == "implemented" and not self.attribute_allowlist:
            raise ValueError(f"{self.source_key}: implemented adapters require a non-empty attribute_allowlist")
        if self.adapter_status != "implemented" and self.attribute_allowlist:
            raise ValueError(f"{self.source_key}: attribute_allowlist is only populated for implemented adapters")
        if self.adapter_status != "implemented" and (self.licence_snapshot_reference or self.licence_snapshot_checksum):
            raise ValueError(f"{self.source_key}: licence snapshot evidence is only captured for implemented adapters")
        return self


NORTH_AMERICA_INTERVENTION_MANIFESTS: Final[dict[str, InterventionSourceManifest]] = {
    # -----------------------------------------------------------------------------------------
    # Continental and cross-border sources (matrix lines 13-18)
    # -----------------------------------------------------------------------------------------
    "openstreetmap-basemap": InterventionSourceManifest(
        source_key="openstreetmap-basemap",
        name="OpenStreetMap basemap, buildings, roads, names",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="ODbL 1.0 attribution/share-alike",
        access_policy="open",
        coverage_geometry="US/Canada/Mexico/global",
        native_resolution_scale="Contributor geometry of uneven completeness and vintage",
        maximum_inference_scale="neighborhood",
        refresh_cadence="minutely diffs",
        attribution="© OpenStreetMap contributors",
    ),
    "esa-worldcover": InterventionSourceManifest(
        source_key="esa-worldcover",
        name="ESA WorldCover land cover",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="CC BY 4.0",
        access_policy="open",
        coverage_geometry="Global",
        native_resolution_scale="10 m; reference years 2020 and 2021, reported accuracy 74.4%/76.7%",
        maximum_inference_scale="neighborhood",
        refresh_cadence="biennial reference-year release",
        attribution="ESA WorldCover",
    ),
    "jrc-global-surface-water": InterventionSourceManifest(
        source_key="jrc-global-surface-water",
        name="JRC Global Surface Water",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="Copernicus free-use terms",
        access_policy="open",
        coverage_geometry="Global (Landsat-derived)",
        native_resolution_scale="30 m",
        maximum_inference_scale="neighborhood",
        refresh_cadence="monthly/yearly history, 1984-2024",
        attribution="EC JRC/Google",
    ),
    "nasa-firms-viirs": InterventionSourceManifest(
        source_key="nasa-firms-viirs",
        name="NASA FIRMS VIIRS active thermal detections",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="NASA attribution",
        access_policy="registration",
        coverage_geometry="Global; US/Canada low-latency",
        native_resolution_scale="375 m pixels",
        maximum_inference_scale="city_landscape",
        refresh_cadence="under 3h globally, 1-30min for US/Canada",
        attribution="NASA FIRMS",
    ),
    "daymet-daily-climatology": InterventionSourceManifest(
        source_key="daymet-daily-climatology",
        name="Daymet daily climatology/history",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="NASA/ORNL open download; dataset DOI citation",
        access_policy="open",
        coverage_geometry="North America",
        native_resolution_scale="1 km daily",
        maximum_inference_scale="neighborhood",
        refresh_cadence="annual, 1980 through latest complete year",
        attribution="NASA/ORNL DAAC, Daymet",
    ),
    "isric-soilgrids": InterventionSourceManifest(
        source_key="isric-soilgrids",
        name="ISRIC SoilGrids soils fallback",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="CC BY 4.0",
        access_policy="open",
        coverage_geometry="Global",
        native_resolution_scale="250 m; 14 properties, six depths, prediction uncertainty",
        maximum_inference_scale="city_landscape",
        refresh_cadence="static release; REST beta unstable/paused, prefer WCS/WebDAV",
        attribution="ISRIC SoilGrids",
    ),
    # -----------------------------------------------------------------------------------------
    # United States and Idaho (matrix lines 24-53)
    # -----------------------------------------------------------------------------------------
    "census-tigerweb-boise-2025": InterventionSourceManifest(
        source_key="census-tigerweb-boise-2025",
        name="US Census Bureau TIGERweb Incorporated Place Boundary, Boise City ID",
        jurisdiction="us-federal",
        adapter_status="implemented",
        licence_identifier="US Public Domain",
        licence_snapshot_reference="plans/boise-intervention-capture-v1.json#sources[census-tigerweb-boise-2025]",
        licence_snapshot_checksum="0025169cd38411e915edbb3f03e89f41a6ba7c471f19f807a55e6850107da96c",
        access_policy="open",
        coverage_geometry=(
            "Boise, Idaho incorporated place boundary (GEOID 1608830); the broader TIGER/Line "
            "product covers all US legal/statistical geography and road centerlines"
        ),
        native_resolution_scale="2025 TIGERweb incorporated-place vector; not survey grade",
        maximum_inference_scale="city_landscape",
        refresh_cadence="annual (2025 vintage); shapefile archive 2007+ and older TIGER history",
        attribution="US Census Bureau TIGER/Line 2025",
        attribute_allowlist=(
            "STATE",
            "PLACE",
            "GEOID",
            "BASENAME",
            "NAME",
            "LSADC",
            "FUNCSTAT",
            "AREALAND",
            "AREAWATER",
            "CENTLAT",
            "CENTLON",
        ),
        domain_allowlist=("tigerweb.geo.census.gov",),
    ),
    "census-geocoder": InterventionSourceManifest(
        source_key="census-geocoder",
        name="Census Geocoder",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US public data",
        access_policy="open",
        coverage_geometry="US addresses; current and census benchmarks",
        native_resolution_scale="Address-to-census candidate match only",
        maximum_inference_scale="unknown",
        refresh_cadence="batch and REST endpoints, ongoing",
        attribution="US Census Bureau Geocoder",
    ),
    "idaho-county-parcels": InterventionSourceManifest(
        source_key="idaho-county-parcels",
        name="Idaho State Tax Commission guidance and county assessors",
        jurisdiction="local",
        adapter_status="planned",
        licence_identifier="per-county licence required",
        access_policy="registration",
        coverage_geometry="Idaho counties; state maintains no county parcel fabric",
        native_resolution_scale="county-specific cadence/coverage",
        maximum_inference_scale="parcel",
        refresh_cadence="county-specific",
        attribution="Idaho county assessors",
    ),
    "idwr-parcel-service": InterventionSourceManifest(
        source_key="idwr-parcel-service",
        name="IDWR parcel service (compiled Idaho county polygons)",
        jurisdiction="us-state",
        adapter_status="blocked",
        licence_identifier="provider redistribution prohibition",
        access_policy="blocked",
        coverage_geometry="Compiled Idaho county polygons",
        native_resolution_scale="county-compiled parcel polygons",
        maximum_inference_scale="unknown",
        refresh_cadence="unknown",
        blocking_reason=(
            "Provider says the data cannot be shared outside IDWR; blocked from PlantGeo ingestion and redistribution."
        ),
        attribution="Idaho Department of Water Resources",
    ),
    "osm-hillside-to-hollow-20260723": InterventionSourceManifest(
        source_key="osm-hillside-to-hollow-20260723",
        name="OpenStreetMap Way 674700373 (Hillside to Hollow Reserve v19)",
        jurisdiction="local",
        adapter_status="implemented",
        licence_identifier="Open Database License (ODbL) 1.0",
        licence_snapshot_reference=(
            "plans/boise-intervention-capture-v1.json#sources[osm-hillside-to-hollow-20260723]; "
            "reference_capture checksum b8f3e0e9a7312bdbcf796156a4257eebe1daec8f6880e7c5ead3de0552ca13e0 "
            "pins OSM way 674700373 version 19 at 2025-04-09T18:53:39Z"
        ),
        licence_snapshot_checksum="7552170d903f8f6313c79d20c186f1c192cd4db5bc3865c99919f8458fa789b3",
        access_policy="open",
        coverage_geometry="Hillside to Hollow Reserve, Boise, Idaho (OSM way 674700373, version 19)",
        native_resolution_scale="Contributor-mapped named reserve boundary; no stated positional accuracy",
        maximum_inference_scale="neighborhood",
        refresh_cadence="contributor-edited; this manifest pins version 19 (2025-04-09T18:53:39Z)",
        attribution="© OpenStreetMap contributors",
        attribute_allowlist=("osm_type", "osm_id", "category", "type", "name"),
        domain_allowlist=("nominatim.openstreetmap.org", "api.openstreetmap.org"),
    ),
    "boise-owned-property-parcels": InterventionSourceManifest(
        source_key="boise-owned-property-parcels",
        name="City of Boise Owned Property polygons",
        jurisdiction="local",
        adapter_status="blocked",
        licence_identifier="custom disclaimer only",
        access_policy="blocked",
        coverage_geometry="Public city-owned parcel polygons; 780 records",
        native_resolution_scale="periodic assessor search extract",
        maximum_inference_scale="unknown",
        refresh_cadence="periodic",
        blocking_reason=(
            "Custom disclaimer only; no express open-redistribution grant was verified. "
            "Blocked from this free/open workstream unless written reuse terms are archived."
        ),
        attribution="City of Boise Owned Property service",
    ),
    "ms-global-building-footprints": InterventionSourceManifest(
        source_key="ms-global-building-footprints",
        name="Microsoft Global ML Building Footprints",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="CDLA-Permissive-2.0 (current release; older releases used different terms)",
        access_policy="open",
        coverage_geometry="US/Canada/Mexico/global ML polygons",
        native_resolution_scale="Imagery largely 2014-2021; release-specific confidence/height availability",
        maximum_inference_scale="neighborhood",
        refresh_cadence="per-release; snapshot the exact release licence",
        attribution="Microsoft Global ML Building Footprints",
    ),
    "usgs-3dep-elevation": InterventionSourceManifest(
        source_key="usgs-3dep-elevation",
        name="USGS 3DEP elevation",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US Public Domain",
        access_policy="open",
        coverage_geometry="US",
        native_resolution_scale="Seamless ~10 m; project 1 m bare-earth DEM incomplete nationally",
        maximum_inference_scale="neighborhood",
        refresh_cadence="TNM/API/COGs, versioned by acquisition project",
        attribution="USGS 3D Elevation Program",
    ),
    "usgs-3dhp-wbd-hydrography": InterventionSourceManifest(
        source_key="usgs-3dhp-wbd-hydrography",
        name="USGS 3DHP and WBD hydrography/watersheds",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US Public Domain",
        access_policy="open",
        coverage_geometry="US; WBD harmonized at Canada/Mexico borders",
        native_resolution_scale="3DHP additions quarterly, annual DOI snapshot",
        maximum_inference_scale="neighborhood",
        refresh_cadence="quarterly (3DHP) / annual (WBD); legacy NHD maintenance stopped 2024",
        attribution="USGS 3D Hydrography Program / Watershed Boundary Dataset",
    ),
    "fws-national-wetlands-inventory": InterventionSourceManifest(
        source_key="fws-national-wetlands-inventory",
        name="FWS National Wetlands Inventory",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Federal public distribution",
        access_policy="open",
        coverage_geometry="US/territories; polygons by state/HUC8",
        native_resolution_scale="source age/scale vary",
        maximum_inference_scale="neighborhood",
        refresh_cadence="continuous improvement, May/October releases",
        attribution="US Fish and Wildlife Service NWI",
    ),
    "usgs-ngwmn-idwr-groundwater": InterventionSourceManifest(
        source_key="usgs-ngwmn-idwr-groundwater",
        name="USGS NGWMN and IDWR water levels (groundwater proxy)",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Public agency data",
        access_policy="open",
        coverage_geometry="Selected national wells; Idaho 1,100+ wells",
        native_resolution_scale="Point well records; retain provisional/provider flags",
        maximum_inference_scale="neighborhood",
        refresh_cadence="NGWMN nightly cache; IDWR generally spring/fall measurement",
        attribution="USGS National Ground-Water Monitoring Network / IDWR",
    ),
    "landfire-fuels": InterventionSourceManifest(
        source_key="landfire-fuels",
        name="LANDFIRE fuels/fire regime",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Public domain",
        access_policy="open",
        coverage_geometry="US/territories",
        native_resolution_scale="Native 30 m",
        maximum_inference_scale="neighborhood",
        refresh_cadence="annual versioning targets prior fiscal year; 20+ years of archives",
        attribution="LANDFIRE",
    ),
    "usgs-annual-nlcd": InterventionSourceManifest(
        source_key="usgs-annual-nlcd",
        name="Annual NLCD land cover",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US Public Domain",
        access_policy="open",
        coverage_geometry="CONUS",
        native_resolution_scale="30 m annual",
        maximum_inference_scale="neighborhood",
        refresh_cadence="annual, 1985-2025",
        attribution="USGS EROS Annual NLCD",
    ),
    "usda-cropland-data-layer": InterventionSourceManifest(
        source_key="usda-cropland-data-layer",
        name="USDA Cropland Data Layer",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US Public Domain",
        access_policy="open",
        coverage_geometry="CONUS",
        native_resolution_scale="30 m through 2023, 10 m starting 2024",
        maximum_inference_scale="neighborhood",
        refresh_cadence="annual; national series 2008+",
        attribution="USDA NASS CropScape/CDL",
    ),
    "nifc-fire-perimeters": InterventionSourceManifest(
        source_key="nifc-fire-perimeters",
        name="NIFC maps and open data (fire perimeters/occurrences)",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Federal public service",
        access_policy="open",
        coverage_geometry="US",
        native_resolution_scale="Interagency active incidents/perimeters",
        maximum_inference_scale="neighborhood",
        refresh_cadence="updated daily; historical products downloadable",
        attribution="National Interagency Fire Center",
    ),
    "mtbs-burn-severity": InterventionSourceManifest(
        source_key="mtbs-burn-severity",
        name="MTBS v1.2 burn history/severity",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="CC0",
        access_policy="open",
        coverage_geometry="US/territories; fires >=1,000 acres west / >=500 acres east only",
        native_resolution_scale="Landsat 30 m",
        maximum_inference_scale="neighborhood",
        refresh_cadence="annual, 1984-2024",
        attribution="MTBS v1.2 (April 2025)",
    ),
    "usdm-drought-history": InterventionSourceManifest(
        source_key="usdm-drought-history",
        name="US Drought Monitor",
        jurisdiction="us-federal",
        adapter_status="blocked",
        licence_identifier="citation required; redistribution licence unverified",
        access_policy="blocked",
        coverage_geometry="US/territories",
        native_resolution_scale="Authoritative vector; display-derived 500 m raster; pre-2004 vectors ~4-mile error",
        maximum_inference_scale="city_landscape",
        refresh_cadence="weekly Thursday using data through Tuesday, 1999/2000+",
        blocking_reason=(
            "Required NDMC/USDA/NOAA citation; an explicit redistribution licence was not found, so "
            "terms need archival review (USDM history redistribution-licence-unverified)."
        ),
        attribution="US Drought Monitor / NDMC / USDA / NOAA",
    ),
    "noaa-ghcn-weather-observations": InterventionSourceManifest(
        source_key="noaa-ghcn-weather-observations",
        name="NOAA GHCN-D and GHCN-H weather observations",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="US federal records public domain; international contributor flags may restrict reuse",
        access_policy="open",
        coverage_geometry="Global stations",
        native_resolution_scale="Point station facts; gridding is model-derived",
        maximum_inference_scale="unknown",
        refresh_cadence="daily updates; archive-quality US replacements can lag 45-60 days",
        attribution="NOAA NCEI GHCN-Daily / GHCN-Hourly",
    ),
    "noaa-hrrr-weather-model": InterventionSourceManifest(
        source_key="noaa-hrrr-weather-model",
        name="NOAA HRRR near-term weather model",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="NOAA public data",
        access_policy="open",
        coverage_geometry="CONUS",
        native_resolution_scale="3 km",
        maximum_inference_scale="neighborhood",
        refresh_cadence="hourly cycles, 18h forecasts and 48h at 00/06/12/18 UTC",
        attribution="NOAA HRRR",
    ),
    "goes-r-glm-lightning": InterventionSourceManifest(
        source_key="goes-r-glm-lightning",
        name="GOES-R GLM lightning",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="NOAA public data",
        access_policy="open",
        coverage_geometry="Americas",
        native_resolution_scale="About 8 km at nadir / 14 km edge",
        maximum_inference_scale="city_landscape",
        refresh_cadence="~20s latency, operational GOES-R era",
        attribution="NOAA GOES-R Geostationary Lightning Mapper",
    ),
    "nasa-smap-soil-moisture": InterventionSourceManifest(
        source_key="nasa-smap-soil-moisture",
        name="SMAP L3 v9 soil moisture",
        jurisdiction="continental",
        adapter_status="planned",
        licence_identifier="NASA/NSIDC (Earthdata terms)",
        access_policy="registration",
        coverage_geometry="Global",
        native_resolution_scale="Daily 36 km since 2015; enhanced 9 km products exist",
        maximum_inference_scale="city_landscape",
        refresh_cadence="nominal ~2-day latency",
        attribution="NASA/NSIDC SMAP L3 v9",
    ),
    "usda-ssurgo-soils": InterventionSourceManifest(
        source_key="usda-ssurgo-soils",
        name="USDA SSURGO soils",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="US federal/open download",
        access_policy="open",
        coverage_geometry="Most US/territories",
        native_resolution_scale="Historical mapping commonly 1:12,000-1:63,360",
        maximum_inference_scale="parcel",
        refresh_cadence="annual October 1 refresh",
        attribution="USDA NRCS SSURGO",
    ),
    "usfs-wui-2020-hillside-hollow": InterventionSourceManifest(
        source_key="usfs-wui-2020-hillside-hollow",
        name="USDA Forest Service 2020 Wildland-Urban Interface Census Block Data",
        jurisdiction="us-federal",
        adapter_status="implemented",
        licence_identifier="United States Government work; public use",
        licence_snapshot_reference="plans/boise-intervention-capture-v1.json#sources[usfs-wui-2020-hillside-hollow]",
        licence_snapshot_checksum="b3a198baeb277b65735381240e9919be317978b6bb6a8ff75ac88ce24ae212da",
        access_policy="open",
        coverage_geometry=(
            "USFS WUI AOI clipped to the Hillside to Hollow Reserve property bounding box "
            "(-116.2291822,43.6412367,-116.2039405,43.6615111); national CONUS product"
        ),
        native_resolution_scale="2020 Census block aggregation with 2019 NLCD vegetation context",
        maximum_inference_scale="neighborhood",
        refresh_cadence="updated as needed; current release is the 2020 classification",
        attribution="USDA Forest Service Research Data Archive",
        attribute_allowlist=(
            "objectid",
            "blk20",
            "state",
            "veg2019pc",
            "hu2020",
            "huden2020",
            "wuiflag2020",
            "wuiclass2020",
        ),
        domain_allowlist=("apps.fs.usda.gov",),
    ),
    "boise-regulatory-wui": InterventionSourceManifest(
        source_key="boise-regulatory-wui",
        name="City of Boise WUI regulatory layer and municipal code",
        jurisdiction="local",
        adapter_status="blocked",
        licence_identifier="public ArcGIS service; redistribution permission unresolved",
        access_policy="blocked",
        coverage_geometry="City of Boise; two current IR classes",
        native_resolution_scale="Source layer updated by City GIS; maps are generalized",
        maximum_inference_scale="unknown",
        refresh_cadence="code requires reevaluation at least every five years",
        blocking_reason=(
            "Public ArcGIS service with City attribution/custom disclaimer; redistribution "
            "permission unresolved. Blocked from this free/open workstream."
        ),
        attribution="City of Boise GIS / municipal code",
    ),
    "census-tiger-roads-egress": InterventionSourceManifest(
        source_key="census-tiger-roads-egress",
        name="Census TIGER plus state/local open roads (roads/egress)",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Public-domain federal base; local terms per jurisdiction",
        access_policy="open",
        coverage_geometry="US annual centerlines; local attributes vary",
        native_resolution_scale="Static topology only; no closures/capacity",
        maximum_inference_scale="unknown",
        refresh_cadence="annual",
        attribution="US Census Bureau TIGER/Line plus state/local sources",
    ),
    "epa-cws-service-areas": InterventionSourceManifest(
        source_key="epa-cws-service-areas",
        name="EPA CWS public water system service areas",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Public feature services/data/code",
        access_policy="open",
        coverage_geometry="US; 44k+ systems, ~99% reported population",
        native_resolution_scale="Authoritative and modeled polygons coexist",
        maximum_inference_scale="neighborhood",
        refresh_cadence="v3 March 2026",
        attribution="EPA public water system service areas",
    ),
    "epa-echo-regulated-facilities": InterventionSourceManifest(
        source_key="epa-echo-regulated-facilities",
        name="EPA ECHO regulated facilities",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Bulk downloads preferred; no warranty",
        access_policy="open",
        coverage_geometry="US regulated facilities",
        native_resolution_scale="Coordinates can be unverified",
        maximum_inference_scale="neighborhood",
        refresh_cadence="most exports weekly, drinking-water data quarterly",
        attribution="EPA ECHO",
    ),
    "fema-nfhl-flood": InterventionSourceManifest(
        source_key="fema-nfhl-flood",
        name="FEMA National Flood Hazard Layer",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Free official downloads",
        access_policy="open",
        coverage_geometry="US effective NFIP hazard geodatabases; coverage/date varies",
        native_resolution_scale="FIRM/LOMC and authority remain controlling",
        maximum_inference_scale="parcel",
        refresh_cadence="varies; effective-data driven",
        attribution="FEMA National Flood Hazard Layer",
    ),
    "usgs-pad-us-conservation": InterventionSourceManifest(
        source_key="usgs-pad-us-conservation",
        name="PAD-US protected areas conservation inventory",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="CC0",
        access_policy="open",
        coverage_geometry="US protected/public/nonprofit inventory",
        native_resolution_scale="v4.1 March 2025",
        maximum_inference_scale="neighborhood",
        refresh_cadence="versioned release",
        attribution="USGS PAD-US",
    ),
    "fws-critical-habitat": InterventionSourceManifest(
        source_key="fws-critical-habitat",
        name="FWS critical habitat designations",
        jurisdiction="us-federal",
        adapter_status="planned",
        licence_identifier="Federal public access",
        access_policy="open",
        coverage_geometry="US proposed/final designations",
        native_resolution_scale="Known NMFS/mapper gaps",
        maximum_inference_scale="neighborhood",
        refresh_cadence="services update weekly/monthly",
        attribution="US Fish and Wildlife Service critical habitat",
    ),
    # -----------------------------------------------------------------------------------------
    # Canada (matrix lines 59-70)
    # -----------------------------------------------------------------------------------------
    "statcan-cgndb-boundaries": InterventionSourceManifest(
        source_key="statcan-cgndb-boundaries",
        name="Statistics Canada boundaries/names and CGNDB",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="Open Government Licence Canada",
        access_policy="open",
        coverage_geometry="National census geographies",
        native_resolution_scale="~350k official names",
        maximum_inference_scale="neighborhood",
        refresh_cadence="five-year census cycle with selected annual files; names quarterly",
        attribution="Statistics Canada / Canadian Geographical Names Database",
    ),
    "canada-parcels-cadastre": InterventionSourceManifest(
        source_key="canada-parcels-cadastre",
        name="Canada Lands and ParcelMap BC (parcels/cadastre)",
        jurisdiction="canada-provincial",
        adapter_status="planned",
        licence_identifier="jurisdiction/product-specific; do not treat paid LTSA products as open",
        access_policy="registration",
        coverage_geometry="No national ordinary parcel fabric; Canada Lands territories/reserves/parks/offshore",
        native_resolution_scale="BC open view 2M+ parcels; Ontario is not open",
        maximum_inference_scale="parcel",
        refresh_cadence="weekly (Canada Lands, ParcelMap BC)",
        attribution="Natural Resources Canada / LTSA ParcelMap BC",
    ),
    "canada-open-database-buildings": InterventionSourceManifest(
        source_key="canada-open-database-buildings",
        name="Open Database of Buildings v3",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="14.4M footprints from 530 datasets/107 governments",
        native_resolution_scale="Uneven vintage/completeness",
        maximum_inference_scale="neighborhood",
        refresh_cadence="April 2025 release",
        attribution="Statistics Canada Open Database of Buildings",
    ),
    "canada-mrdem-elevation": InterventionSourceManifest(
        source_key="canada-mrdem-elevation",
        name="MRDEM elevation",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="National 30 m DTM/DSM; partial 1-2 m HRDEM",
        native_resolution_scale="Inputs ~2006-2023; HRDEM 2.23M km^2 by June 2026",
        maximum_inference_scale="neighborhood",
        refresh_cadence="ongoing national elevation strategy",
        attribution="Natural Resources Canada MRDEM",
    ),
    "canada-nhn-chn-hydrography": InterventionSourceManifest(
        source_key="canada-nhn-chn-hydrography",
        name="NHN and CHN hydrography",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="NHN 1:50,000+ (unmaintained since 2022); CHN approaches 1:2,000, ~58k km^2 by 2026",
        maximum_inference_scale="neighborhood",
        refresh_cadence="CHN ongoing; NHN unmaintained since 2022",
        attribution="Natural Resources Canada NHN / Canadian Hydrospatial Network",
    ),
    "canada-wetland-groundwater": InterventionSourceManifest(
        source_key="canada-wetland-groundwater",
        name="Wetland Inventory v3A and Groundwater Information Network",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="National; heterogeneous well data absent for PEI/NB/NWT/Nunavut",
        native_resolution_scale="10 m 2016-2020 wetland model, reported 90.5% mean accuracy",
        maximum_inference_scale="parcel",
        refresh_cadence="wetland model versioned; wells ongoing",
        attribution="Environment and Climate Change Canada",
    ),
    "canada-fuels-landcover-canopy": InterventionSourceManifest(
        source_key="canada-fuels-landcover-canopy",
        name="CFS 2024 FBP, NRCan land cover, and 2022 forest attributes",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="30 m; land-cover epochs 2010/2015/2020; forest attributes strategic",
        maximum_inference_scale="parcel",
        refresh_cadence="epoch-versioned",
        attribution="Canadian Forest Service / Natural Resources Canada",
    ),
    "canada-national-fire-database": InterventionSourceManifest(
        source_key="canada-national-fire-database",
        name="Canadian National Fire Database",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada; contributor precision/completeness varies",
        access_policy="open",
        coverage_geometry="Agency-contributed history, varies by province",
        native_resolution_scale="1910s/1920s through mostly 2024",
        maximum_inference_scale="neighborhood",
        refresh_cadence="active locations daily",
        attribution="Canadian Forest Service Wildfire Information System",
    ),
    "canada-drought-weather-lightning": InterventionSourceManifest(
        source_key="canada-drought-weather-lightning",
        name="Canadian Drought Monitor, ECCC open data, HRDPS, HRDPA, CaLDAS, lightning",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada or ECCC end-use licence",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="2.5 km weather/precip/land analyses; lightning 2.5 km/10 min",
        maximum_inference_scale="neighborhood",
        refresh_cadence="drought monthly since 2002; weather 3-hourly to four runs/day",
        attribution="Environment and Climate Change Canada",
    ),
    "canada-soils-crop-inventory": InterventionSourceManifest(
        source_key="canada-soils-crop-inventory",
        name="Soil Landscapes 3.2 and Annual Crop Inventory",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="Soil polygons mainly agricultural/2013-era; crops annual",
        native_resolution_scale="100 m modeled soil grids; crops 30 m since 2011",
        maximum_inference_scale="parcel",
        refresh_cadence="crops annual since 2009",
        attribution="Agriculture and Agri-Food Canada",
    ),
    "canada-roads-conservation": InterventionSourceManifest(
        source_key="canada-roads-conservation",
        name="National Road Network and CPCAD",
        jurisdiction="canada-federal",
        adapter_status="planned",
        licence_identifier="OGL Canada",
        access_policy="open",
        coverage_geometry="13 jurisdictional road datasets; protected/conserved compilation",
        native_resolution_scale="Static egress and constraint screening only",
        maximum_inference_scale="neighborhood",
        refresh_cadence="roads annual; protected/conserved at least annual",
        attribution="Natural Resources Canada / CPCAD",
    ),
    "canada-wui-water-infrastructure": InterventionSourceManifest(
        source_key="canada-wui-water-infrastructure",
        name="Canada WUI/water infrastructure",
        jurisdiction="canada-federal",
        adapter_status="blocked",
        licence_identifier="local licence/security review required",
        access_policy="blocked",
        coverage_geometry="No complete authoritative national public fabric verified",
        native_resolution_scale="unknown",
        maximum_inference_scale="unknown",
        refresh_cadence="unknown",
        blocking_reason=(
            "No complete authoritative national public fabric verified; local licence/security "
            "review required before any WUI or water-infrastructure adapter can be built. Any "
            "WUI model must be labeled derived; never infer pipes, pressure, hydrants, service, "
            "or capacity from service-area context."
        ),
        attribution="No verified national provider",
    ),
    # -----------------------------------------------------------------------------------------
    # Mexico (matrix lines 76-90)
    # -----------------------------------------------------------------------------------------
    "inegi-marco-geoestadistico": InterventionSourceManifest(
        source_key="inegi-marco-geoestadistico",
        name="INEGI Marco Geoestadistico 2025 boundaries/streets",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI free-use terms",
        access_policy="open",
        coverage_geometry="National state/municipal statistical areas, localities, AGEBs, blocks, street axes",
        native_resolution_scale="No national open address geocoder verified",
        maximum_inference_scale="parcel",
        refresh_cadence="2025 reference period; annual editions since at least 2019",
        attribution="INEGI Marco Geoestadistico",
    ),
    "mexico-parcels-cadastre": InterventionSourceManifest(
        source_key="mexico-parcels-cadastre",
        name="Mexico parcels/cadastre",
        jurisdiction="mexico-state",
        adapter_status="planned",
        licence_identifier="local terms required; agricultural-unit geometry confidential",
        access_policy="registration",
        coverage_geometry="No national open legal parcel fabric; state/municipal cadastral offices",
        native_resolution_scale="Census reports cadastre statistics, not geometry",
        maximum_inference_scale="parcel",
        refresh_cadence="unknown",
        attribution="State/municipal cadastral offices (Mexico)",
    ),
    "inegi-topographic-information": InterventionSourceManifest(
        source_key="inegi-topographic-information",
        name="INEGI Topographic Information 2024 (buildings/topography)",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National, ~2M km^2 and 17M+ features including building objects",
        native_resolution_scale="1:50,000",
        maximum_inference_scale="neighborhood",
        refresh_cadence="2024 edition",
        attribution="INEGI Topographic Information",
    ),
    "inegi-cem-elevation": InterventionSourceManifest(
        source_key="inegi-cem-elevation",
        name="INEGI CEM elevation",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="15 m; CEM 3.0 metadata dates generation to 2012",
        maximum_inference_scale="parcel",
        refresh_cadence="unversioned since 2012 metadata",
        attribution="INEGI Continuo de Elevaciones Mexicano",
    ),
    "inegi-hydrographic-network": InterventionSourceManifest(
        source_key="inegi-hydrographic-network",
        name="INEGI Hydrographic Network v2",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="1:50,000; 2010 edition",
        maximum_inference_scale="neighborhood",
        refresh_cadence="2010 edition, dated",
        attribution="INEGI Hydrographic Network",
    ),
    "conagua-wetlands-groundwater": InterventionSourceManifest(
        source_key="conagua-wetlands-groundwater",
        name="CONAGUA National Wetland Inventory and 653 aquifers",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="public access; redistribution terms dataset-specific",
        access_policy="registration",
        coverage_geometry="National wetlands (~25 ha minimum mapping unit); 653 aquifers",
        native_resolution_scale="1:250k-1:50k inputs; aquifer legal availability 2023/2024 viewer",
        maximum_inference_scale="city_landscape",
        refresh_cadence="unknown",
        attribution="CONAGUA",
    ),
    "inegi-conafor-vegetation-fuels": InterventionSourceManifest(
        source_key="inegi-conafor-vegetation-fuels",
        name="INEGI Land Use and Vegetation Series VII and CONAFOR INFyS",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="1:250,000 based on 2018 imagery/field work; forest inventory samples 2015-2020",
        maximum_inference_scale="city_landscape",
        refresh_cadence="no fixed cadence since late 1970s",
        attribution="INEGI / CONAFOR INFyS",
    ),
    "conafor-fire-occurrence": InterventionSourceManifest(
        source_key="conafor-fire-occurrence",
        name="CONAFOR open wildfire data (fire occurrence)",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="CC BY 4.0",
        access_policy="open",
        coverage_geometry="National agency incidents",
        native_resolution_scale="Records may be revised",
        maximum_inference_scale="city_landscape",
        refresh_cadence="annual files 2010+ and current-year CSV",
        attribution="CONAFOR open wildfire data",
    ),
    "conabio-satif-active-fire": InterventionSourceManifest(
        source_key="conabio-satif-active-fire",
        name="CONABIO SATIF active fire exclusion",
        jurisdiction="mexico-federal",
        adapter_status="blocked",
        licence_identifier="CC BY-NC 2.5 MX",
        access_policy="blocked",
        coverage_geometry="MODIS 1 km and VIIRS 750/375 m; history since 2000, selected burned areas",
        native_resolution_scale="roughly 30-minute automation",
        maximum_inference_scale="unknown",
        refresh_cadence="~30 min",
        blocking_reason="CC BY-NC 2.5 MX licence; blocked from a commercial redistribution path without permission.",
        attribution="CONABIO SATIF",
    ),
    "smn-drought-weather": InterventionSourceManifest(
        source_key="smn-drought-weather",
        name="SMN drought monitor, station archive, forecast API",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="dataset-specific terms (shapefile requires emailed request)",
        access_policy="registration",
        coverage_geometry="National; 5,400+ stations/~2,800 reporting",
        native_resolution_scale="Drought D0-D4 from 2003, fortnightly since 2014",
        maximum_inference_scale="neighborhood",
        refresh_cadence="municipal 3-day daily/48-hour hourly forecasts updated ~75 min",
        attribution="Servicio Meteorologico Nacional (Mexico)",
    ),
    "inegi-edaphological-series": InterventionSourceManifest(
        source_key="inegi-edaphological-series",
        name="INEGI Edaphological Series II soils",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National",
        native_resolution_scale="1:250,000",
        maximum_inference_scale="city_landscape",
        refresh_cadence="no fixed published refresh",
        attribution="INEGI Edaphological Series II",
    ),
    "inegi-national-road-network": InterventionSourceManifest(
        source_key="inegi-national-road-network",
        name="INEGI National Road Network (roads/egress)",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="INEGI terms",
        access_policy="open",
        coverage_geometry="National; ~178,608 km roads, 530,493 km rural roads, 274,097 km urban streets (2025)",
        native_resolution_scale="Static topology only",
        maximum_inference_scale="unknown",
        refresh_cadence="annual",
        attribution="INEGI National Road Network",
    ),
    "mexico-agriculture-statistics": InterventionSourceManifest(
        source_key="mexico-agriculture-statistics",
        name="DGSIAP/SIAP statistics and Frontera Agricola",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="public access; dataset-specific reuse terms",
        access_policy="registration",
        coverage_geometry="National statistics to 1980; municipal mainly 2003-2024",
        native_resolution_scale="Field screening about 1:10,000 using SPOT imagery",
        maximum_inference_scale="parcel",
        refresh_cadence="targeted rather than complete annual refresh",
        attribution="SADER DGSIAP / SIAP",
    ),
    "conanp-conservation": InterventionSourceManifest(
        source_key="conanp-conservation",
        name="CONANP GIS conservation/regulation",
        jurisdiction="mexico-federal",
        adapter_status="planned",
        licence_identifier="public download; redistribution terms need capture",
        access_policy="registration",
        coverage_geometry="Federal protected areas, zoning, voluntary conservation",
        native_resolution_scale="Layer dates vary through 2025-2026",
        maximum_inference_scale="neighborhood",
        refresh_cadence="varies by layer",
        attribution="CONANP GIS",
    ),
    "mexico-water-infrastructure-wui": InterventionSourceManifest(
        source_key="mexico-water-infrastructure-wui",
        name="Mexico water infrastructure/WUI",
        jurisdiction="mexico-federal",
        adapter_status="blocked",
        licence_identifier="local/operator licence and security review required",
        access_policy="blocked",
        coverage_geometry="Major hydraulic works at regional map scale; ~210 reservoir levels",
        native_resolution_scale="No complete national public potable network or WUI verified",
        maximum_inference_scale="city_landscape",
        refresh_cadence="unknown",
        blocking_reason=(
            "No complete national public potable network or WUI verified; local/operator "
            "licence and security review required before any adapter can be built. Any WUI is "
            "derived; no pipe, hydrant, pressure, hookup, or capacity inference."
        ),
        attribution="No verified national provider",
    ),
}
