-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.cell_source_crosswalk (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_release_id uuid NOT NULL,
    cell_id uuid NOT NULL,
    native_feature_key character varying(255) NOT NULL,
    native_geometry public.geometry(Geometry,4326) NOT NULL,
    native_resolution_m integer,
    mapping_method character varying(100) NOT NULL,
    coverage_fraction double precision NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    spatial_support_kind character varying(32) NOT NULL,
    CONSTRAINT ck_cell_source_crosswalk_ck_cell_source_crosswalk_known_4ebd CHECK (((spatial_support_kind)::text = ANY ((ARRAY['native_grid_cell'::character varying, 'native_polygon'::character varying, 'point_sample'::character varying, 'area_aggregate'::character varying, 'unknown'::character varying])::text[]))),
    CONSTRAINT ck_cell_source_crosswalk_positive_native_resolution CHECK (((native_resolution_m IS NULL) OR (native_resolution_m > 0))),
    CONSTRAINT ck_cell_source_crosswalk_valid_coverage CHECK (((coverage_fraction > (0)::double precision) AND (coverage_fraction <= (1)::double precision)))
);

-- CONSTRAINT: cell_source_crosswalk pk_cell_source_crosswalk
ALTER TABLE ONLY agri.cell_source_crosswalk
    ADD CONSTRAINT pk_cell_source_crosswalk PRIMARY KEY (id);

-- CONSTRAINT: cell_source_crosswalk uq_cell_source_crosswalk_release_feature_cell
ALTER TABLE ONLY agri.cell_source_crosswalk
    ADD CONSTRAINT uq_cell_source_crosswalk_release_feature_cell UNIQUE (source_release_id, native_feature_key, cell_id);

-- INDEX: ix_cell_source_crosswalk_geometry
CREATE INDEX ix_cell_source_crosswalk_geometry ON agri.cell_source_crosswalk USING gist (native_geometry);

-- INDEX: ix_cell_source_crosswalk_release_cell
CREATE INDEX ix_cell_source_crosswalk_release_cell ON agri.cell_source_crosswalk USING btree (source_release_id, cell_id);
