-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.climate_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id uuid NOT NULL,
    source character varying(10) NOT NULL,
    annual_precip_mm double precision,
    growing_season_days integer,
    avg_temp_c double precision,
    min_temp_c double precision,
    max_temp_c double precision,
    frost_free_days integer,
    koppen_zone character varying(10),
    aridity_index double precision,
    monthly_precip_json jsonb,
    monthly_temp_json jsonb,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_climate_profiles_climate_source CHECK (((source)::text = ANY ((ARRAY['prism'::character varying, 'noaa'::character varying, 'nasa_power'::character varying])::text[])))
);

-- CONSTRAINT: climate_profiles pk_climate_profiles
ALTER TABLE ONLY agri.climate_profiles
    ADD CONSTRAINT pk_climate_profiles PRIMARY KEY (id);

-- INDEX: ix_climate_profiles_location_id
CREATE INDEX ix_climate_profiles_location_id ON agri.climate_profiles USING btree (location_id);
