-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.data_source (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    owner character varying(255) NOT NULL,
    purpose text NOT NULL,
    base_url character varying(1000),
    license_name character varying(255) NOT NULL,
    license_url character varying(1000),
    citation text NOT NULL,
    refresh_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    retention_days integer,
    allowed_client_exposure boolean DEFAULT false NOT NULL,
    review_state character varying(8) DEFAULT 'draft'::character varying NOT NULL,
    review_due_at timestamp with time zone,
    reviewed_at timestamp with time zone,
    reviewed_by character varying(255),
    is_active boolean DEFAULT true NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_data_source_approved_source_has_review CHECK ((((review_state)::text <> 'approved'::text) OR (reviewed_at IS NOT NULL))),
    CONSTRAINT ck_data_source_positive_retention_days CHECK (((retention_days IS NULL) OR (retention_days > 0))),
    CONSTRAINT ck_data_source_source_review_state CHECK (((review_state)::text = ANY (ARRAY[('draft'::character varying)::text, ('reviewed'::character varying)::text, ('approved'::character varying)::text, ('rejected'::character varying)::text, ('retired'::character varying)::text])))
);

-- CONSTRAINT: data_source pk_data_source
ALTER TABLE ONLY agri.data_source
    ADD CONSTRAINT pk_data_source PRIMARY KEY (id);

-- CONSTRAINT: data_source uq_data_source_key
ALTER TABLE ONLY agri.data_source
    ADD CONSTRAINT uq_data_source_key UNIQUE (key);
