-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.drought_polygon_snapshot (
    id bigint NOT NULL,
    source_release_id uuid NOT NULL,
    issue_date date NOT NULL,
    severity_class smallint NOT NULL,
    impact_type character varying(8) DEFAULT 'none'::character varying NOT NULL,
    geometry public.geometry(MultiPolygon,4326) NOT NULL,
    geometry_checksum character varying(64) NOT NULL,
    data_available_at timestamp with time zone NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_drought_polygon_geometry_checksum_sha256 CHECK (((geometry_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_drought_polygon_valid_severity CHECK (((severity_class >= 0) AND (severity_class <= 4)))
);

-- SEQUENCE OWNED BY: drought_polygon_snapshot_id_seq
ALTER SEQUENCE agri.drought_polygon_snapshot_id_seq OWNED BY agri.drought_polygon_snapshot.id;

-- DEFAULT: drought_polygon_snapshot id
ALTER TABLE ONLY agri.drought_polygon_snapshot ALTER COLUMN id SET DEFAULT nextval('agri.drought_polygon_snapshot_id_seq'::regclass);

-- CONSTRAINT: drought_polygon_snapshot pk_drought_polygon_snapshot
ALTER TABLE ONLY agri.drought_polygon_snapshot
    ADD CONSTRAINT pk_drought_polygon_snapshot PRIMARY KEY (id);

-- CONSTRAINT: drought_polygon_snapshot uq_drought_polygon_release_identity
ALTER TABLE ONLY agri.drought_polygon_snapshot
    ADD CONSTRAINT uq_drought_polygon_release_identity UNIQUE (source_release_id, severity_class, impact_type, geometry_checksum);

-- INDEX: ix_drought_polygon_snapshot_geometry
CREATE INDEX ix_drought_polygon_snapshot_geometry ON agri.drought_polygon_snapshot USING gist (geometry);

-- INDEX: ix_drought_polygon_snapshot_issue_date
CREATE INDEX ix_drought_polygon_snapshot_issue_date ON agri.drought_polygon_snapshot USING btree (issue_date);
