-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.expert_label_release (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    release_key character varying(255) NOT NULL,
    harvest_document_uri character varying(2000) NOT NULL,
    harvest_document_checksum character varying(64) NOT NULL,
    harvested_at timestamp with time zone NOT NULL,
    label_count integer NOT NULL,
    draft_count integer NOT NULL,
    agent_reviewed_count integer NOT NULL,
    approved_count integer DEFAULT 0 NOT NULL,
    rejected_count integer NOT NULL,
    slice_summary jsonb NOT NULL,
    review_tier character varying(64) DEFAULT 'agent_reviewed_pending_owner_signature'::character varying NOT NULL,
    owner_signature_reference character varying(500),
    owner_signed_at timestamp with time zone,
    release_checksum character varying(64) NOT NULL,
    loader_code_checksum character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_expert_label_release_checksums CHECK ((((harvest_document_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((loader_code_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_expert_label_release_counts CHECK (((label_count >= 0) AND (draft_count >= 0) AND (agent_reviewed_count >= 0) AND (approved_count >= 0) AND (rejected_count >= 0) AND (label_count = (((draft_count + agent_reviewed_count) + approved_count) + rejected_count)))),
    CONSTRAINT ck_expert_label_release_owner_signature CHECK ((((review_tier)::text <> 'owner_signed'::text) OR ((owner_signature_reference IS NOT NULL) AND (owner_signed_at IS NOT NULL)))),
    CONSTRAINT ck_expert_label_release_slice_summary CHECK ((jsonb_typeof(slice_summary) = 'object'::text)),
    CONSTRAINT ck_expert_label_release_tier CHECK (((review_tier)::text = ANY (ARRAY[('draft'::character varying)::text, ('agent_reviewed_pending_owner_signature'::character varying)::text, ('owner_signed'::character varying)::text])))
);

-- CONSTRAINT: expert_label_release pk_expert_label_release
ALTER TABLE ONLY agri.expert_label_release
    ADD CONSTRAINT pk_expert_label_release PRIMARY KEY (id);

-- CONSTRAINT: expert_label_release uq_expert_label_release_key
ALTER TABLE ONLY agri.expert_label_release
    ADD CONSTRAINT uq_expert_label_release_key UNIQUE (release_key);
