-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.expert_label_training_instance (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    label_id uuid NOT NULL,
    release_id uuid NOT NULL,
    spatial_cell_id uuid NOT NULL,
    observed_date date NOT NULL,
    as_of_time timestamp with time zone NOT NULL,
    feature_schema_version character varying(64) NOT NULL,
    feature_values jsonb NOT NULL,
    feature_checksum character varying(64) NOT NULL,
    envelope_match jsonb NOT NULL,
    unexpressible_terms jsonb NOT NULL,
    match_state character varying(24) NOT NULL,
    instance_checksum character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_expert_label_training_instance_checksums CHECK ((((feature_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((instance_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_expert_label_training_instance_json CHECK (((jsonb_typeof(feature_values) = 'array'::text) AND (jsonb_typeof(envelope_match) = 'object'::text) AND (jsonb_typeof(unexpressible_terms) = 'array'::text))),
    CONSTRAINT ck_expert_label_training_instance_state CHECK (((match_state)::text = ANY (ARRAY[('matched'::character varying)::text, ('excluded'::character varying)::text, ('unexpressible'::character varying)::text])))
);

-- CONSTRAINT: expert_label_training_instance pk_expert_label_training_instance
ALTER TABLE ONLY agri.expert_label_training_instance
    ADD CONSTRAINT pk_expert_label_training_instance PRIMARY KEY (id);

-- CONSTRAINT: expert_label_training_instance uq_expert_label_training_instance_identity
ALTER TABLE ONLY agri.expert_label_training_instance
    ADD CONSTRAINT uq_expert_label_training_instance_identity UNIQUE (label_id, spatial_cell_id, observed_date, feature_schema_version);

-- INDEX: ix_expert_label_training_instance_release_state
CREATE INDEX ix_expert_label_training_instance_release_state ON agri.expert_label_training_instance USING btree (release_id, match_state, observed_date);
