-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.expert_label (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    label_key character varying(255) NOT NULL,
    release_id uuid NOT NULL,
    source_id uuid NOT NULL,
    label_kind character varying(32) NOT NULL,
    subject character varying(255) NOT NULL,
    subject_normalized character varying(255) NOT NULL,
    outcome character varying(24) NOT NULL,
    condition_envelope jsonb NOT NULL,
    envelope_checksum character varying(64) NOT NULL,
    rationale text NOT NULL,
    supporting_quote text,
    confidence character varying(16) NOT NULL,
    confidence_weight double precision NOT NULL,
    harvest_slice character varying(120) NOT NULL,
    citation_check_refuted boolean NOT NULL,
    citation_check_doi_resolves boolean NOT NULL,
    citation_check_reason text NOT NULL,
    review_state character varying(24) DEFAULT 'draft'::character varying NOT NULL,
    review_note text,
    reviewed_by character varying(255),
    reviewed_at timestamp with time zone,
    owner_signature_reference character varying(500),
    label_checksum character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_expert_label_agent_review_not_refuted CHECK ((((review_state)::text <> ALL (ARRAY['agent_reviewed'::text, 'approved'::text])) OR (citation_check_refuted = false))),
    CONSTRAINT ck_expert_label_approval_needs_owner_signature CHECK ((((review_state)::text <> 'approved'::text) OR ((COALESCE(owner_signature_reference, ''::character varying))::text <> ''::text))),
    CONSTRAINT ck_expert_label_checksums CHECK ((((label_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((envelope_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_expert_label_confidence CHECK ((((confidence)::text = ANY (ARRAY[('high'::character varying)::text, ('medium'::character varying)::text, ('low'::character varying)::text])) AND (confidence_weight >= (0.0)::double precision) AND (confidence_weight <= (1.0)::double precision))),
    CONSTRAINT ck_expert_label_envelope CHECK (agri.expert_label_envelope_valid(condition_envelope)),
    CONSTRAINT ck_expert_label_kind CHECK (((label_kind)::text = ANY (ARRAY[('species_fit'::character varying)::text, ('strategy_outcome'::character varying)::text]))),
    CONSTRAINT ck_expert_label_outcome_matches_kind CHECK (((((label_kind)::text = 'species_fit'::text) AND ((outcome)::text = ANY (ARRAY[('fit'::character varying)::text, ('marginal'::character varying)::text, ('unfit'::character varying)::text]))) OR (((label_kind)::text = 'strategy_outcome'::text) AND ((outcome)::text = ANY (ARRAY[('effective'::character varying)::text, ('mixed'::character varying)::text, ('ineffective'::character varying)::text]))))),
    CONSTRAINT ck_expert_label_quote_bounded CHECK (((supporting_quote IS NULL) OR ((char_length(supporting_quote) >= 1) AND (char_length(supporting_quote) <= 1000)))),
    CONSTRAINT ck_expert_label_review_evidence CHECK ((((review_state)::text = 'draft'::text) OR ((reviewed_at IS NOT NULL) AND (reviewed_by IS NOT NULL)))),
    CONSTRAINT ck_expert_label_review_state CHECK (((review_state)::text = ANY (ARRAY[('draft'::character varying)::text, ('agent_reviewed'::character varying)::text, ('approved'::character varying)::text, ('rejected'::character varying)::text])))
);

-- CONSTRAINT: expert_label pk_expert_label
ALTER TABLE ONLY agri.expert_label
    ADD CONSTRAINT pk_expert_label PRIMARY KEY (id);

-- CONSTRAINT: expert_label uq_expert_label_key
ALTER TABLE ONLY agri.expert_label
    ADD CONSTRAINT uq_expert_label_key UNIQUE (label_key);

-- INDEX: ix_expert_label_release_state
CREATE INDEX ix_expert_label_release_state ON agri.expert_label USING btree (release_id, review_state);

-- INDEX: ix_expert_label_trainable
CREATE INDEX ix_expert_label_trainable ON agri.expert_label USING btree (review_state, label_kind, subject_normalized);
