-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_iteration_actual_input (
    actual_id uuid NOT NULL,
    source_release_id uuid NOT NULL,
    observation_checksum character varying(64) NOT NULL,
    license_snapshot text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_iteration_actual_input_checksum CHECK ((((observation_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND (btrim(license_snapshot) <> ''::text)))
);

-- CONSTRAINT: forecast_iteration_actual_input forecast_iteration_actual_input_pkey
ALTER TABLE ONLY agri.forecast_iteration_actual_input
    ADD CONSTRAINT forecast_iteration_actual_input_pkey PRIMARY KEY (actual_id, source_release_id, observation_checksum);
