-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_iteration_actual (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    iteration_value_id bigint NOT NULL,
    actual_release_set_id uuid NOT NULL,
    actual_input_release_checksum character varying(64) NOT NULL,
    actual_value double precision NOT NULL,
    source_sample_count integer NOT NULL,
    data_available_at timestamp with time zone NOT NULL,
    actual_digest_version character varying(40) DEFAULT 'forecast_iteration_actual_v2'::character varying NOT NULL,
    actual_checksum character varying(64) NOT NULL,
    recorded_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_iteration_actual_availability CHECK ((recorded_at >= data_available_at)),
    CONSTRAINT ck_forecast_iteration_actual_checksum CHECK ((((actual_input_release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((actual_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_forecast_iteration_actual_digest_version CHECK (((actual_digest_version)::text = 'forecast_iteration_actual_v2'::text)),
    CONSTRAINT ck_forecast_iteration_actual_finite CHECK (((actual_value)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))),
    CONSTRAINT ck_forecast_iteration_actual_samples CHECK ((source_sample_count > 0))
);

-- CONSTRAINT: forecast_iteration_actual forecast_iteration_actual_iteration_value_id_key
ALTER TABLE ONLY agri.forecast_iteration_actual
    ADD CONSTRAINT forecast_iteration_actual_iteration_value_id_key UNIQUE (iteration_value_id);

-- CONSTRAINT: forecast_iteration_actual forecast_iteration_actual_pkey
ALTER TABLE ONLY agri.forecast_iteration_actual
    ADD CONSTRAINT forecast_iteration_actual_pkey PRIMARY KEY (id);
