-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    run_key character varying(255) NOT NULL,
    job_run_id uuid NOT NULL,
    feature_snapshot_id uuid NOT NULL,
    model_id uuid NOT NULL,
    training_run_id uuid,
    quality_policy_id uuid NOT NULL,
    forecast_method character varying(24) NOT NULL,
    issue_time timestamp with time zone NOT NULL,
    valid_from timestamp with time zone NOT NULL,
    valid_to timestamp with time zone NOT NULL,
    horizon_steps integer NOT NULL,
    step_interval interval NOT NULL,
    input_release_checksum character varying(64) NOT NULL,
    feature_checksum character varying(64) NOT NULL,
    model_checksum character varying(64) NOT NULL,
    parameter_checksum character varying(64) NOT NULL,
    status character varying(24) DEFAULT 'staged'::character varying NOT NULL,
    backtest_passed boolean DEFAULT false NOT NULL,
    quality_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    validated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_run_checksums CHECK ((((input_release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((feature_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((model_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((parameter_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_forecast_run_method CHECK (((forecast_method)::text = ANY ((ARRAY['sql_linear'::character varying, 'ml'::character varying])::text[]))),
    CONSTRAINT ck_forecast_run_model_binding CHECK (((((forecast_method)::text = 'sql_linear'::text) AND (training_run_id IS NULL)) OR (((forecast_method)::text = 'ml'::text) AND (training_run_id IS NOT NULL)))),
    CONSTRAINT ck_forecast_run_ordered_window CHECK ((valid_to > valid_from)),
    CONSTRAINT ck_forecast_run_positive_horizon CHECK (((horizon_steps > 0) AND (step_interval > '00:00:00'::interval))),
    CONSTRAINT ck_forecast_run_status CHECK (((status)::text = ANY ((ARRAY['staged'::character varying, 'validated'::character varying, 'rejected'::character varying])::text[])))
);

-- CONSTRAINT: forecast_run forecast_run_pkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_run forecast_run_run_key_key
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_run_key_key UNIQUE (run_key);

-- INDEX: ix_forecast_run_issue_time
CREATE INDEX ix_forecast_run_issue_time ON agri.forecast_run USING btree (issue_time DESC);
