-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_backtest_metric (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    forecast_run_id uuid NOT NULL,
    job_output_id uuid NOT NULL,
    series_id uuid NOT NULL,
    cutoff_time timestamp with time zone NOT NULL,
    training_point_count integer NOT NULL,
    backtest_point_count integer NOT NULL,
    mae double precision NOT NULL,
    rmse double precision NOT NULL,
    naive_rmse double precision,
    skill_score double precision,
    bias double precision NOT NULL,
    mape double precision,
    coverage_fraction double precision NOT NULL,
    metrics_checksum character varying(64) NOT NULL,
    passed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_backtest_checksum_sha256 CHECK (((metrics_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_forecast_backtest_counts CHECK (((training_point_count >= 3) AND (backtest_point_count > 0))),
    CONSTRAINT ck_forecast_backtest_coverage CHECK (((coverage_fraction >= (0)::double precision) AND (coverage_fraction <= (1)::double precision))),
    CONSTRAINT ck_forecast_backtest_nonnegative_metrics CHECK (((mae >= (0)::double precision) AND (rmse >= (0)::double precision) AND ((naive_rmse IS NULL) OR (naive_rmse >= (0)::double precision)) AND ((skill_score IS NULL) OR (skill_score <= (1)::double precision)) AND ((mape IS NULL) OR (mape >= (0)::double precision)) AND ((mae)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND ((rmse)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND ((bias)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))))
);

-- CONSTRAINT: forecast_backtest_metric forecast_backtest_metric_pkey
ALTER TABLE ONLY agri.forecast_backtest_metric
    ADD CONSTRAINT forecast_backtest_metric_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_backtest_metric uq_forecast_backtest_run_series_cutoff
ALTER TABLE ONLY agri.forecast_backtest_metric
    ADD CONSTRAINT uq_forecast_backtest_run_series_cutoff UNIQUE (forecast_run_id, series_id, cutoff_time);
