-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_entity_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    series_id uuid NOT NULL,
    source_release_id uuid NOT NULL,
    state_key character varying(255) NOT NULL,
    valid_from timestamp with time zone NOT NULL,
    valid_to timestamp with time zone,
    data_available_at timestamp with time zone NOT NULL,
    state_checksum character varying(64) NOT NULL,
    state_geometry public.geometry(Geometry,4326),
    state_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_entity_state_checksum_sha256 CHECK (((state_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_forecast_entity_state_ordered_window CHECK (((valid_to IS NULL) OR (valid_to > valid_from)))
);

-- CONSTRAINT: forecast_entity_state forecast_entity_state_pkey
ALTER TABLE ONLY agri.forecast_entity_state
    ADD CONSTRAINT forecast_entity_state_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_entity_state uq_forecast_entity_state_identity
ALTER TABLE ONLY agri.forecast_entity_state
    ADD CONSTRAINT uq_forecast_entity_state_identity UNIQUE (series_id, state_key, state_checksum);

-- INDEX: ix_forecast_entity_state_geometry
CREATE INDEX ix_forecast_entity_state_geometry ON agri.forecast_entity_state USING gist (state_geometry) WHERE (state_geometry IS NOT NULL);

-- INDEX: ix_forecast_entity_state_series_window
CREATE INDEX ix_forecast_entity_state_series_window ON agri.forecast_entity_state USING btree (series_id, valid_from, valid_to);
