-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_receipt (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    forecast_run_id uuid NOT NULL,
    job_output_id uuid NOT NULL,
    series_id uuid NOT NULL,
    entity_state_id uuid,
    issue_time timestamp with time zone NOT NULL,
    valid_from timestamp with time zone NOT NULL,
    valid_to timestamp with time zone NOT NULL,
    expected_value_count integer NOT NULL,
    quantile_levels double precision[] NOT NULL,
    receipt_checksum character varying(64),
    status character varying(24) DEFAULT 'staging'::character varying NOT NULL,
    quality_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    finalized_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_receipt_expected_values CHECK ((expected_value_count > 0)),
    CONSTRAINT ck_forecast_receipt_finalized_evidence CHECK ((((status)::text <> 'finalized'::text) OR ((receipt_checksum IS NOT NULL) AND ((receipt_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND (finalized_at IS NOT NULL)))),
    CONSTRAINT ck_forecast_receipt_ordered_window CHECK ((valid_to > valid_from)),
    CONSTRAINT ck_forecast_receipt_quantiles CHECK ((agri.forecast_quantiles_valid(quantile_levels) AND ((0.5)::double precision = ANY (quantile_levels)))),
    CONSTRAINT ck_forecast_receipt_status CHECK (((status)::text = ANY ((ARRAY['staging'::character varying, 'finalized'::character varying])::text[])))
);

-- CONSTRAINT: forecast_receipt forecast_receipt_pkey
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT forecast_receipt_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_receipt uq_forecast_receipt_run_series_window
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT uq_forecast_receipt_run_series_window UNIQUE (forecast_run_id, series_id, issue_time, valid_from, valid_to);
