-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_publication (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    publication_key character varying(255) NOT NULL,
    job_run_id uuid NOT NULL,
    job_output_id uuid NOT NULL,
    release_set_id uuid NOT NULL,
    scope_key character varying(255) NOT NULL,
    state character varying(24) DEFAULT 'draft'::character varying NOT NULL,
    manifest_checksum character varying(64),
    published_at timestamp with time zone,
    retired_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_publication_published_evidence CHECK ((((state)::text = 'draft'::text) OR (((manifest_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND (published_at IS NOT NULL)))),
    CONSTRAINT ck_forecast_publication_state CHECK (((state)::text = ANY ((ARRAY['draft'::character varying, 'published'::character varying, 'retired'::character varying])::text[])))
);

-- CONSTRAINT: forecast_publication forecast_publication_job_output_id_key
ALTER TABLE ONLY agri.forecast_publication
    ADD CONSTRAINT forecast_publication_job_output_id_key UNIQUE (job_output_id);

-- CONSTRAINT: forecast_publication forecast_publication_pkey
ALTER TABLE ONLY agri.forecast_publication
    ADD CONSTRAINT forecast_publication_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_publication forecast_publication_publication_key_key
ALTER TABLE ONLY agri.forecast_publication
    ADD CONSTRAINT forecast_publication_publication_key_key UNIQUE (publication_key);

-- INDEX: uq_forecast_publication_live_scope
CREATE UNIQUE INDEX uq_forecast_publication_live_scope ON agri.forecast_publication USING btree (scope_key) WHERE ((state)::text = 'published'::text);
