-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_iteration_value (
    id bigint NOT NULL,
    iteration_id uuid NOT NULL,
    valid_time timestamp with time zone NOT NULL,
    horizon_step integer NOT NULL,
    low_value double precision NOT NULL,
    median_value double precision NOT NULL,
    high_value double precision NOT NULL,
    increment_count integer NOT NULL,
    parameter_checksum character varying(64) NOT NULL,
    value_checksum character varying(64),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_iteration_value_finite CHECK ((((low_value)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND ((median_value)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND ((high_value)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])))),
    CONSTRAINT ck_forecast_iteration_value_horizon CHECK ((horizon_step > 0)),
    CONSTRAINT ck_forecast_iteration_value_increment_count CHECK ((increment_count >= 2)),
    CONSTRAINT ck_forecast_iteration_value_ordered CHECK (((low_value <= median_value) AND (median_value <= high_value))),
    CONSTRAINT ck_forecast_iteration_value_parameter_checksum CHECK (((parameter_checksum)::text ~ '^[0-9a-f]{64}$'::text))
);

-- IDENTITY: forecast_iteration_value_id_seq
ALTER TABLE agri.forecast_iteration_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME agri.forecast_iteration_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- CONSTRAINT: forecast_iteration_value forecast_iteration_value_pkey
ALTER TABLE ONLY agri.forecast_iteration_value
    ADD CONSTRAINT forecast_iteration_value_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_iteration_value uq_forecast_iteration_value_horizon
ALTER TABLE ONLY agri.forecast_iteration_value
    ADD CONSTRAINT uq_forecast_iteration_value_horizon UNIQUE (iteration_id, horizon_step);

-- CONSTRAINT: forecast_iteration_value uq_forecast_iteration_value_time
ALTER TABLE ONLY agri.forecast_iteration_value
    ADD CONSTRAINT uq_forecast_iteration_value_time UNIQUE (iteration_id, valid_time);

-- INDEX: ix_forecast_iteration_value_iteration_time
CREATE INDEX ix_forecast_iteration_value_iteration_time ON agri.forecast_iteration_value USING btree (iteration_id, valid_time);
