-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_iteration (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    iteration_key character varying(255) NOT NULL,
    series_id uuid NOT NULL,
    release_set_id uuid NOT NULL,
    purpose character varying(32) DEFAULT 'evaluation_only'::character varying NOT NULL,
    availability_mode character varying(40) NOT NULL,
    method character varying(64) DEFAULT 'daily_increment_bootstrap_v1'::character varying NOT NULL,
    as_of_time timestamp with time zone NOT NULL,
    cutoff_time timestamp with time zone NOT NULL,
    history_start timestamp with time zone NOT NULL,
    horizon_days integer DEFAULT 30 NOT NULL,
    simulation_count integer DEFAULT 1000 NOT NULL,
    simulation_seed bigint DEFAULT 0 NOT NULL,
    grain interval DEFAULT '1 day'::interval NOT NULL,
    gap_policy character varying(24) DEFAULT 'strict'::character varying NOT NULL,
    lower_bound double precision,
    upper_bound double precision,
    input_release_checksum character varying(64) NOT NULL,
    input_license_snapshots jsonb NOT NULL,
    contract_snapshot jsonb NOT NULL,
    contract_checksum character varying(64) NOT NULL,
    history_checksum character varying(64) NOT NULL,
    parameter_checksum character varying(64) NOT NULL,
    training_day_count integer NOT NULL,
    increment_count integer NOT NULL,
    expected_value_count integer NOT NULL,
    receipt_checksum character varying(64),
    status character varying(24) DEFAULT 'staging'::character varying NOT NULL,
    recorded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_iteration_availability CHECK (((availability_mode)::text = ANY ((ARRAY['as_of_pinned_release'::character varying, 'retrospective_pinned_release'::character varying])::text[]))),
    CONSTRAINT ck_forecast_iteration_bounds CHECK ((((lower_bound IS NULL) OR ((lower_bound)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))) AND ((upper_bound IS NULL) OR ((upper_bound)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))) AND ((lower_bound IS NULL) OR (upper_bound IS NULL) OR (lower_bound <= upper_bound)))),
    CONSTRAINT ck_forecast_iteration_checksums CHECK ((((input_release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((contract_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((history_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((parameter_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_forecast_iteration_counts CHECK (((training_day_count >= 3) AND (increment_count >= 2))),
    CONSTRAINT ck_forecast_iteration_finalized_evidence CHECK ((((status)::text <> 'finalized'::text) OR (((receipt_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND (recorded_at IS NOT NULL)))),
    CONSTRAINT ck_forecast_iteration_gap_policy CHECK (((gap_policy)::text = ANY ((ARRAY['strict'::character varying, 'locf'::character varying])::text[]))),
    CONSTRAINT ck_forecast_iteration_horizon CHECK ((((horizon_days >= 1) AND (horizon_days <= 366)) AND (expected_value_count = horizon_days) AND (grain = '1 day'::interval))),
    CONSTRAINT ck_forecast_iteration_method CHECK (((method)::text = 'daily_increment_bootstrap_v1'::text)),
    CONSTRAINT ck_forecast_iteration_ordered_history CHECK (((history_start <= cutoff_time) AND (cutoff_time <= as_of_time))),
    CONSTRAINT ck_forecast_iteration_purpose CHECK (((purpose)::text = 'evaluation_only'::text)),
    CONSTRAINT ck_forecast_iteration_simulations CHECK (((simulation_count >= 100) AND (simulation_count <= 10000))),
    CONSTRAINT ck_forecast_iteration_snapshots CHECK (((jsonb_typeof(input_license_snapshots) = 'array'::text) AND (jsonb_array_length(input_license_snapshots) > 0) AND (jsonb_typeof(contract_snapshot) = 'object'::text))),
    CONSTRAINT ck_forecast_iteration_status CHECK (((status)::text = ANY ((ARRAY['staging'::character varying, 'finalized'::character varying])::text[])))
);

-- CONSTRAINT: forecast_iteration forecast_iteration_iteration_key_key
ALTER TABLE ONLY agri.forecast_iteration
    ADD CONSTRAINT forecast_iteration_iteration_key_key UNIQUE (iteration_key);

-- CONSTRAINT: forecast_iteration forecast_iteration_pkey
ALTER TABLE ONLY agri.forecast_iteration
    ADD CONSTRAINT forecast_iteration_pkey PRIMARY KEY (id);

-- INDEX: ix_forecast_iteration_series_cutoff
CREATE INDEX ix_forecast_iteration_series_cutoff ON agri.forecast_iteration USING btree (series_id, cutoff_time DESC);
