-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_publication_item (
    publication_id uuid NOT NULL,
    forecast_receipt_id uuid NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CONSTRAINT: forecast_publication_item forecast_publication_item_pkey
ALTER TABLE ONLY agri.forecast_publication_item
    ADD CONSTRAINT forecast_publication_item_pkey PRIMARY KEY (publication_id, forecast_receipt_id);
