-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_training_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    training_key character varying(255) NOT NULL,
    model_id uuid NOT NULL,
    job_run_id uuid NOT NULL,
    job_output_id uuid NOT NULL,
    feature_snapshot_id uuid NOT NULL,
    execution_mode character varying(24) DEFAULT 'local'::character varying NOT NULL,
    status character varying(24) DEFAULT 'gated'::character varying NOT NULL,
    input_release_checksum character varying(64) NOT NULL,
    feature_checksum character varying(64) NOT NULL,
    training_code_checksum character varying(64) NOT NULL,
    model_checksum character varying(64),
    validation_checksum character varying(64),
    validation_metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    validated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    strategy_label_release_id uuid,
    strategy_label_checksum character varying(64),
    CONSTRAINT ck_forecast_training_execution_mode CHECK (((execution_mode)::text = 'local'::text)),
    CONSTRAINT ck_forecast_training_input_checksums CHECK ((((input_release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((feature_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((training_code_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_forecast_training_status CHECK (((status)::text = ANY ((ARRAY['gated'::character varying, 'running'::character varying, 'validated'::character varying, 'rejected'::character varying])::text[]))),
    CONSTRAINT ck_forecast_training_strategy_label_binding CHECK ((((strategy_label_release_id IS NULL) AND (strategy_label_checksum IS NULL)) OR ((strategy_label_release_id IS NOT NULL) AND ((strategy_label_checksum)::text ~ '^[0-9a-f]{64}$'::text))))
);

-- CONSTRAINT: forecast_training_run forecast_training_run_pkey
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_training_run forecast_training_run_training_key_key
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_training_key_key UNIQUE (training_key);
