-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_model (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    model_key character varying(255) NOT NULL,
    model_version character varying(100) NOT NULL,
    model_kind character varying(24) NOT NULL,
    model_purpose character varying(32) DEFAULT 'metric_forecast'::character varying NOT NULL,
    algorithm character varying(150) NOT NULL,
    model_code_checksum character varying(64) NOT NULL,
    artifact_id uuid,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_model_code_checksum_sha256 CHECK (((model_code_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_forecast_model_kind CHECK (((model_kind)::text = ANY ((ARRAY['sql_linear'::character varying, 'ml'::character varying, 'ensemble'::character varying])::text[]))),
    CONSTRAINT ck_forecast_model_ml_artifact CHECK ((((model_kind)::text <> 'ml'::text) OR (artifact_id IS NOT NULL))),
    CONSTRAINT ck_forecast_model_purpose CHECK (((model_purpose)::text = ANY ((ARRAY['metric_forecast'::character varying, 'strategy_selection'::character varying])::text[])))
);

-- CONSTRAINT: forecast_model forecast_model_pkey
ALTER TABLE ONLY agri.forecast_model
    ADD CONSTRAINT forecast_model_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_model uq_forecast_model_version
ALTER TABLE ONLY agri.forecast_model
    ADD CONSTRAINT uq_forecast_model_version UNIQUE (model_key, model_version);
