-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_feature_snapshot (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    snapshot_key character varying(255) NOT NULL,
    job_run_id uuid NOT NULL,
    release_set_id uuid NOT NULL,
    input_release_checksum character varying(64) NOT NULL,
    feature_recipe_version character varying(100) NOT NULL,
    feature_code_checksum character varying(64) NOT NULL,
    feature_checksum character varying(64) NOT NULL,
    training_window_start timestamp with time zone NOT NULL,
    training_window_end timestamp with time zone NOT NULL,
    row_count bigint NOT NULL,
    status character varying(24) DEFAULT 'draft'::character varying NOT NULL,
    validation_metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    validated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    job_output_id uuid,
    CONSTRAINT ck_forecast_feature_snapshot_checksums CHECK ((((input_release_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((feature_code_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((feature_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_forecast_feature_snapshot_ordered_window CHECK ((training_window_end >= training_window_start)),
    CONSTRAINT ck_forecast_feature_snapshot_positive_rows CHECK ((row_count > 0)),
    CONSTRAINT ck_forecast_feature_snapshot_status CHECK (((status)::text = ANY (ARRAY[('draft'::character varying)::text, ('validated'::character varying)::text, ('rejected'::character varying)::text]))),
    CONSTRAINT ck_forecast_feature_snapshot_validated_at CHECK ((((status)::text <> 'validated'::text) OR (validated_at IS NOT NULL)))
);

-- CONSTRAINT: forecast_feature_snapshot forecast_feature_snapshot_pkey
ALTER TABLE ONLY agri.forecast_feature_snapshot
    ADD CONSTRAINT forecast_feature_snapshot_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_feature_snapshot forecast_feature_snapshot_snapshot_key_key
ALTER TABLE ONLY agri.forecast_feature_snapshot
    ADD CONSTRAINT forecast_feature_snapshot_snapshot_key_key UNIQUE (snapshot_key);
