-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_quality_policy (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    policy_key character varying(255) NOT NULL,
    min_training_points integer NOT NULL,
    min_backtest_points integer NOT NULL,
    min_coverage_fraction double precision NOT NULL,
    max_mae double precision,
    max_rmse double precision,
    max_mape double precision,
    min_skill_score double precision,
    required_quantiles double precision[] DEFAULT ARRAY[(0.1)::double precision, (0.5)::double precision, (0.9)::double precision] NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_quality_policy_coverage CHECK (((min_coverage_fraction > (0)::double precision) AND (min_coverage_fraction <= (1)::double precision))),
    CONSTRAINT ck_forecast_quality_policy_nonnegative_limits CHECK ((((max_mae IS NULL) OR (max_mae >= (0)::double precision)) AND ((max_rmse IS NULL) OR (max_rmse >= (0)::double precision)) AND ((max_mape IS NULL) OR (max_mape >= (0)::double precision)) AND ((min_skill_score IS NULL) OR (min_skill_score <= (1)::double precision)))),
    CONSTRAINT ck_forecast_quality_policy_positive_counts CHECK (((min_training_points >= 3) AND (min_backtest_points > 0))),
    CONSTRAINT ck_forecast_quality_policy_quantiles CHECK ((agri.forecast_quantiles_valid(required_quantiles) AND ((0.5)::double precision = ANY (required_quantiles))))
);

-- CONSTRAINT: forecast_quality_policy forecast_quality_policy_pkey
ALTER TABLE ONLY agri.forecast_quality_policy
    ADD CONSTRAINT forecast_quality_policy_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_quality_policy forecast_quality_policy_policy_key_key
ALTER TABLE ONLY agri.forecast_quality_policy
    ADD CONSTRAINT forecast_quality_policy_policy_key_key UNIQUE (policy_key);
