-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.forecast_series (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    series_key character varying(255) NOT NULL,
    source_variant_key character varying(255) NOT NULL,
    input_adapter character varying(32) NOT NULL,
    data_source_id uuid NOT NULL,
    signal_name character varying(150),
    source_parameter character varying(150),
    support_key character varying(150),
    source_transform_version character varying(100) NOT NULL,
    entity_type character varying(100) NOT NULL,
    entity_key character varying(255) NOT NULL,
    metric_name character varying(150) NOT NULL,
    metric_unit character varying(64) NOT NULL,
    spatial_cell_id uuid,
    representation_kind character varying(24) NOT NULL,
    spatial_support_kind character varying(32) NOT NULL,
    source_spatial_resolution_m integer,
    output_spatial_resolution_m integer,
    source_temporal_support interval NOT NULL,
    output_temporal_support interval NOT NULL,
    aggregation_method character varying(100),
    allow_ml_daily_aggregate boolean DEFAULT false NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_forecast_series_aggregate_method CHECK (((((representation_kind)::text = 'raw_native'::text) AND (aggregation_method IS NULL)) OR (((representation_kind)::text = ANY (ARRAY[('resampled'::character varying)::text, ('aggregate'::character varying)::text])) AND (aggregation_method IS NOT NULL)))),
    CONSTRAINT ck_forecast_series_input_adapter CHECK (((input_adapter)::text = ANY (ARRAY[('signal_observation'::character varying)::text, ('forecast_observation'::character varying)::text]))),
    CONSTRAINT ck_forecast_series_positive_resolutions CHECK ((((source_spatial_resolution_m IS NULL) OR (source_spatial_resolution_m > 0)) AND ((output_spatial_resolution_m IS NULL) OR (output_spatial_resolution_m > 0)))),
    CONSTRAINT ck_forecast_series_positive_temporal_support CHECK (((source_temporal_support > '00:00:00'::interval) AND (output_temporal_support > '00:00:00'::interval))),
    CONSTRAINT ck_forecast_series_representation_kind CHECK (((representation_kind)::text = ANY (ARRAY[('raw_native'::character varying)::text, ('resampled'::character varying)::text, ('aggregate'::character varying)::text]))),
    CONSTRAINT ck_forecast_series_signal_adapter_identity CHECK ((((input_adapter)::text <> 'signal_observation'::text) OR ((signal_name IS NOT NULL) AND (source_parameter IS NOT NULL) AND (support_key IS NOT NULL) AND (spatial_cell_id IS NOT NULL)))),
    CONSTRAINT ck_forecast_series_spatial_support_kind CHECK (((spatial_support_kind)::text = ANY (ARRAY[('native_grid_cell'::character varying)::text, ('native_polygon'::character varying)::text, ('point_sample'::character varying)::text, ('area_aggregate'::character varying)::text, ('unknown'::character varying)::text])))
);

-- CONSTRAINT: forecast_series forecast_series_pkey
ALTER TABLE ONLY agri.forecast_series
    ADD CONSTRAINT forecast_series_pkey PRIMARY KEY (id);

-- CONSTRAINT: forecast_series forecast_series_series_key_key
ALTER TABLE ONLY agri.forecast_series
    ADD CONSTRAINT forecast_series_series_key_key UNIQUE (series_key);

-- INDEX: ix_forecast_series_entity_metric
CREATE INDEX ix_forecast_series_entity_metric ON agri.forecast_series USING btree (entity_type, entity_key, metric_name);

-- INDEX: ix_forecast_series_spatial_cell
CREATE INDEX ix_forecast_series_spatial_cell ON agri.forecast_series USING btree (spatial_cell_id) WHERE (spatial_cell_id IS NOT NULL);

-- INDEX: uq_forecast_series_exact_source_identity
CREATE UNIQUE INDEX uq_forecast_series_exact_source_identity ON agri.forecast_series USING btree (data_source_id, source_transform_version, input_adapter, signal_name, source_parameter, support_key, spatial_cell_id, entity_type, entity_key, metric_name, metric_unit, representation_kind, spatial_support_kind, source_temporal_support, output_temporal_support) NULLS NOT DISTINCT;
