-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.historical_promotion_source_release_receipt (
    bundle_id uuid NOT NULL,
    source_release_id uuid NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CONSTRAINT: historical_promotion_source_release_receipt pk_historical_promotion_source_release_receipt
ALTER TABLE ONLY agri.historical_promotion_source_release_receipt
    ADD CONSTRAINT pk_historical_promotion_source_release_receipt PRIMARY KEY (bundle_id, source_release_id);
