-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.historical_promotion_artifact_receipt (
    id uuid NOT NULL,
    bundle_id uuid NOT NULL,
    source_release_id uuid NOT NULL,
    uri character varying(2000) NOT NULL,
    media_type character varying(255),
    checksum_sha256 character varying(64) NOT NULL,
    size_bytes integer NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    artifact_id uuid,
    uploaded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_historical_promotion_artifact_receipt_historical_art_c9fc CHECK (((checksum_sha256)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_historical_promotion_artifact_receipt_historical_art_e7b1 CHECK ((size_bytes > 0))
);

-- CONSTRAINT: historical_promotion_artifact_receipt pk_historical_promotion_artifact_receipt
ALTER TABLE ONLY agri.historical_promotion_artifact_receipt
    ADD CONSTRAINT pk_historical_promotion_artifact_receipt PRIMARY KEY (id);

-- CONSTRAINT: historical_promotion_artifact_receipt uq_historical_artifact_receipt_bundle_release
ALTER TABLE ONLY agri.historical_promotion_artifact_receipt
    ADD CONSTRAINT uq_historical_artifact_receipt_bundle_release UNIQUE (bundle_id, source_release_id);

-- INDEX: ix_historical_artifact_receipt_bundle_pending
CREATE INDEX ix_historical_artifact_receipt_bundle_pending ON agri.historical_promotion_artifact_receipt USING btree (bundle_id, uploaded_at);
