-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.historical_promotion_bundle (
    id uuid NOT NULL,
    manifest_checksum character varying(64) NOT NULL,
    manifest_json jsonb NOT NULL,
    release_set_id uuid NOT NULL,
    state character varying(32) DEFAULT 'receiving'::character varying NOT NULL,
    expected_chunk_count integer NOT NULL,
    expected_record_count integer NOT NULL,
    received_by character varying(255) NOT NULL,
    finalized_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_historical_promotion_bundle_historical_promotion_known_state CHECK (((state)::text = ANY ((ARRAY['receiving'::character varying, 'finalized'::character varying])::text[]))),
    CONSTRAINT ck_historical_promotion_bundle_historical_promotion_man_9177 CHECK (((manifest_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_historical_promotion_bundle_historical_promotion_pos_85d2 CHECK ((expected_chunk_count > 0)),
    CONSTRAINT ck_historical_promotion_bundle_historical_promotion_pos_8a9c CHECK ((expected_record_count > 0))
);

-- CONSTRAINT: historical_promotion_bundle pk_historical_promotion_bundle
ALTER TABLE ONLY agri.historical_promotion_bundle
    ADD CONSTRAINT pk_historical_promotion_bundle PRIMARY KEY (id);

-- CONSTRAINT: historical_promotion_bundle uq_historical_promotion_bundle_manifest_checksum
ALTER TABLE ONLY agri.historical_promotion_bundle
    ADD CONSTRAINT uq_historical_promotion_bundle_manifest_checksum UNIQUE (manifest_checksum);

-- CONSTRAINT: historical_promotion_bundle uq_historical_promotion_bundle_release_set_id
ALTER TABLE ONLY agri.historical_promotion_bundle
    ADD CONSTRAINT uq_historical_promotion_bundle_release_set_id UNIQUE (release_set_id);
