-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.historical_promotion_chunk_receipt (
    bundle_id uuid NOT NULL,
    sequence integer NOT NULL,
    payload_sha256 character varying(64) NOT NULL,
    payload_bytes integer NOT NULL,
    record_count integer NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_historical_promotion_chunk_receipt_historical_chunk__322d CHECK (((payload_sha256)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_historical_promotion_chunk_receipt_historical_chunk__5c1b CHECK ((sequence > 0)),
    CONSTRAINT ck_historical_promotion_chunk_receipt_historical_chunk__8c4f CHECK ((payload_bytes > 0)),
    CONSTRAINT ck_historical_promotion_chunk_receipt_historical_chunk__d892 CHECK ((record_count > 0))
);

-- CONSTRAINT: historical_promotion_chunk_receipt pk_historical_promotion_chunk_receipt
ALTER TABLE ONLY agri.historical_promotion_chunk_receipt
    ADD CONSTRAINT pk_historical_promotion_chunk_receipt PRIMARY KEY (bundle_id, sequence);
