-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.intervention_evidence_lineage (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    evidence_input_id uuid NOT NULL,
    source_release_id uuid NOT NULL,
    source_feature_id uuid,
    source_record_table character varying(64),
    source_record_key character varying(255),
    source_record_checksum character varying(64),
    lineage_role character varying(32) NOT NULL,
    input_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_intervention_evidence_lineage_feature_or_record_locator CHECK ((((source_feature_id IS NOT NULL) AND (source_record_table IS NULL) AND (source_record_key IS NULL) AND (source_record_checksum IS NULL)) OR ((source_feature_id IS NULL) AND (source_record_table IS NOT NULL) AND (source_record_key IS NOT NULL) AND (source_record_checksum IS NOT NULL)))),
    CONSTRAINT ck_intervention_evidence_lineage_known_lineage_role CHECK (((lineage_role)::text = ANY ((ARRAY['direct_observation'::character varying, 'derivation_input'::character varying, 'coverage_basis'::character varying, 'gap_basis'::character varying])::text[]))),
    CONSTRAINT ck_intervention_evidence_lineage_known_source_record_table CHECK (((source_record_table IS NULL) OR ((source_record_table)::text = ANY ((ARRAY['signal_observation'::character varying, 'drought_polygon_snapshot'::character varying, 'signal_coverage_audit'::character varying, 'source_coverage_audit'::character varying])::text[])))),
    CONSTRAINT ck_intervention_evidence_lineage_nonnegative_input_order CHECK ((input_order >= 0)),
    CONSTRAINT ck_intervention_evidence_lineage_source_record_checksum_sha256 CHECK (((source_record_checksum IS NULL) OR ((source_record_checksum)::text ~ '^[0-9a-f]{64}$'::text)))
);

-- CONSTRAINT: intervention_evidence_lineage pk_intervention_evidence_lineage
ALTER TABLE ONLY agri.intervention_evidence_lineage
    ADD CONSTRAINT pk_intervention_evidence_lineage PRIMARY KEY (id);

-- CONSTRAINT: intervention_evidence_lineage uq_intervention_evidence_lineage_input_order
ALTER TABLE ONLY agri.intervention_evidence_lineage
    ADD CONSTRAINT uq_intervention_evidence_lineage_input_order UNIQUE (evidence_input_id, input_order);

-- INDEX: ix_intervention_evidence_lineage_source_release
CREATE INDEX ix_intervention_evidence_lineage_source_release ON agri.intervention_evidence_lineage USING btree (source_release_id, evidence_input_id);
