-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.intervention_evidence_input (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    release_set_id uuid NOT NULL,
    analysis_subject_id uuid NOT NULL,
    evidence_kind character varying(32) NOT NULL,
    metric_name character varying(150) NOT NULL,
    numeric_value double precision,
    text_value text,
    boolean_value boolean,
    value_unit character varying(64),
    gap_detail text,
    evidence_geometry public.geometry(Geometry,4326) NOT NULL,
    observed_from timestamp with time zone,
    observed_to timestamp with time zone,
    data_available_at timestamp with time zone NOT NULL,
    spatial_support_kind character varying(32) NOT NULL,
    native_resolution_m double precision,
    native_scale character varying(120) NOT NULL,
    maximum_inference_scale character varying(32) NOT NULL,
    confidence double precision,
    confidence_basis character varying(255) NOT NULL,
    method_key character varying(120) NOT NULL,
    method_version character varying(100) NOT NULL,
    intervention_analysis_run_id uuid,
    evidence_checksum character varying(64) NOT NULL,
    is_life_safety_validated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_intervention_evidence_input_derived_feature_has_repr_f42c CHECK (((((evidence_kind)::text = 'model_derived_feature'::text) AND (intervention_analysis_run_id IS NOT NULL)) OR (((evidence_kind)::text <> 'model_derived_feature'::text) AND (intervention_analysis_run_id IS NULL)))),
    CONSTRAINT ck_intervention_evidence_input_evidence_checksum_sha256 CHECK (((evidence_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_intervention_evidence_input_kind_matches_typed_value CHECK (((((evidence_kind)::text = ANY (ARRAY[('observed_fact'::character varying)::text, ('model_derived_feature'::character varying)::text])) AND (num_nonnulls(numeric_value, text_value, boolean_value) = 1) AND (gap_detail IS NULL)) OR (((evidence_kind)::text = 'known_gap'::text) AND (num_nonnulls(numeric_value, text_value, boolean_value) = 0) AND (gap_detail IS NOT NULL)))),
    CONSTRAINT ck_intervention_evidence_input_known_evidence_kind CHECK (((evidence_kind)::text = ANY (ARRAY[('observed_fact'::character varying)::text, ('model_derived_feature'::character varying)::text, ('known_gap'::character varying)::text]))),
    CONSTRAINT ck_intervention_evidence_input_known_geometry_type CHECK ((public.geometrytype(evidence_geometry) = ANY (ARRAY['POINT'::text, 'MULTIPOINT'::text, 'LINESTRING'::text, 'MULTILINESTRING'::text, 'POLYGON'::text, 'MULTIPOLYGON'::text]))),
    CONSTRAINT ck_intervention_evidence_input_known_maximum_inference_scale CHECK (((maximum_inference_scale)::text = ANY (ARRAY[('structure'::character varying)::text, ('parcel'::character varying)::text, ('neighborhood'::character varying)::text, ('city'::character varying)::text, ('landscape'::character varying)::text, ('regional'::character varying)::text]))),
    CONSTRAINT ck_intervention_evidence_input_known_spatial_support_kind CHECK (((spatial_support_kind)::text = ANY (ARRAY[('point_sample'::character varying)::text, ('line_sample'::character varying)::text, ('native_grid_cell'::character varying)::text, ('model_grid_cell'::character varying)::text, ('native_polygon'::character varying)::text, ('area_aggregate'::character varying)::text, ('structure_footprint'::character varying)::text, ('parcel_boundary'::character varying)::text, ('administrative_boundary'::character varying)::text, ('unknown'::character varying)::text]))),
    CONSTRAINT ck_intervention_evidence_input_not_life_safety_validated CHECK ((is_life_safety_validated = false)),
    CONSTRAINT ck_intervention_evidence_input_ordered_observation_window CHECK (((observed_to IS NULL) OR (observed_from IS NULL) OR (observed_to >= observed_from))),
    CONSTRAINT ck_intervention_evidence_input_positive_native_resolution CHECK (((native_resolution_m IS NULL) OR (native_resolution_m > (0)::double precision))),
    CONSTRAINT ck_intervention_evidence_input_valid_confidence CHECK (((confidence IS NULL) OR ((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))),
    CONSTRAINT ck_intervention_evidence_input_valid_wgs84_geometry CHECK (((public.st_srid(evidence_geometry) = 4326) AND (public.st_ndims(evidence_geometry) = 2) AND (NOT public.st_isempty(evidence_geometry)) AND public.st_isvalid(evidence_geometry)))
);

-- CONSTRAINT: intervention_evidence_input pk_intervention_evidence_input
ALTER TABLE ONLY agri.intervention_evidence_input
    ADD CONSTRAINT pk_intervention_evidence_input PRIMARY KEY (id);

-- CONSTRAINT: intervention_evidence_input uq_intervention_evidence_release_subject_checksum
ALTER TABLE ONLY agri.intervention_evidence_input
    ADD CONSTRAINT uq_intervention_evidence_release_subject_checksum UNIQUE (release_set_id, analysis_subject_id, evidence_checksum);

-- INDEX: ix_intervention_evidence_input_geometry
CREATE INDEX ix_intervention_evidence_input_geometry ON agri.intervention_evidence_input USING gist (evidence_geometry);

-- INDEX: ix_intervention_evidence_input_subject_kind
CREATE INDEX ix_intervention_evidence_input_subject_kind ON agri.intervention_evidence_input USING btree (analysis_subject_id, evidence_kind);
