-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_dependency (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_run_id uuid NOT NULL,
    depends_on_run_id uuid NOT NULL,
    required_status character varying(32) DEFAULT 'succeeded'::character varying NOT NULL,
    satisfied_at timestamp with time zone,
    CONSTRAINT ck_job_dependency_dependency_not_self CHECK ((job_run_id <> depends_on_run_id)),
    CONSTRAINT ck_job_dependency_dependency_required_status CHECK (((required_status)::text = ANY (ARRAY[('succeeded'::character varying)::text, ('partial'::character varying)::text])))
);

-- CONSTRAINT: job_dependency pk_job_dependency
ALTER TABLE ONLY agri.job_dependency
    ADD CONSTRAINT pk_job_dependency PRIMARY KEY (id);

-- CONSTRAINT: job_dependency uq_job_dependency_edge
ALTER TABLE ONLY agri.job_dependency
    ADD CONSTRAINT uq_job_dependency_edge UNIQUE (job_run_id, depends_on_run_id);
