-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_attempt (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_work_item_id uuid NOT NULL,
    attempt_number integer NOT NULL,
    fencing_token bigint NOT NULL,
    status character varying(9) DEFAULT 'running'::character varying NOT NULL,
    worker_id character varying(255) NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    heartbeat_at timestamp with time zone,
    finished_at timestamp with time zone,
    failure_class character varying(255),
    error_summary text,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_job_attempt_attempt_state CHECK (((status)::text = ANY ((ARRAY['running'::character varying, 'succeeded'::character varying, 'failed'::character varying, 'lost'::character varying, 'deferred'::character varying, 'cancelled'::character varying])::text[]))),
    CONSTRAINT ck_job_attempt_positive_attempt_fencing_token CHECK ((fencing_token > 0)),
    CONSTRAINT ck_job_attempt_positive_attempt_number CHECK ((attempt_number > 0)),
    CONSTRAINT ck_job_attempt_terminal_attempt_has_finish_time CHECK ((((status)::text = 'running'::text) OR (finished_at IS NOT NULL)))
);

-- CONSTRAINT: job_attempt pk_job_attempt
ALTER TABLE ONLY agri.job_attempt
    ADD CONSTRAINT pk_job_attempt PRIMARY KEY (id);

-- CONSTRAINT: job_attempt uq_job_attempt_checkpoint_fence
ALTER TABLE ONLY agri.job_attempt
    ADD CONSTRAINT uq_job_attempt_checkpoint_fence UNIQUE (id, job_work_item_id, fencing_token);

-- CONSTRAINT: job_attempt uq_job_attempt_item_fence
ALTER TABLE ONLY agri.job_attempt
    ADD CONSTRAINT uq_job_attempt_item_fence UNIQUE (job_work_item_id, fencing_token);

-- CONSTRAINT: job_attempt uq_job_attempt_item_number
ALTER TABLE ONLY agri.job_attempt
    ADD CONSTRAINT uq_job_attempt_item_number UNIQUE (job_work_item_id, attempt_number);
