-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_outbox (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_key character varying(255) NOT NULL,
    aggregate_type character varying(100) NOT NULL,
    aggregate_id uuid NOT NULL,
    topic character varying(255) NOT NULL,
    payload jsonb NOT NULL,
    status character varying(11) DEFAULT 'pending'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 10 NOT NULL,
    next_attempt_at timestamp with time zone DEFAULT now() NOT NULL,
    fencing_token bigint DEFAULT '0'::bigint NOT NULL,
    lease_owner character varying(255),
    lease_expires_at timestamp with time zone,
    delivered_at timestamp with time zone,
    last_error_summary text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_job_outbox_complete_outbox_lease_pair CHECK ((((lease_owner IS NULL) AND (lease_expires_at IS NULL)) OR ((lease_owner IS NOT NULL) AND (lease_expires_at IS NOT NULL)))),
    CONSTRAINT ck_job_outbox_delivered_outbox_has_timestamp CHECK ((((status)::text <> 'delivered'::text) OR (delivered_at IS NOT NULL))),
    CONSTRAINT ck_job_outbox_nonnegative_outbox_attempt_count CHECK ((attempt_count >= 0)),
    CONSTRAINT ck_job_outbox_nonnegative_outbox_fencing_token CHECK ((fencing_token >= 0)),
    CONSTRAINT ck_job_outbox_outbox_attempt_count_within_limit CHECK ((attempt_count <= max_attempts)),
    CONSTRAINT ck_job_outbox_outbox_state CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'publishing'::character varying, 'retry_wait'::character varying, 'delivered'::character varying, 'dead_letter'::character varying])::text[]))),
    CONSTRAINT ck_job_outbox_positive_outbox_max_attempts CHECK ((max_attempts > 0)),
    CONSTRAINT ck_job_outbox_publishing_outbox_has_fenced_lease CHECK ((((status)::text <> 'publishing'::text) OR ((lease_owner IS NOT NULL) AND (lease_expires_at IS NOT NULL) AND (fencing_token > 0))))
);

-- CONSTRAINT: job_outbox pk_job_outbox
ALTER TABLE ONLY agri.job_outbox
    ADD CONSTRAINT pk_job_outbox PRIMARY KEY (id);

-- CONSTRAINT: job_outbox uq_job_outbox_event_key
ALTER TABLE ONLY agri.job_outbox
    ADD CONSTRAINT uq_job_outbox_event_key UNIQUE (event_key);

-- INDEX: ix_job_outbox_dispatch
CREATE INDEX ix_job_outbox_dispatch ON agri.job_outbox USING btree (status, next_attempt_at);
