-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    job_run_id uuid,
    job_work_item_id uuid,
    job_attempt_id uuid,
    severity character varying(8) NOT NULL,
    event_code character varying(150) NOT NULL,
    environment character varying(100) NOT NULL,
    service character varying(100) NOT NULL,
    trace_id character varying(255),
    duration_ms bigint,
    progress jsonb DEFAULT '{}'::jsonb NOT NULL,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_job_event_event_severity CHECK (((severity)::text = ANY (ARRAY[('debug'::character varying)::text, ('info'::character varying)::text, ('warning'::character varying)::text, ('error'::character varying)::text, ('critical'::character varying)::text]))),
    CONSTRAINT ck_job_event_nonnegative_event_duration CHECK (((duration_ms IS NULL) OR (duration_ms >= 0)))
)
PARTITION BY RANGE (occurred_at);

-- CONSTRAINT: job_event pk_job_event
ALTER TABLE ONLY agri.job_event
    ADD CONSTRAINT pk_job_event PRIMARY KEY (id, occurred_at);

-- INDEX: ix_job_event_run_occurred
CREATE INDEX ix_job_event_run_occurred ON ONLY agri.job_event USING btree (job_run_id, occurred_at);

-- INDEX: ix_job_event_severity_occurred
CREATE INDEX ix_job_event_severity_occurred ON ONLY agri.job_event USING btree (severity, occurred_at);
