-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_definition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(150) NOT NULL,
    version character varying(100) NOT NULL,
    handler character varying(500) NOT NULL,
    queue_name character varying(100) DEFAULT 'default'::character varying NOT NULL,
    schedule character varying(255),
    schedule_timezone character varying(100) DEFAULT 'UTC'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    concurrency_key character varying(255),
    max_attempts integer DEFAULT 5 NOT NULL,
    lease_seconds integer DEFAULT 300 NOT NULL,
    time_budget_seconds integer DEFAULT 240 NOT NULL,
    retry_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_job_definition_positive_lease_seconds CHECK ((lease_seconds > 0)),
    CONSTRAINT ck_job_definition_positive_max_attempts CHECK ((max_attempts > 0)),
    CONSTRAINT ck_job_definition_positive_time_budget_seconds CHECK ((time_budget_seconds > 0))
);

-- CONSTRAINT: job_definition pk_job_definition
ALTER TABLE ONLY agri.job_definition
    ADD CONSTRAINT pk_job_definition PRIMARY KEY (id);

-- CONSTRAINT: job_definition uq_job_definition_name_version
ALTER TABLE ONLY agri.job_definition
    ADD CONSTRAINT uq_job_definition_name_version UNIQUE (name, version);
