-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fingerprint character varying(255) NOT NULL,
    incident_type character varying(150) NOT NULL,
    severity character varying(8) NOT NULL,
    status character varying(12) DEFAULT 'open'::character varying NOT NULL,
    job_run_id uuid,
    job_work_item_id uuid,
    summary text NOT NULL,
    occurrence_count integer DEFAULT 1 NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    cooldown_until timestamp with time zone,
    owner character varying(255),
    acknowledged_at timestamp with time zone,
    acknowledged_by character varying(255),
    resolved_at timestamp with time zone,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_job_incident_acknowledged_incident_has_timestamp CHECK ((((status)::text <> 'acknowledged'::text) OR (acknowledged_at IS NOT NULL))),
    CONSTRAINT ck_job_incident_incident_severity CHECK (((severity)::text = ANY (ARRAY[('debug'::character varying)::text, ('info'::character varying)::text, ('warning'::character varying)::text, ('error'::character varying)::text, ('critical'::character varying)::text]))),
    CONSTRAINT ck_job_incident_incident_state CHECK (((status)::text = ANY (ARRAY[('open'::character varying)::text, ('acknowledged'::character varying)::text, ('resolved'::character varying)::text]))),
    CONSTRAINT ck_job_incident_ordered_incident_seen_window CHECK ((last_seen_at >= first_seen_at)),
    CONSTRAINT ck_job_incident_positive_incident_occurrence_count CHECK ((occurrence_count > 0)),
    CONSTRAINT ck_job_incident_resolved_incident_has_timestamp CHECK ((((status)::text <> 'resolved'::text) OR (resolved_at IS NOT NULL)))
);

-- CONSTRAINT: job_incident pk_job_incident
ALTER TABLE ONLY agri.job_incident
    ADD CONSTRAINT pk_job_incident PRIMARY KEY (id);

-- CONSTRAINT: job_incident uq_job_incident_fingerprint
ALTER TABLE ONLY agri.job_incident
    ADD CONSTRAINT uq_job_incident_fingerprint UNIQUE (fingerprint);

-- INDEX: ix_job_incident_status_severity
CREATE INDEX ix_job_incident_status_severity ON agri.job_incident USING btree (status, severity);
