-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.job_output (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_run_id uuid NOT NULL,
    job_work_item_id uuid,
    job_attempt_id uuid,
    fencing_token bigint,
    artifact_id uuid,
    output_key character varying(500) NOT NULL,
    kind character varying(100) NOT NULL,
    state character varying(10) DEFAULT 'staged'::character varying NOT NULL,
    uri character varying(2000),
    checksum_sha256 character varying(64) NOT NULL,
    row_count bigint,
    size_bytes bigint,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    validated_at timestamp with time zone,
    CONSTRAINT ck_job_output_nonnegative_output_rows CHECK (((row_count IS NULL) OR (row_count >= 0))),
    CONSTRAINT ck_job_output_nonnegative_output_size CHECK (((size_bytes IS NULL) OR (size_bytes >= 0))),
    CONSTRAINT ck_job_output_output_state CHECK (((state)::text = ANY (ARRAY[('staged'::character varying)::text, ('validated'::character varying)::text, ('rejected'::character varying)::text, ('published'::character varying)::text, ('superseded'::character varying)::text]))),
    CONSTRAINT ck_job_output_validated_output_has_timestamp CHECK ((((state)::text <> ALL (ARRAY[('validated'::character varying)::text, ('published'::character varying)::text])) OR (validated_at IS NOT NULL))),
    CONSTRAINT ck_job_output_work_output_has_attempt_fence CHECK ((((job_work_item_id IS NULL) AND (job_attempt_id IS NULL) AND (fencing_token IS NULL)) OR ((job_work_item_id IS NOT NULL) AND (job_attempt_id IS NOT NULL) AND (fencing_token IS NOT NULL) AND (fencing_token > 0))))
);

-- CONSTRAINT: job_output pk_job_output
ALTER TABLE ONLY agri.job_output
    ADD CONSTRAINT pk_job_output PRIMARY KEY (id);

-- CONSTRAINT: job_output uq_job_output_run_key
ALTER TABLE ONLY agri.job_output
    ADD CONSTRAINT uq_job_output_run_key UNIQUE (job_run_id, output_key);

-- INDEX: ix_job_output_artifact_id
CREATE INDEX ix_job_output_artifact_id ON agri.job_output USING btree (artifact_id);
