-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.knowledge_chunks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_document character varying(500) NOT NULL,
    title character varying(500) NOT NULL,
    content text NOT NULL,
    chunk_index integer NOT NULL,
    embedding public.vector(1536),
    strategy_id uuid,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CONSTRAINT: knowledge_chunks pk_knowledge_chunks
ALTER TABLE ONLY agri.knowledge_chunks
    ADD CONSTRAINT pk_knowledge_chunks PRIMARY KEY (id);

-- INDEX: ix_knowledge_chunks_embedding
CREATE INDEX ix_knowledge_chunks_embedding ON agri.knowledge_chunks USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');

-- INDEX: ix_knowledge_chunks_strategy_id
CREATE INDEX ix_knowledge_chunks_strategy_id ON agri.knowledge_chunks USING btree (strategy_id);
