-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.land_use_snapshots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id uuid NOT NULL,
    source character varying(4) NOT NULL,
    year integer NOT NULL,
    classification character varying(100),
    crop_history_json jsonb,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_land_use_snapshots_land_use_source CHECK (((source)::text = ANY ((ARRAY['cdl'::character varying, 'nlcd'::character varying])::text[])))
);

-- CONSTRAINT: land_use_snapshots pk_land_use_snapshots
ALTER TABLE ONLY agri.land_use_snapshots
    ADD CONSTRAINT pk_land_use_snapshots PRIMARY KEY (id);

-- INDEX: ix_land_use_snapshots_location_id
CREATE INDEX ix_land_use_snapshots_location_id ON agri.land_use_snapshots USING btree (location_id);
