-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.locations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    geometry public.geometry(Point,4326) NOT NULL,
    bounding_box public.geometry(Polygon,4326),
    usda_zone character varying(10),
    epa_ecoregion character varying(100),
    elevation_m double precision,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CONSTRAINT: locations pk_locations
ALTER TABLE ONLY agri.locations
    ADD CONSTRAINT pk_locations PRIMARY KEY (id);

-- INDEX: ix_locations_bounding_box
CREATE INDEX ix_locations_bounding_box ON agri.locations USING gist (bounding_box);

-- INDEX: ix_locations_geometry
CREATE INDEX ix_locations_geometry ON agri.locations USING gist (geometry);
