-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.normalized_source_feature (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_release_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    feature_key character varying(500) NOT NULL,
    feature_kind character varying(100) NOT NULL,
    geometry public.geometry(Geometry,4326) NOT NULL,
    geometry_checksum character varying(64) NOT NULL,
    observed_from timestamp with time zone,
    observed_to timestamp with time zone,
    data_available_at timestamp with time zone NOT NULL,
    numeric_value double precision,
    text_value text,
    boolean_value boolean,
    value_unit character varying(64),
    attributes_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    spatial_support_kind character varying(32) NOT NULL,
    native_resolution_m double precision,
    native_scale character varying(120) NOT NULL,
    maximum_inference_scale character varying(32) NOT NULL,
    confidence double precision,
    confidence_basis character varying(255) NOT NULL,
    method_key character varying(120) NOT NULL,
    method_version character varying(100) NOT NULL,
    feature_checksum character varying(64) NOT NULL,
    is_life_safety_validated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_normalized_source_feature_feature_checksum_sha256 CHECK (((feature_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_normalized_source_feature_geometry_checksum_sha256 CHECK (((geometry_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_normalized_source_feature_known_geometry_type CHECK ((public.geometrytype(geometry) = ANY (ARRAY['POINT'::text, 'MULTIPOINT'::text, 'LINESTRING'::text, 'MULTILINESTRING'::text, 'POLYGON'::text, 'MULTIPOLYGON'::text]))),
    CONSTRAINT ck_normalized_source_feature_known_maximum_inference_scale CHECK (((maximum_inference_scale)::text = ANY (ARRAY[('structure'::character varying)::text, ('parcel'::character varying)::text, ('neighborhood'::character varying)::text, ('city'::character varying)::text, ('landscape'::character varying)::text, ('regional'::character varying)::text]))),
    CONSTRAINT ck_normalized_source_feature_known_spatial_support_kind CHECK (((spatial_support_kind)::text = ANY (ARRAY[('point_sample'::character varying)::text, ('line_sample'::character varying)::text, ('native_grid_cell'::character varying)::text, ('model_grid_cell'::character varying)::text, ('native_polygon'::character varying)::text, ('area_aggregate'::character varying)::text, ('structure_footprint'::character varying)::text, ('parcel_boundary'::character varying)::text, ('administrative_boundary'::character varying)::text, ('unknown'::character varying)::text]))),
    CONSTRAINT ck_normalized_source_feature_not_life_safety_validated CHECK ((is_life_safety_validated = false)),
    CONSTRAINT ck_normalized_source_feature_ordered_observation_window CHECK (((observed_to IS NULL) OR (observed_from IS NULL) OR (observed_to >= observed_from))),
    CONSTRAINT ck_normalized_source_feature_positive_native_resolution CHECK (((native_resolution_m IS NULL) OR (native_resolution_m > (0)::double precision))),
    CONSTRAINT ck_normalized_source_feature_valid_confidence CHECK (((confidence IS NULL) OR ((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))),
    CONSTRAINT ck_normalized_source_feature_valid_wgs84_geometry CHECK (((public.st_srid(geometry) = 4326) AND (public.st_ndims(geometry) = 2) AND (NOT public.st_isempty(geometry)) AND public.st_isvalid(geometry)))
);

-- CONSTRAINT: normalized_source_feature pk_normalized_source_feature
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT pk_normalized_source_feature PRIMARY KEY (id);

-- CONSTRAINT: normalized_source_feature uq_normalized_source_feature_id_release
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT uq_normalized_source_feature_id_release UNIQUE (id, source_release_id);

-- CONSTRAINT: normalized_source_feature uq_normalized_source_feature_id_release_artifact
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT uq_normalized_source_feature_id_release_artifact UNIQUE (id, source_release_id, artifact_id);

-- CONSTRAINT: normalized_source_feature uq_normalized_source_feature_release_identity
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT uq_normalized_source_feature_release_identity UNIQUE (source_release_id, feature_key, method_key, method_version);

-- INDEX: ix_normalized_source_feature_geometry
CREATE INDEX ix_normalized_source_feature_geometry ON agri.normalized_source_feature USING gist (geometry);

-- INDEX: ix_normalized_source_feature_release_kind
CREATE INDEX ix_normalized_source_feature_release_kind ON agri.normalized_source_feature USING btree (source_release_id, feature_kind);
