-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.recommendation_training_receipt (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    training_key character varying(255) NOT NULL,
    model_name character varying(120) NOT NULL,
    model_kind character varying(32) NOT NULL,
    label_release_id uuid NOT NULL,
    label_review_tier character varying(64) NOT NULL,
    artifact_id uuid,
    job_run_id uuid,
    job_output_id uuid,
    feature_schema_version character varying(64) NOT NULL,
    label_count integer NOT NULL,
    training_instance_count integer NOT NULL,
    source_count integer NOT NULL,
    artifact_checksum character varying(64) NOT NULL,
    evaluation_metrics jsonb NOT NULL,
    evaluation_checksum character varying(64) NOT NULL,
    parameter_checksum character varying(64) NOT NULL,
    training_code_checksum character varying(64) NOT NULL,
    evaluation_only boolean DEFAULT true NOT NULL,
    publication_authorized boolean DEFAULT false NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_recommendation_training_receipt_checksums CHECK ((((artifact_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((evaluation_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((parameter_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND ((training_code_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_recommendation_training_receipt_counts CHECK (((label_count >= 0) AND (training_instance_count >= 0) AND (source_count >= 0))),
    CONSTRAINT ck_recommendation_training_receipt_evaluation_only CHECK (evaluation_only),
    CONSTRAINT ck_recommendation_training_receipt_kind CHECK (((model_kind)::text = ANY (ARRAY[('species_fit'::character varying)::text, ('strategy_selection'::character varying)::text]))),
    CONSTRAINT ck_recommendation_training_receipt_metrics CHECK ((jsonb_typeof(evaluation_metrics) = 'object'::text)),
    CONSTRAINT ck_recommendation_training_receipt_ordered CHECK ((completed_at >= started_at)),
    CONSTRAINT ck_recommendation_training_receipt_review_tier CHECK (((label_review_tier)::text = ANY (ARRAY[('draft'::character varying)::text, ('agent_reviewed_pending_owner_signature'::character varying)::text, ('owner_signed'::character varying)::text]))),
    CONSTRAINT ck_recommendation_training_receipt_unpublishable CHECK ((NOT publication_authorized))
);

-- CONSTRAINT: recommendation_training_receipt pk_recommendation_training_receipt
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT pk_recommendation_training_receipt PRIMARY KEY (id);

-- CONSTRAINT: recommendation_training_receipt uq_recommendation_training_receipt_key
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT uq_recommendation_training_receipt_key UNIQUE (training_key);

-- INDEX: ix_recommendation_training_receipt_model
CREATE INDEX ix_recommendation_training_receipt_model ON agri.recommendation_training_receipt USING btree (model_kind, completed_at DESC);
