-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.release_set (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    logical_key character varying(255) NOT NULL,
    as_of_time timestamp with time zone NOT NULL,
    manifest_checksum character varying(64) NOT NULL,
    state character varying(9) DEFAULT 'draft'::character varying NOT NULL,
    description text,
    validated_at timestamp with time zone,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_release_set_published_set_has_timestamp CHECK ((((state)::text <> 'published'::text) OR (published_at IS NOT NULL))),
    CONSTRAINT ck_release_set_release_set_manifest_checksum_sha256 CHECK (((manifest_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_release_set_release_set_state CHECK (((state)::text = ANY ((ARRAY['draft'::character varying, 'validated'::character varying, 'published'::character varying, 'retired'::character varying])::text[]))),
    CONSTRAINT ck_release_set_validated_set_has_timestamp CHECK ((((state)::text <> ALL ((ARRAY['validated'::character varying, 'published'::character varying])::text[])) OR (validated_at IS NOT NULL)))
);

-- CONSTRAINT: release_set pk_release_set
ALTER TABLE ONLY agri.release_set
    ADD CONSTRAINT pk_release_set PRIMARY KEY (id);

-- CONSTRAINT: release_set uq_release_set_logical_key
ALTER TABLE ONLY agri.release_set
    ADD CONSTRAINT uq_release_set_logical_key UNIQUE (logical_key);

-- CONSTRAINT: release_set uq_release_set_manifest_checksum
ALTER TABLE ONLY agri.release_set
    ADD CONSTRAINT uq_release_set_manifest_checksum UNIQUE (manifest_checksum);
