-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.signal_observation (
    id bigint NOT NULL,
    source_release_id uuid NOT NULL,
    cell_id uuid NOT NULL,
    signal_name character varying(150) NOT NULL,
    source_parameter character varying(150) NOT NULL,
    support_key character varying(150) DEFAULT 'surface'::character varying NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    valid_from timestamp with time zone,
    valid_to timestamp with time zone,
    data_available_at timestamp with time zone NOT NULL,
    original_value double precision,
    original_unit character varying(64),
    normalized_value double precision,
    normalized_unit character varying(64),
    quality_flag character varying(64) DEFAULT 'accepted'::character varying NOT NULL,
    coverage_fraction double precision DEFAULT '1'::double precision NOT NULL,
    is_observed boolean DEFAULT true NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_signal_observation_ordered_valid_window CHECK (((valid_to IS NULL) OR (valid_from IS NULL) OR (valid_to >= valid_from))),
    CONSTRAINT ck_signal_observation_valid_coverage CHECK (((coverage_fraction >= (0)::double precision) AND (coverage_fraction <= (1)::double precision)))
);

-- SEQUENCE OWNED BY: signal_observation_id_seq
ALTER SEQUENCE agri.signal_observation_id_seq OWNED BY agri.signal_observation.id;

-- DEFAULT: signal_observation id
ALTER TABLE ONLY agri.signal_observation ALTER COLUMN id SET DEFAULT nextval('agri.signal_observation_id_seq'::regclass);

-- CONSTRAINT: signal_observation pk_signal_observation
ALTER TABLE ONLY agri.signal_observation
    ADD CONSTRAINT pk_signal_observation PRIMARY KEY (id);

-- CONSTRAINT: signal_observation uq_signal_observation_release_cell_signal_time
ALTER TABLE ONLY agri.signal_observation
    ADD CONSTRAINT uq_signal_observation_release_cell_signal_time UNIQUE (source_release_id, cell_id, signal_name, source_parameter, support_key, observed_at);

-- INDEX: ix_signal_observation_cell_time_signal
CREATE INDEX ix_signal_observation_cell_time_signal ON agri.signal_observation USING btree (cell_id, observed_at, signal_name);

-- INDEX: ix_signal_observation_release_time
CREATE INDEX ix_signal_observation_release_time ON agri.signal_observation USING btree (source_release_id, observed_at);
