-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.signal_coverage_audit (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_release_id uuid NOT NULL,
    cell_id uuid NOT NULL,
    signal_name character varying(150) NOT NULL,
    support_key character varying(150) DEFAULT 'surface'::character varying NOT NULL,
    window_start timestamp with time zone NOT NULL,
    window_end timestamp with time zone NOT NULL,
    expected_observation_count integer NOT NULL,
    received_observation_count integer NOT NULL,
    status character varying(32) NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_parameter character varying(150) NOT NULL,
    CONSTRAINT ck_signal_coverage_known_status CHECK (((status)::text = ANY (ARRAY[('complete'::character varying)::text, ('partial'::character varying)::text, ('no_data'::character varying)::text, ('failed'::character varying)::text]))),
    CONSTRAINT ck_signal_coverage_nonnegative_counts CHECK (((expected_observation_count >= 0) AND (received_observation_count >= 0))),
    CONSTRAINT ck_signal_coverage_ordered_window CHECK ((window_end >= window_start)),
    CONSTRAINT ck_signal_coverage_received_within_expected CHECK ((received_observation_count <= expected_observation_count)),
    CONSTRAINT ck_signal_coverage_status_matches_counts CHECK (((((status)::text = 'complete'::text) AND (received_observation_count = expected_observation_count)) OR (((status)::text = 'partial'::text) AND (received_observation_count > 0) AND (received_observation_count < expected_observation_count)) OR (((status)::text = 'no_data'::text) AND (received_observation_count = 0)) OR (((status)::text = 'failed'::text) AND (received_observation_count < expected_observation_count))))
);

-- CONSTRAINT: signal_coverage_audit pk_signal_coverage_audit
ALTER TABLE ONLY agri.signal_coverage_audit
    ADD CONSTRAINT pk_signal_coverage_audit PRIMARY KEY (id);

-- CONSTRAINT: signal_coverage_audit uq_signal_coverage_release_cell_signal_parameter_window
ALTER TABLE ONLY agri.signal_coverage_audit
    ADD CONSTRAINT uq_signal_coverage_release_cell_signal_parameter_window UNIQUE (source_release_id, cell_id, signal_name, source_parameter, support_key, window_start, window_end);
