-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.soil_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id uuid NOT NULL,
    source character varying(9) NOT NULL,
    soil_type character varying(100),
    texture_class character varying(50),
    ph double precision,
    organic_matter_pct double precision,
    cec double precision,
    bulk_density double precision,
    drainage_class character varying(50),
    depth_cm double precision,
    sand_pct double precision,
    silt_pct double precision,
    clay_pct double precision,
    available_water_capacity double precision,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_soil_profiles_soil_source CHECK (((source)::text = ANY ((ARRAY['ssurgo'::character varying, 'soilgrids'::character varying])::text[])))
);

-- CONSTRAINT: soil_profiles pk_soil_profiles
ALTER TABLE ONLY agri.soil_profiles
    ADD CONSTRAINT pk_soil_profiles PRIMARY KEY (id);

-- INDEX: ix_soil_profiles_location_id
CREATE INDEX ix_soil_profiles_location_id ON agri.soil_profiles USING btree (location_id);
