-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.source_coverage_audit (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_release_id uuid NOT NULL,
    scope_key character varying(180) NOT NULL,
    window_start timestamp with time zone NOT NULL,
    window_end timestamp with time zone NOT NULL,
    expected_feature_count integer NOT NULL,
    received_feature_count integer NOT NULL,
    status character varying(32) NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_source_coverage_known_status CHECK (((status)::text = ANY ((ARRAY['complete'::character varying, 'partial'::character varying, 'no_data'::character varying, 'failed'::character varying])::text[]))),
    CONSTRAINT ck_source_coverage_nonnegative_counts CHECK (((expected_feature_count >= 0) AND (received_feature_count >= 0))),
    CONSTRAINT ck_source_coverage_ordered_window CHECK ((window_end >= window_start)),
    CONSTRAINT ck_source_coverage_received_within_expected CHECK ((received_feature_count <= expected_feature_count)),
    CONSTRAINT ck_source_coverage_status_matches_counts CHECK (((((status)::text = 'complete'::text) AND (received_feature_count = expected_feature_count)) OR (((status)::text = 'partial'::text) AND (received_feature_count > 0) AND (received_feature_count < expected_feature_count)) OR (((status)::text = 'no_data'::text) AND (received_feature_count = 0)) OR (((status)::text = 'failed'::text) AND (received_feature_count < expected_feature_count))))
);

-- CONSTRAINT: source_coverage_audit pk_source_coverage_audit
ALTER TABLE ONLY agri.source_coverage_audit
    ADD CONSTRAINT pk_source_coverage_audit PRIMARY KEY (id);

-- CONSTRAINT: source_coverage_audit uq_source_coverage_release_scope_window
ALTER TABLE ONLY agri.source_coverage_audit
    ADD CONSTRAINT uq_source_coverage_release_scope_window UNIQUE (source_release_id, scope_key, window_start, window_end);

-- INDEX: ix_source_coverage_audit_release_window
CREATE INDEX ix_source_coverage_audit_release_window ON agri.source_coverage_audit USING btree (source_release_id, window_start);
