-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.spatial_cell (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cell_key character varying(180) NOT NULL,
    grid_name character varying(100) NOT NULL,
    resolution_m integer NOT NULL,
    geometry public.geometry(Polygon,4326) NOT NULL,
    centroid public.geometry(Point,4326) NOT NULL,
    parent_cell_id uuid,
    coverage_fraction double precision DEFAULT '1'::double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_spatial_cell_positive_resolution CHECK ((resolution_m > 0)),
    CONSTRAINT ck_spatial_cell_valid_coverage CHECK (((coverage_fraction > (0)::double precision) AND (coverage_fraction <= (1)::double precision)))
);

-- CONSTRAINT: spatial_cell pk_spatial_cell
ALTER TABLE ONLY agri.spatial_cell
    ADD CONSTRAINT pk_spatial_cell PRIMARY KEY (id);

-- CONSTRAINT: spatial_cell uq_spatial_cell_cell_key
ALTER TABLE ONLY agri.spatial_cell
    ADD CONSTRAINT uq_spatial_cell_cell_key UNIQUE (cell_key);

-- INDEX: ix_spatial_cell_centroid
CREATE INDEX ix_spatial_cell_centroid ON agri.spatial_cell USING gist (centroid);

-- INDEX: ix_spatial_cell_geometry
CREATE INDEX ix_spatial_cell_geometry ON agri.spatial_cell USING gist (geometry);

-- INDEX: ix_spatial_cell_grid_resolution
CREATE INDEX ix_spatial_cell_grid_resolution ON agri.spatial_cell USING btree (grid_name, resolution_m);
