-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.strategy_outcome_definition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    definition_key character varying(255) NOT NULL,
    definition_version character varying(100) NOT NULL,
    metric_name character varying(150) NOT NULL,
    metric_unit character varying(64) NOT NULL,
    benefit_direction character varying(16) NOT NULL,
    smallest_meaningful_effect double precision NOT NULL,
    baseline_window interval NOT NULL,
    outcome_window interval NOT NULL,
    aggregation_method character varying(100) NOT NULL,
    transform_method character varying(100) NOT NULL,
    eligibility_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    definition_checksum character varying(64),
    review_state character varying(24) DEFAULT 'draft'::character varying NOT NULL,
    reviewed_at timestamp with time zone,
    reviewed_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_strategy_outcome_definition_benefit_direction CHECK (((benefit_direction)::text = ANY ((ARRAY['increase'::character varying, 'decrease'::character varying])::text[]))),
    CONSTRAINT ck_strategy_outcome_definition_checksum_sha256 CHECK (((definition_checksum IS NULL) OR ((definition_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_strategy_outcome_definition_eligibility_policy_object CHECK ((jsonb_typeof(eligibility_policy) = 'object'::text)),
    CONSTRAINT ck_strategy_outcome_definition_positive_windows CHECK (((baseline_window > '00:00:00'::interval) AND (outcome_window > '00:00:00'::interval))),
    CONSTRAINT ck_strategy_outcome_definition_review_evidence CHECK ((((review_state)::text = 'draft'::text) OR ((reviewed_at IS NOT NULL) AND (reviewed_by IS NOT NULL) AND ((definition_checksum)::text ~ '^[0-9a-f]{64}$'::text)))),
    CONSTRAINT ck_strategy_outcome_definition_review_state CHECK (((review_state)::text = ANY ((ARRAY['draft'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[]))),
    CONSTRAINT ck_strategy_outcome_definition_smallest_meaningful_effect CHECK (((smallest_meaningful_effect >= (0)::double precision) AND ((smallest_meaningful_effect)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))))
);

-- CONSTRAINT: strategy_outcome_definition pk_strategy_outcome_definition
ALTER TABLE ONLY agri.strategy_outcome_definition
    ADD CONSTRAINT pk_strategy_outcome_definition PRIMARY KEY (id);

-- CONSTRAINT: strategy_outcome_definition uq_strategy_outcome_definition_version
ALTER TABLE ONLY agri.strategy_outcome_definition
    ADD CONSTRAINT uq_strategy_outcome_definition_version UNIQUE (definition_key, definition_version);
