-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.strategies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    category character varying(100) NOT NULL,
    authority character varying(100) NOT NULL,
    practice_code character varying(100) NOT NULL,
    description text NOT NULL,
    min_precip_mm double precision,
    max_precip_mm double precision,
    min_temp_c double precision,
    max_temp_c double precision,
    suitable_soil_types character varying[],
    suitable_drainage character varying[],
    max_slope_pct double precision,
    min_organic_matter_pct double precision,
    water_requirement character varying(6),
    labor_intensity character varying(6),
    time_to_yield_years double precision,
    carbon_seq_potential character varying(9),
    biodiversity_impact character varying(9),
    evidence_citation text,
    evidence_source_url character varying(1000),
    jurisdiction character varying(255),
    limitations text,
    review_state character varying(8) DEFAULT 'draft'::character varying NOT NULL,
    reviewed_at timestamp with time zone,
    reviewed_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_strategies_approved_strategy_has_evidence CHECK ((((review_state)::text <> 'approved'::text) OR ((reviewed_at IS NOT NULL) AND (reviewed_by IS NOT NULL) AND (evidence_citation IS NOT NULL) AND (evidence_source_url IS NOT NULL) AND (jurisdiction IS NOT NULL) AND (limitations IS NOT NULL)))),
    CONSTRAINT ck_strategies_labor_intensity CHECK (((labor_intensity)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying])::text[]))),
    CONSTRAINT ck_strategies_strategy_biodiversity_impact_level CHECK (((biodiversity_impact)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'very_high'::character varying])::text[]))),
    CONSTRAINT ck_strategies_strategy_carbon_impact_level CHECK (((carbon_seq_potential)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'very_high'::character varying])::text[]))),
    CONSTRAINT ck_strategies_strategy_review_state CHECK (((review_state)::text = ANY ((ARRAY['draft'::character varying, 'reviewed'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[]))),
    CONSTRAINT ck_strategies_water_requirement CHECK (((water_requirement)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying])::text[])))
);

-- CONSTRAINT: strategies pk_strategies
ALTER TABLE ONLY agri.strategies
    ADD CONSTRAINT pk_strategies PRIMARY KEY (id);

-- CONSTRAINT: strategies uq_strategies_name
ALTER TABLE ONLY agri.strategies
    ADD CONSTRAINT uq_strategies_name UNIQUE (name);

-- CONSTRAINT: strategies uq_strategies_slug
ALTER TABLE ONLY agri.strategies
    ADD CONSTRAINT uq_strategies_slug UNIQUE (slug);

-- CONSTRAINT: strategies uq_strategy_authority_practice
ALTER TABLE ONLY agri.strategies
    ADD CONSTRAINT uq_strategy_authority_practice UNIQUE (authority, practice_code);
