-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.strategy_label_episode (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    episode_key character varying(255) NOT NULL,
    label_release_id uuid NOT NULL,
    analysis_subject_id uuid NOT NULL,
    strategy_id uuid,
    arm_kind character varying(16) NOT NULL,
    cohort_key character varying(255) NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    intervention_start timestamp with time zone NOT NULL,
    intervention_end timestamp with time zone NOT NULL,
    baseline_start timestamp with time zone NOT NULL,
    baseline_end timestamp with time zone NOT NULL,
    outcome_start timestamp with time zone NOT NULL,
    outcome_end timestamp with time zone NOT NULL,
    baseline_evidence_input_id uuid NOT NULL,
    outcome_evidence_input_id uuid NOT NULL,
    target_value double precision NOT NULL,
    target_unit character varying(64) NOT NULL,
    assignment_mechanism character varying(64) NOT NULL,
    known_assignment_probability double precision,
    spatial_block_key character varying(255) NOT NULL,
    covariate_snapshot jsonb NOT NULL,
    covariate_checksum character varying(64) NOT NULL,
    covariates_available_at timestamp with time zone NOT NULL,
    data_available_at timestamp with time zone NOT NULL,
    episode_checksum character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_strategy_label_episode_arm_strategy CHECK (((((arm_kind)::text = 'treatment'::text) AND (strategy_id IS NOT NULL)) OR (((arm_kind)::text = 'control'::text) AND (strategy_id IS NULL)))),
    CONSTRAINT ck_strategy_label_episode_assignment_probability CHECK (((known_assignment_probability IS NULL) OR ((known_assignment_probability > (0)::double precision) AND (known_assignment_probability < (1)::double precision)))),
    CONSTRAINT ck_strategy_label_episode_checksum_sha256 CHECK (((episode_checksum)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_strategy_label_episode_covariate_contract CHECK (((btrim((cohort_key)::text) <> ''::text) AND (jsonb_typeof(covariate_snapshot) = 'array'::text) AND (jsonb_array_length(covariate_snapshot) > 0) AND ((covariate_checksum)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_strategy_label_episode_finite_target CHECK (((target_value)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))),
    CONSTRAINT ck_strategy_label_episode_ordered_windows CHECK (((baseline_start < baseline_end) AND (baseline_end <= assigned_at) AND (assigned_at <= intervention_start) AND (intervention_start < intervention_end) AND (intervention_end <= outcome_start) AND (outcome_start < outcome_end) AND (outcome_end <= data_available_at) AND (covariates_available_at <= assigned_at)))
);

-- CONSTRAINT: strategy_label_episode pk_strategy_label_episode
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT pk_strategy_label_episode PRIMARY KEY (id);

-- CONSTRAINT: strategy_label_episode uq_strategy_label_episode_episode_checksum
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT uq_strategy_label_episode_episode_checksum UNIQUE (episode_checksum);

-- CONSTRAINT: strategy_label_episode uq_strategy_label_episode_episode_key
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT uq_strategy_label_episode_episode_key UNIQUE (episode_key);

-- INDEX: ix_strategy_label_episode_release_arm
CREATE INDEX ix_strategy_label_episode_release_arm ON agri.strategy_label_episode USING btree (label_release_id, arm_kind, strategy_id);

-- INDEX: ix_strategy_label_episode_release_block
CREATE INDEX ix_strategy_label_episode_release_block ON agri.strategy_label_episode USING btree (label_release_id, spatial_block_key);
