-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.strategy_selection_receipt (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    selection_key character varying(255) NOT NULL,
    analysis_subject_id uuid NOT NULL,
    forecast_receipt_id uuid,
    forecast_iteration_id uuid,
    feature_snapshot_id uuid NOT NULL,
    training_run_id uuid NOT NULL,
    selection_policy_id uuid NOT NULL,
    issue_time timestamp with time zone NOT NULL,
    applicability_start timestamp with time zone NOT NULL,
    applicability_end timestamp with time zone NOT NULL,
    data_cutoff timestamp with time zone NOT NULL,
    execution_mode character varying(24) DEFAULT 'evaluation_only'::character varying NOT NULL,
    claim_tier character varying(32) DEFAULT 'feasibility_candidate'::character varying NOT NULL,
    decision_state character varying(24) NOT NULL,
    abstention_reason text,
    candidate_count integer NOT NULL,
    receipt_checksum character varying(64),
    status character varying(24) DEFAULT 'staging'::character varying NOT NULL,
    finalized_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_strategy_selection_receipt_claim_tier CHECK ((((claim_tier)::text = ANY ((ARRAY['feasibility_candidate'::character varying, 'effect_candidate'::character varying])::text[])) AND (((claim_tier)::text <> 'effect_candidate'::text) OR ((execution_mode)::text = 'publishable'::text)))),
    CONSTRAINT ck_strategy_selection_receipt_decision CHECK ((((decision_state)::text = ANY ((ARRAY['ranked'::character varying, 'abstained'::character varying])::text[])) AND ((((decision_state)::text = 'ranked'::text) AND (abstention_reason IS NULL) AND (candidate_count > 0)) OR (((decision_state)::text = 'abstained'::text) AND (abstention_reason IS NOT NULL) AND (candidate_count >= 0))))),
    CONSTRAINT ck_strategy_selection_receipt_finalized_evidence CHECK ((((status)::text <> 'finalized'::text) OR (((receipt_checksum)::text ~ '^[0-9a-f]{64}$'::text) AND (finalized_at IS NOT NULL)))),
    CONSTRAINT ck_strategy_selection_receipt_forecast_source CHECK (((((execution_mode)::text = 'evaluation_only'::text) AND (forecast_iteration_id IS NOT NULL) AND (forecast_receipt_id IS NULL)) OR (((execution_mode)::text = 'publishable'::text) AND (forecast_receipt_id IS NOT NULL) AND (forecast_iteration_id IS NULL)))),
    CONSTRAINT ck_strategy_selection_receipt_ordered_times CHECK (((data_cutoff <= issue_time) AND (applicability_start >= issue_time) AND (applicability_end > applicability_start))),
    CONSTRAINT ck_strategy_selection_receipt_status CHECK (((status)::text = ANY ((ARRAY['staging'::character varying, 'finalized'::character varying])::text[])))
);

-- CONSTRAINT: strategy_selection_receipt pk_strategy_selection_receipt
ALTER TABLE ONLY agri.strategy_selection_receipt
    ADD CONSTRAINT pk_strategy_selection_receipt PRIMARY KEY (id);

-- CONSTRAINT: strategy_selection_receipt uq_strategy_selection_receipt_selection_key
ALTER TABLE ONLY agri.strategy_selection_receipt
    ADD CONSTRAINT uq_strategy_selection_receipt_selection_key UNIQUE (selection_key);

-- INDEX: ix_strategy_selection_receipt_subject_issue
CREATE INDEX ix_strategy_selection_receipt_subject_issue ON agri.strategy_selection_receipt USING btree (analysis_subject_id, issue_time DESC);
