-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.topography_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id uuid NOT NULL,
    elevation_m double precision,
    slope_pct double precision,
    aspect_deg double precision,
    curvature double precision,
    twi double precision,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CONSTRAINT: topography_profiles pk_topography_profiles
ALTER TABLE ONLY agri.topography_profiles
    ADD CONSTRAINT pk_topography_profiles PRIMARY KEY (id);

-- INDEX: ix_topography_profiles_location_id
CREATE INDEX ix_topography_profiles_location_id ON agri.topography_profiles USING btree (location_id);
