-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.vegetation_publication_day (
    observed_day date NOT NULL,
    source_fingerprint character varying(64) NOT NULL,
    published_fingerprint character varying(64),
    first_enqueued_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    last_enqueued_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    last_attempted_at timestamp with time zone,
    published_at timestamp with time zone,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_error text,
    CONSTRAINT ck_vegetation_publication_day_attempt_count CHECK ((attempt_count >= 0)),
    CONSTRAINT ck_vegetation_publication_day_published_fingerprint CHECK (((published_fingerprint IS NULL) OR ((published_fingerprint)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT ck_vegetation_publication_day_source_fingerprint CHECK (((source_fingerprint)::text ~ '^[0-9a-f]{64}$'::text))
);

-- CONSTRAINT: vegetation_publication_day vegetation_publication_day_pkey
ALTER TABLE ONLY agri.vegetation_publication_day
    ADD CONSTRAINT vegetation_publication_day_pkey PRIMARY KEY (observed_day);

-- INDEX: ix_vegetation_publication_day_pending
CREATE INDEX ix_vegetation_publication_day_pending ON agri.vegetation_publication_day USING btree (last_attempted_at, first_enqueued_at, observed_day) WHERE ((published_fingerprint)::text IS DISTINCT FROM (source_fingerprint)::text);
