-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE TABLE agri.water_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id uuid NOT NULL,
    source character varying(12) NOT NULL,
    nearest_stream_distance_m double precision,
    watershed_huc12 character varying(12),
    annual_runoff_mm double precision,
    flood_zone character varying(20),
    groundwater_depth_m double precision,
    water_table_seasonal_json jsonb,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_water_profiles_water_source CHECK (((source)::text = ANY (ARRAY[('usgs_nwis'::character varying)::text, ('noaa_atlas14'::character varying)::text])))
);

-- CONSTRAINT: water_profiles pk_water_profiles
ALTER TABLE ONLY agri.water_profiles
    ADD CONSTRAINT pk_water_profiles PRIMARY KEY (id);

-- INDEX: ix_water_profiles_location_id
CREATE INDEX ix_water_profiles_location_id ON agri.water_profiles USING btree (location_id);
