-- agent_materialized_plane_populated
-- Purpose: report, for each named relation, whether it exists and whether it has ever been
--          populated, so a tool can refuse honestly instead of raising or returning an empty
--          result that reads as an absence.
-- Loaded by: agri_data_service.agent.tools
-- Params: relation_names (text[] -- schema-qualified relation names, e.g.
--         agri.mv_forecast_ml_daily_serving)
--
-- Parameter names appear above WITHOUT a leading colon -- see "Header/bind-param trap" in
-- sql/AGENTS.md.
--
-- WHY THIS EXISTS. Every pre-aggregated relation in this design is a MATERIALIZED VIEW, and a
-- materialized view can exist while holding nothing: PostgreSQL creates it WITH NO DATA and
-- refuses to read it until a REFRESH has run, raising "materialized view has not been populated"
-- rather than returning zero rows. agri.mv_forecast_ml_daily_serving is in exactly that state in
-- production today -- created, indexed, never refreshed, and with a refresher that was reading an
-- environment variable nobody set.
--
-- That leaves an agent tool two bad options and one good one. It can let the raise escape, which
-- surfaces to the model as a tool error with no explanation. It can catch the raise and return
-- nothing, which is the worst outcome of the three because "no forecast published here" and "the
-- forecast plane has never been built" are different facts and the model cannot tell them apart.
-- Or it can ask this question first and return a TYPED REFUSAL naming the relation that is not
-- built. That is what the callers do.
--
-- The check is deliberately cheap enough to run before every read: it is a lookup in the system
-- catalog, touching no user data at all, over an array that is never longer than three entries.
--
-- ONE RELATION IS LEFT TO PROBE, AND IT IS THE ONE THIS PROBE WAS WRITTEN FOR. As of 2026-09-04
-- every environmental plane the agent read has moved to Parquet, where an unbuilt plane is not a
-- catalog state but one of the four warehouse states (`lane_never_written` above all), so nothing
-- environmental asks this question any more. What remains is agri.mv_forecast_ml_daily_serving --
-- the governed ML serving plane, which the retirement inventory classes "keep" and which really
-- did ship unpopulated. The probe stays parameterised by array rather than hard-coded to that one
-- name, because narrowing a general check to its last caller is how the next plane ships unprobed.
--
-- The probe answers `relispopulated`, WHICH IS NOT A FRESHNESS TEST, and nothing may read it as
-- one. A matview refreshed once and then frozen for a month reports true. That gap is why
-- geo.mv_signal_observation_day was removed from the probe list rather than left in it: its
-- refresh was dropped from the spec in f5510a1 after timing out at 302 s against a 300 s
-- statement_timeout, so it is populated AND frozen, and a probe that passes it would have let two
-- tools serve stale census answers with no refusal. The census question moved to the Parquet
-- availability index, which carries a source ceiling and can say how current it is.
--
-- How this query works, clause by clause:
--
--   unnest(relation_names) AS wanted(name)
--     unnest() turns an array bind parameter into rows, one per element, so the statement answers
--     about every relation the caller named in a single round trip instead of one query each.
--     The `AS wanted(name)` part gives that derived table and its single column a name to join on.
--
--   to_regclass(wanted.name)
--     Resolves a relation name to its catalog identifier, or to NULL when no such relation exists.
--     It is the non-raising form -- a plain cast to regclass raises on an unknown name, which is
--     precisely the behaviour this statement exists to avoid. A NULL here is the "the migration
--     has not been applied" case, distinct from the "applied but never refreshed" case below.
--
--   LEFT JOIN pg_catalog.pg_class ON pg_class.oid = to_regclass(wanted.name)
--     LEFT, so a relation that does not exist still comes back as a row saying so, rather than
--     vanishing from the answer. A missing row would be read by the caller as "not asked about".
--
--   pg_class.relispopulated
--     The catalog's own record of whether a matview has been refreshed at least once. False means
--     reading it would raise. For an ordinary table or view it is always true, which is correct:
--     those are always readable.
--
--   pg_class.relkind
--     Returned so the caller can tell a matview ('m') from a view ('v') or a table ('r'). A plain
--     view over matviews -- geo.v_observation_day_census is one -- reports itself populated even
--     when the matviews beneath it are not, so a caller must probe the matviews by name and not
--     the view that unions them. Returning relkind is what makes that mistake visible.
--
--   coalesce(pg_class.relispopulated, false)
--     Turns the NULL a LEFT JOIN leaves for a missing relation into an explicit false, so the
--     caller has one boolean to test rather than a three-valued one.
SELECT
    wanted.name AS relation_name,
    to_regclass(wanted.name) IS NOT NULL AS relation_exists,
    pg_class.relkind AS relation_kind,
    coalesce(pg_class.relispopulated, false) AS is_populated
FROM unnest(:relation_names) AS wanted(name)
LEFT JOIN pg_catalog.pg_class ON pg_class.oid = to_regclass(wanted.name)
ORDER BY wanted.name
