-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE MATERIALIZED VIEW agri.mv_forecast_ml_daily_serving AS
 SELECT serving.publication_id,
    serving.forecast_receipt_id,
    serving.receipt_checksum,
    serving.series_id,
    serving.series_key,
    serving.source_variant_key,
    serving.entity_type,
    serving.entity_key,
    serving.metric_name,
    serving.metric_unit,
    serving.spatial_cell_id,
    date_trunc('day'::text, serving.valid_time) AS valid_day,
    max(serving.issue_time) AS issue_time,
    avg(serving.point_value) AS mean_point_value,
    min(serving.p10_value) AS lower_p10_value,
    avg(serving.p50_value) AS median_p50_value,
    max(serving.p90_value) AS upper_p90_value,
    count(*) AS contributing_forecast_points,
    serving.representation_kind AS source_representation_kind,
    serving.spatial_support_kind AS source_spatial_support_kind,
    serving.source_spatial_resolution_m,
    serving.output_spatial_resolution_m,
    serving.source_temporal_support,
    '1 day'::interval AS output_temporal_support,
    'daily_mean_min_max_band'::text AS aggregation_method,
    serving.input_release_checksum,
    serving.feature_checksum,
    serving.model_checksum,
    serving.training_run_id,
    serving.training_code_checksum,
    serving.validation_checksum,
    'preaggregated_forecast'::text AS serving_representation
   FROM (agri.v_forecast_series_serving serving
     JOIN agri.forecast_series configured_series ON ((configured_series.id = serving.series_id)))
  WHERE (((serving.forecast_method)::text = 'ml'::text) AND configured_series.allow_ml_daily_aggregate)
  GROUP BY serving.publication_id, serving.forecast_receipt_id, serving.receipt_checksum, serving.series_id, serving.series_key, serving.source_variant_key, serving.entity_type, serving.entity_key, serving.metric_name, serving.metric_unit, serving.spatial_cell_id, (date_trunc('day'::text, serving.valid_time)), serving.representation_kind, serving.spatial_support_kind, serving.source_spatial_resolution_m, serving.output_spatial_resolution_m, serving.source_temporal_support, serving.input_release_checksum, serving.feature_checksum, serving.model_checksum, serving.training_run_id, serving.training_code_checksum, serving.validation_checksum
  WITH NO DATA;

-- INDEX: uq_mv_forecast_ml_daily_serving_identity
CREATE UNIQUE INDEX uq_mv_forecast_ml_daily_serving_identity ON agri.mv_forecast_ml_daily_serving USING btree (publication_id, forecast_receipt_id, series_id, valid_day);
