-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.covariate_feature_schema(p_schema_version character varying) RETURNS TABLE(feature_index integer, feature_name text, feature_kind text, stream_key text, signal_name text, lag_days integer, window_days integer)
    LANGUAGE plpgsql IMMUTABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET extra_float_digits TO '1'
    AS $$
        BEGIN
            IF p_schema_version <> 'agri_covariates_v1' THEN
                RAISE EXCEPTION 'unknown covariate schema version %; only agri_covariates_v1 is defined', p_schema_version;
            END IF;

            RETURN QUERY
            WITH signal_spec(signal_ordinal, signal_name) AS (
                VALUES
                    (1, 'air_temperature_max'),
                    (2, 'air_temperature_mean'),
                    (3, 'air_temperature_min'),
                    (4, 'dew_point_temperature'),
                    (5, 'precipitation'),
                    (6, 'relative_humidity'),
                    (7, 'wind_speed')
            ),
            shape_spec(shape_ordinal, name_suffix, lag_days, window_days) AS (
                VALUES
                    (1, 'lag_1', 1, 1),
                    (2, 'lag_2', 2, 1),
                    (3, 'lag_3', 3, 1),
                    (4, 'roll_mean_7', 1, 7),
                    (5, 'roll_mean_28', 1, 28)
            ),
            meteorology AS (
                SELECT
                    ((signal_spec.signal_ordinal - 1) * 5 + shape_spec.shape_ordinal) AS feature_index,
                    (signal_spec.signal_name || '_' || shape_spec.name_suffix) AS feature_name,
                    'meteorology' AS feature_kind,
                    'nasa_power' AS stream_key,
                    signal_spec.signal_name AS signal_name,
                    shape_spec.lag_days AS lag_days,
                    shape_spec.window_days AS window_days
                FROM signal_spec
                CROSS JOIN shape_spec
            ),
            derived AS (
                SELECT
                    entry.feature_index,
                    entry.feature_name,
                    entry.feature_kind,
                    entry.stream_key,
                    entry.signal_name,
                    entry.lag_days,
                    entry.window_days
                FROM (
                    VALUES
                        (36, 'drought_severity_class_lag_1', 'drought', 'usdm', NULL::text, 1, 1),
                        (37, 'drought_severity_class_lag_7', 'drought', 'usdm', NULL::text, 7, 1),
                        (38, 'drought_severity_imputed_lag_1', 'drought', 'usdm', NULL::text, 1, 1),
                        (39, 'day_of_year_sin', 'calendar', 'calendar', NULL::text, 0, 1),
                        (40, 'day_of_year_cos', 'calendar', 'calendar', NULL::text, 0, 1)
                ) AS entry(
                    feature_index, feature_name, feature_kind, stream_key,
                    signal_name, lag_days, window_days
                )
            )
            SELECT
                combined.feature_index::integer,
                combined.feature_name::text,
                combined.feature_kind::text,
                combined.stream_key::text,
                combined.signal_name::text,
                combined.lag_days::integer,
                combined.window_days::integer
            FROM (
                SELECT * FROM meteorology
                UNION ALL
                SELECT * FROM derived
            ) AS combined
            ORDER BY combined.feature_index;
        END
        $$;
