-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.drought_class_daily_series(p_cell_id uuid, p_window_start timestamp with time zone, p_window_end timestamp with time zone, p_as_of_time timestamp with time zone) RETURNS TABLE(cell_id uuid, observed_date date, severity_class integer, is_imputed boolean, issue_date date, source_release_id uuid, data_available_at timestamp with time zone, geometry_checksum text)
    LANGUAGE sql STABLE
    SET search_path TO 'public', 'pg_catalog'
    AS $$
    WITH cell AS (
        SELECT spatial_cell.geometry
        FROM agri.spatial_cell AS spatial_cell
        WHERE spatial_cell.id = p_cell_id
    ),
    admissible AS MATERIALIZED (
        SELECT
            snapshot.issue_date,
            snapshot.severity_class::integer AS severity_class,
            snapshot.source_release_id,
            snapshot.data_available_at,
            snapshot.geometry_checksum
        FROM agri.drought_polygon_snapshot AS snapshot
        CROSS JOIN cell
        WHERE snapshot.data_available_at <= p_as_of_time
          AND snapshot.issue_date <= (p_window_end AT TIME ZONE 'UTC')::date
          AND ST_Intersects(snapshot.geometry, cell.geometry)
    ),
    spine AS (
        SELECT (day_spine.bucket_start AT TIME ZONE 'UTC')::date AS observed_date
        FROM agri.forecast_date_spine(
            p_window_start,
            p_window_end + interval '1 day',
            interval '1 day'
        ) AS day_spine
    )
    SELECT
        p_cell_id,
        spine.observed_date,
        winner.severity_class,
        CASE
            WHEN winner.issue_date IS NULL THEN true
            ELSE (spine.observed_date - winner.issue_date) > 7
        END,
        winner.issue_date,
        winner.source_release_id,
        winner.data_available_at,
        winner.geometry_checksum::text
    FROM spine
    CROSS JOIN cell
    LEFT JOIN LATERAL (
        SELECT
            candidate.issue_date,
            candidate.severity_class,
            candidate.source_release_id,
            candidate.data_available_at,
            candidate.geometry_checksum
        FROM admissible AS candidate
        WHERE candidate.issue_date <= spine.observed_date
        ORDER BY
            candidate.issue_date DESC,
            candidate.severity_class DESC,
            candidate.geometry_checksum ASC
        LIMIT 1
    ) AS winner ON true
    ORDER BY spine.observed_date
$$;
