-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_forecast_hindcast_insert_contract() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF NEW.status <> 'staging' THEN
                RAISE EXCEPTION 'new hindcast runs must begin in staging status';
            END IF;
            IF NEW.receipt_digest_version <> 'hindcast_v2' THEN
                RAISE EXCEPTION 'new hindcast runs require receipt digest version hindcast_v2';
            END IF;
            RETURN NEW;
        END
        $$;
