-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_forecast_hindcast_finalization_policy() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            policy agri.forecast_quality_policy;
            actual_calibration_samples bigint;
            current_quality_passed boolean;
        BEGIN
            IF NEW.status <> 'finalized' OR OLD.status = 'finalized' THEN
                RETURN NEW;
            END IF;
            IF NEW.receipt_digest_version NOT IN ('hindcast_v2', 'hindcast_v3') THEN
                RAISE EXCEPTION
                    'hindcast finalization requires receipt digest version hindcast_v2 or hindcast_v3';
            END IF;
            IF NEW.actual_knowledge_as_of IS NULL THEN
                RAISE EXCEPTION 'hindcast finalization must pin its actual-knowledge horizon';
            END IF;
            IF NEW.availability_mode = 'as_recorded'
               AND NEW.actual_knowledge_as_of <> NEW.simulated_cutoff_time THEN
                RAISE EXCEPTION
                    'as-recorded hindcast knowledge horizon must equal the simulated cutoff';
            END IF;

            SELECT policy_row.*
              INTO STRICT policy
              FROM agri.forecast_run AS parent
              INNER JOIN agri.forecast_quality_policy AS policy_row
                  ON policy_row.id = parent.quality_policy_id
             WHERE parent.id = NEW.forecast_run_id
             FOR SHARE OF policy_row;

            IF NOT policy.is_active THEN
                RAISE EXCEPTION 'hindcast quality policy is inactive';
            END IF;

            SELECT bands.backtest_point_count
              INTO actual_calibration_samples
              FROM agri.forecast_linear_residual_bands(
                    NEW.series_id,
                    NEW.release_set_id,
                    NEW.actual_knowledge_as_of,
                    NEW.uncertainty_calibration_cutoff_time,
                    NEW.horizon_steps,
                    NEW.step_interval,
                    NEW.minimum_training_points
              ) AS bands;

            IF coalesce(actual_calibration_samples, 0) < policy.min_backtest_points THEN
                RAISE EXCEPTION
                    'hindcast uncertainty calibration has % samples; active policy requires at least %',
                    coalesce(actual_calibration_samples, 0),
                    policy.min_backtest_points;
            END IF;

            current_quality_passed := NEW.training_point_count >= policy.min_training_points
                AND NEW.coverage_fraction >= policy.min_coverage_fraction
                AND (
                    NEW.receipt_digest_version <> 'hindcast_v3'
                    OR (NEW.interval_coverage_fraction IS NOT NULL
                        AND NEW.interval_coverage_fraction >= policy.min_interval_coverage_fraction)
                )
                AND (policy.max_mae IS NULL OR NEW.mae <= policy.max_mae)
                AND (policy.max_rmse IS NULL OR NEW.rmse <= policy.max_rmse)
                AND (policy.max_mape IS NULL
                    OR (NEW.mape IS NOT NULL AND NEW.mape <= policy.max_mape))
                AND (policy.min_skill_score IS NULL
                    OR (NEW.skill_score IS NOT NULL AND NEW.skill_score >= policy.min_skill_score));
            NEW.quality_passed := current_quality_passed;
            RETURN NEW;
        END
        $$;
