-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_release_set_freeze() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            PERFORM pg_advisory_xact_lock(hashtextextended(OLD.id::text, 0));
            IF OLD.state <> 'draft' AND (
                NEW.state IS DISTINCT FROM OLD.state
                OR NEW.logical_key IS DISTINCT FROM OLD.logical_key
                OR NEW.as_of_time IS DISTINCT FROM OLD.as_of_time
                OR NEW.manifest_checksum IS DISTINCT FROM OLD.manifest_checksum
                OR NEW.validated_at IS DISTINCT FROM OLD.validated_at
                OR NEW.published_at IS DISTINCT FROM OLD.published_at
            ) THEN
                RAISE EXCEPTION 'validated release set identity is immutable'
                    USING ERRCODE = '55000';
            END IF;
            RETURN NEW;
        END;
        $$;
