-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_derived_evidence_run() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF NEW.evidence_kind = 'model_derived_feature' AND NOT EXISTS (
                SELECT 1
                FROM agri.intervention_analysis_run AS analysis_run
                WHERE analysis_run.id = NEW.intervention_analysis_run_id
                  AND analysis_run.release_set_id = NEW.release_set_id
                  AND analysis_run.validation_state = 'validated'
                  AND analysis_run.validated_at IS NOT NULL
                  AND analysis_run.method_key = NEW.method_key
                  AND analysis_run.method_version = NEW.method_version
            ) THEN
                RAISE EXCEPTION
                    'Derived evidence requires a validated release- and method-matched analysis receipt';
            END IF;
            RETURN NEW;
        END
        $$;
