-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_forecast_input_lineage() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            series_adapter varchar;
            series_source uuid;
            series_transform varchar;
            release_source uuid;
            release_transform varchar;
            release_available_at timestamptz;
            state_series_id uuid;
            state_release_id uuid;
            state_valid_from timestamptz;
            state_valid_to timestamptz;
            state_available_at timestamptz;
        BEGIN
            SELECT input_adapter, data_source_id, source_transform_version
              INTO series_adapter, series_source, series_transform
              FROM agri.forecast_series
             WHERE id = NEW.series_id;
            SELECT data_source_id, transform_version, data_available_at
              INTO release_source, release_transform, release_available_at
              FROM agri.source_release
             WHERE id = NEW.source_release_id;
            IF series_source <> release_source OR series_transform <> release_transform THEN
                RAISE EXCEPTION 'forecast input source variant does not match its series';
            END IF;
            IF NEW.data_available_at < release_available_at THEN
                RAISE EXCEPTION 'forecast input cannot be available before its source release';
            END IF;
            IF TG_TABLE_NAME = 'forecast_observation' AND series_adapter <> 'forecast_observation' THEN
                RAISE EXCEPTION 'generic forecast observation requires the forecast_observation adapter';
            END IF;
            IF TG_TABLE_NAME = 'forecast_observation'
               AND to_jsonb(NEW) ->> 'entity_state_id' IS NOT NULL THEN
                SELECT series_id, source_release_id, valid_from, valid_to, data_available_at
                  INTO state_series_id, state_release_id, state_valid_from, state_valid_to, state_available_at
                  FROM agri.forecast_entity_state
                 WHERE id = (to_jsonb(NEW) ->> 'entity_state_id')::uuid;
                IF state_series_id <> NEW.series_id
                   OR state_release_id <> NEW.source_release_id
                   OR state_available_at > NEW.data_available_at
                   OR (to_jsonb(NEW) ->> 'observed_at')::timestamptz < state_valid_from
                   OR (
                       state_valid_to IS NOT NULL
                       AND (to_jsonb(NEW) ->> 'observed_at')::timestamptz >= state_valid_to
                   ) THEN
                    RAISE EXCEPTION 'forecast observation entity state lineage mismatch';
                END IF;
            END IF;
            RETURN NEW;
        END
        $$;
