-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.enforce_release_set_membership_draft() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            candidate_release_set_id uuid;
            candidate_state text;
        BEGIN
            IF TG_OP = 'UPDATE' AND OLD.release_set_id <> NEW.release_set_id THEN
                RAISE EXCEPTION 'release set membership cannot be reparented'
                    USING ERRCODE = '55000';
            END IF;
            candidate_release_set_id := CASE
                WHEN TG_OP = 'DELETE' THEN OLD.release_set_id
                ELSE NEW.release_set_id
            END;
            SELECT state INTO candidate_state
            FROM agri.release_set
            WHERE id = candidate_release_set_id
            FOR UPDATE;
            IF candidate_state IS DISTINCT FROM 'draft' THEN
                RAISE EXCEPTION 'release set membership is immutable after validation'
                    USING ERRCODE = '55000';
            END IF;
            RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$;
