-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.expert_label_envelope_valid(p_envelope jsonb) RETURNS boolean
    LANGUAGE plpgsql IMMUTABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET extra_float_digits TO '1'
    AS $$
        DECLARE
            numeric_keys constant text[] := ARRAY[
                'mean_annual_precipitation_mm',
                'mean_annual_temperature_c',
                'growing_season_frost_free_days',
                'elevation_m'
            ];
            categorical_keys constant text[] := ARRAY[
                'soil_texture',
                'aridity',
                'usda_hardiness_zone'
            ];
            envelope_key text;
            entry jsonb;
            element jsonb;
        BEGIN
            -- The CHECK-validated key vocabulary for agri.expert_label.condition_envelope.
            -- A harvested envelope term outside this list is a schema change, not data: it
            -- must be added here and mapped onto a governed stream in the same review, so an
            -- unmappable term can never enter the plane looking mapped.
            IF p_envelope IS NULL OR jsonb_typeof(p_envelope) <> 'object' THEN
                RETURN false;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM jsonb_object_keys(p_envelope)) THEN
                RETURN false;
            END IF;

            FOR envelope_key IN SELECT jsonb_object_keys(p_envelope) LOOP
                IF NOT (envelope_key = ANY (numeric_keys) OR envelope_key = ANY (categorical_keys)) THEN
                    RETURN false;
                END IF;
                entry := p_envelope -> envelope_key;

                IF envelope_key = ANY (numeric_keys) THEN
                    -- A numeric term is a point value, a two-element [low, high] range with
                    -- either end open, or an explicit {"min": .., "max": ..} object.
                    IF jsonb_typeof(entry) = 'number' THEN
                        CONTINUE;
                    ELSIF jsonb_typeof(entry) = 'array' THEN
                        IF jsonb_array_length(entry) <> 2 THEN
                            RETURN false;
                        END IF;
                        FOR element IN SELECT jsonb_array_elements(entry) LOOP
                            IF jsonb_typeof(element) NOT IN ('number', 'null') THEN
                                RETURN false;
                            END IF;
                        END LOOP;
                        CONTINUE;
                    ELSIF jsonb_typeof(entry) = 'object' THEN
                        IF EXISTS (
                            SELECT 1
                            FROM jsonb_object_keys(entry) AS bound_key
                            WHERE bound_key NOT IN ('min', 'max')
                        ) THEN
                            RETURN false;
                        END IF;
                        IF NOT (entry ? 'min' OR entry ? 'max') THEN
                            RETURN false;
                        END IF;
                        IF jsonb_typeof(coalesce(entry -> 'min', 'null'::jsonb)) NOT IN ('number', 'null') THEN
                            RETURN false;
                        END IF;
                        IF jsonb_typeof(coalesce(entry -> 'max', 'null'::jsonb)) NOT IN ('number', 'null') THEN
                            RETURN false;
                        END IF;
                        CONTINUE;
                    END IF;
                    RETURN false;
                END IF;

                -- A categorical term is one label or a non-empty list of labels.
                IF jsonb_typeof(entry) = 'string' THEN
                    CONTINUE;
                ELSIF jsonb_typeof(entry) = 'array' THEN
                    IF jsonb_array_length(entry) = 0 THEN
                        RETURN false;
                    END IF;
                    FOR element IN SELECT jsonb_array_elements(entry) LOOP
                        IF jsonb_typeof(element) <> 'string' THEN
                            RETURN false;
                        END IF;
                    END LOOP;
                    CONTINUE;
                END IF;
                RETURN false;
            END LOOP;

            RETURN true;
        END
        $$;
