-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.expert_label_release_summary(p_release_key character varying) RETURNS TABLE(release_key text, review_tier text, harvest_slice text, label_kind text, review_state text, outcome text, label_count integer, source_count integer, subject_count integer, refuted_count integer, mean_confidence double precision)
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET extra_float_digits TO '1'
    AS $$
    -- One canonical accounting of a label release, shared by the loader's report, the
    -- owner-signature request document and the serving route's coverage answer. Bounded by
    -- construction: one release key, grouped, stably ordered.
    SELECT
        release.release_key::text,
        release.review_tier::text,
        label.harvest_slice::text,
        label.label_kind::text,
        label.review_state::text,
        label.outcome::text,
        count(*)::integer AS label_count,
        count(DISTINCT label.source_id)::integer AS source_count,
        count(DISTINCT label.subject_normalized)::integer AS subject_count,
        count(*) FILTER (WHERE label.citation_check_refuted)::integer AS refuted_count,
        avg(label.confidence_weight)::double precision AS mean_confidence
    FROM agri.expert_label_release AS release
    JOIN agri.expert_label AS label
      ON label.release_id = release.id
    WHERE release.release_key = p_release_key
    GROUP BY
        release.release_key,
        release.review_tier,
        label.harvest_slice,
        label.label_kind,
        label.review_state,
        label.outcome
    ORDER BY
        label.harvest_slice,
        label.label_kind,
        label.review_state,
        label.outcome
$$;
