-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.export_strategy_label_bundle(p_label_release_id uuid) RETURNS jsonb
    LANGUAGE plpgsql STABLE
    SET "TimeZone" TO 'UTC'
    SET extra_float_digits TO '1'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    AS $$
        DECLARE
            label agri.strategy_label_release;
            outcome agri.strategy_outcome_definition;
            bundle jsonb;
        BEGIN
            SELECT * INTO label
              FROM agri.strategy_label_release
             WHERE id = p_label_release_id;
            IF NOT FOUND
               OR label.status <> 'validated'
               OR label.receipt_checksum IS DISTINCT FROM
                    agri.strategy_label_release_checksum(label.id) THEN
                RAISE EXCEPTION 'strategy label export requires an intact validated label release';
            END IF;

            SELECT * INTO outcome
              FROM agri.strategy_outcome_definition
             WHERE id = label.outcome_definition_id;
            IF outcome.review_state <> 'approved'
               OR outcome.definition_checksum IS DISTINCT FROM
                    agri.strategy_outcome_definition_checksum(outcome) THEN
                RAISE EXCEPTION 'strategy label export requires an intact approved outcome definition';
            END IF;

            SELECT jsonb_build_object(
                'schema_version', 'strategy_labels_v1',
                'label_release_checksum', label.receipt_checksum,
                'as_of_time', label.as_of_time,
                'outcome', jsonb_build_object(
                    'key', format('%s@%s', outcome.definition_key, outcome.definition_version),
                    'unit', outcome.metric_unit,
                    'benefit_direction', outcome.benefit_direction,
                    'smallest_meaningful_effect', outcome.smallest_meaningful_effect
                ),
                'feature_names', label.feature_schema,
                'episodes', jsonb_agg(
                    jsonb_build_object(
                        'episode_id', episode.episode_key,
                        'subject_id', episode.analysis_subject_id::text,
                        'strategy_id', episode.strategy_id::text,
                        'arm', episode.arm_kind,
                        'cohort', episode.cohort_key,
                        'spatial_block', episode.spatial_block_key,
                        'assigned_at', episode.assigned_at,
                        'baseline_start', episode.baseline_start,
                        'baseline_end', episode.baseline_end,
                        'outcome_start', episode.outcome_start,
                        'outcome_end', episode.outcome_end,
                        'covariates_available_at', episode.covariates_available_at,
                        'data_available_at', episode.data_available_at,
                        'baseline_value', baseline.numeric_value,
                        'outcome_value', observed.numeric_value,
                        'features', episode.covariate_snapshot
                    )
                    ORDER BY episode.episode_key
                )
            ) INTO bundle
              FROM agri.strategy_label_episode AS episode
              INNER JOIN agri.intervention_evidence_input AS baseline
                ON baseline.id = episode.baseline_evidence_input_id
              INNER JOIN agri.intervention_evidence_input AS observed
                ON observed.id = episode.outcome_evidence_input_id
             WHERE episode.label_release_id = label.id;

            IF bundle IS NULL THEN
                RAISE EXCEPTION 'validated strategy label release has no exportable episodes';
            END IF;
            RETURN bundle;
        END
    $$;
