-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.finalize_strategy_label_release(p_label_release_id uuid, p_expected_checksum character varying) RETURNS agri.strategy_label_release
    LANGUAGE plpgsql
    AS $_$
        DECLARE
            label agri.strategy_label_release;
            pinned_release agri.release_set;
            outcome agri.strategy_outcome_definition;
            actual_row_count bigint;
            actual_treated_count bigint;
            actual_control_count bigint;
            actual_strategy_count integer;
            actual_spatial_block_count integer;
            distinct_subject_count bigint;
            invalid_episode_count bigint;
            invalid_cohort_count bigint;
            missing_taxonomy_count bigint;
            computed_checksum varchar;
        BEGIN
            IF p_expected_checksum IS NULL OR p_expected_checksum !~ '^[0-9a-f]{64}$' THEN
                RAISE EXCEPTION 'strategy label release checksum must be SHA-256';
            END IF;

            SELECT * INTO label
              FROM agri.strategy_label_release
             WHERE id = p_label_release_id
             FOR UPDATE;
            IF NOT FOUND OR label.status NOT IN ('staging', 'validated') THEN
                RAISE EXCEPTION 'strategy label release is missing or not eligible for finalization';
            END IF;

            SELECT * INTO pinned_release
              FROM agri.release_set
             WHERE id = label.release_set_id;
            SELECT * INTO outcome
              FROM agri.strategy_outcome_definition
             WHERE id = label.outcome_definition_id;
            IF pinned_release.state NOT IN ('validated', 'published')
               OR pinned_release.validated_at IS NULL
               OR pinned_release.manifest_checksum IS NULL THEN
                RAISE EXCEPTION 'strategy label release requires a validated pinned release set';
            END IF;
            IF outcome.review_state <> 'approved' THEN
                RAISE EXCEPTION 'strategy label release requires an approved outcome definition';
            END IF;
            IF outcome.definition_checksum IS DISTINCT FROM
                agri.strategy_outcome_definition_checksum(outcome) THEN
                RAISE EXCEPTION 'strategy label release outcome definition checksum mismatch';
            END IF;
            IF label.strategy_taxonomy_checksum <> encode(
                digest(label.strategy_taxonomy_snapshot::text, 'sha256'),
                'hex'
            ) THEN
                RAISE EXCEPTION 'strategy label release taxonomy snapshot checksum mismatch';
            END IF;
            IF label.feature_schema_checksum <> encode(
                digest(label.feature_schema::text, 'sha256'),
                'hex'
            )
               OR jsonb_typeof(label.feature_schema) <> 'array'
               OR jsonb_array_length(label.feature_schema) = 0
               OR EXISTS (
                    SELECT 1
                      FROM jsonb_array_elements(label.feature_schema) AS feature(value)
                     WHERE jsonb_typeof(feature.value) <> 'string'
                        OR btrim(feature.value #>> '{}') = ''
               )
               OR (
                    SELECT count(*) <> count(DISTINCT feature.value #>> '{}')
                      FROM jsonb_array_elements(label.feature_schema) AS feature(value)
               ) THEN
                RAISE EXCEPTION 'strategy label release feature schema is invalid or checksum-mismatched';
            END IF;

            SELECT
                count(*),
                count(*) FILTER (WHERE episode.arm_kind = 'treatment'),
                count(*) FILTER (WHERE episode.arm_kind = 'control'),
                count(DISTINCT episode.strategy_id) FILTER (WHERE episode.strategy_id IS NOT NULL),
                count(DISTINCT episode.spatial_block_key),
                count(DISTINCT episode.analysis_subject_id),
                count(*) FILTER (
                    WHERE baseline.analysis_subject_id <> episode.analysis_subject_id
                       OR observed.analysis_subject_id <> episode.analysis_subject_id
                       OR baseline.release_set_id <> label.release_set_id
                       OR observed.release_set_id <> label.release_set_id
                       OR baseline.evidence_kind <> 'observed_fact'
                       OR observed.evidence_kind <> 'observed_fact'
                       OR baseline.metric_name <> outcome.metric_name
                       OR observed.metric_name <> outcome.metric_name
                       OR baseline.numeric_value IS NULL
                       OR observed.numeric_value IS NULL
                       OR baseline.value_unit IS DISTINCT FROM outcome.metric_unit
                       OR observed.value_unit IS DISTINCT FROM outcome.metric_unit
                       OR episode.target_unit <> outcome.metric_unit
                       OR episode.covariate_checksum <> encode(
                            digest(episode.covariate_snapshot::text, 'sha256'),
                            'hex'
                       )
                       OR jsonb_typeof(episode.covariate_snapshot) <> 'array'
                       OR jsonb_array_length(episode.covariate_snapshot) <>
                            jsonb_array_length(label.feature_schema)
                       OR EXISTS (
                            SELECT 1
                              FROM jsonb_array_elements(episode.covariate_snapshot) AS covariate(value)
                             WHERE jsonb_typeof(covariate.value) <> 'number'
                       )
                       OR episode.covariates_available_at > episode.assigned_at
                       OR baseline.data_available_at > label.as_of_time
                       OR observed.data_available_at > label.as_of_time
                       OR episode.data_available_at > label.as_of_time
                       OR episode.outcome_end > episode.data_available_at
                       OR baseline.observed_from IS NULL
                       OR baseline.observed_to IS NULL
                       OR observed.observed_from IS NULL
                       OR observed.observed_to IS NULL
                       OR baseline.observed_from > episode.baseline_start
                       OR baseline.observed_to < episode.baseline_end
                       OR observed.observed_from > episode.outcome_start
                       OR observed.observed_to < episode.outcome_end
                       OR episode.episode_checksum IS DISTINCT FROM
                            agri.strategy_label_episode_checksum(episode.id)
                       OR episode.baseline_end - episode.baseline_start <> outcome.baseline_window
                       OR episode.outcome_end - episode.outcome_start <> outcome.outcome_window
                       OR episode.target_value IS DISTINCT FROM CASE outcome.benefit_direction
                            WHEN 'increase' THEN observed.numeric_value - baseline.numeric_value
                            WHEN 'decrease' THEN baseline.numeric_value - observed.numeric_value
                       END
                )
              INTO
                actual_row_count,
                actual_treated_count,
                actual_control_count,
                actual_strategy_count,
                actual_spatial_block_count,
                distinct_subject_count,
                invalid_episode_count
              FROM agri.strategy_label_episode AS episode
              INNER JOIN agri.intervention_evidence_input AS baseline
                ON baseline.id = episode.baseline_evidence_input_id
              INNER JOIN agri.intervention_evidence_input AS observed
                ON observed.id = episode.outcome_evidence_input_id
             WHERE episode.label_release_id = label.id;

            SELECT count(*) INTO missing_taxonomy_count
              FROM agri.strategy_label_episode AS episode
             WHERE episode.label_release_id = label.id
               AND episode.arm_kind = 'treatment'
               AND NOT EXISTS (
                    SELECT 1
                      FROM jsonb_array_elements(label.strategy_taxonomy_snapshot) AS item
                     WHERE item ->> 'strategy_id' = episode.strategy_id::text
               );

            SELECT count(*) INTO invalid_cohort_count
              FROM (
                    SELECT episode.cohort_key
                      FROM agri.strategy_label_episode AS episode
                     WHERE episode.label_release_id = label.id
                     GROUP BY episode.cohort_key
                    HAVING count(DISTINCT episode.assigned_at) <> 1
              ) AS invalid_cohort;

            IF actual_row_count <> label.row_count
               OR actual_treated_count <> label.treated_count
               OR actual_control_count <> label.control_count
               OR actual_strategy_count <> label.strategy_count
               OR actual_spatial_block_count <> label.spatial_block_count
               OR distinct_subject_count <> label.row_count THEN
                RAISE EXCEPTION 'strategy label release declared counts do not match persisted episodes';
            END IF;
            IF invalid_episode_count > 0 THEN
                RAISE EXCEPTION 'strategy label release contains lineage, feature, availability, window, metric, or unit mismatch';
            END IF;
            IF missing_taxonomy_count > 0 THEN
                RAISE EXCEPTION 'strategy label release treatment is absent from the pinned taxonomy snapshot';
            END IF;
            IF invalid_cohort_count > 0 THEN
                RAISE EXCEPTION 'strategy label release cohort maps to multiple assignment times';
            END IF;

            computed_checksum := agri.strategy_label_release_checksum(label.id);
            IF computed_checksum IS DISTINCT FROM p_expected_checksum THEN
                RAISE EXCEPTION 'strategy label release checksum mismatch';
            END IF;

            IF label.status = 'staging' THEN
                UPDATE agri.strategy_label_release
                   SET status = 'validated',
                       receipt_checksum = computed_checksum,
                       validated_at = now()
                 WHERE id = label.id
                 RETURNING * INTO label;
            ELSIF label.receipt_checksum IS DISTINCT FROM computed_checksum THEN
                RAISE EXCEPTION 'validated strategy label release no longer matches its receipt';
            END IF;
            RETURN label;
        END
    $_$;
