-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.finalize_strategy_selection_receipt(p_selection_receipt_id uuid, p_expected_checksum character varying) RETURNS agri.strategy_selection_receipt
    LANGUAGE plpgsql
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    SET search_path TO 'public', 'pg_catalog'
    AS $_$
        DECLARE
            receipt agri.strategy_selection_receipt;
            training agri.forecast_training_run;
            model agri.forecast_model;
            feature agri.forecast_feature_snapshot;
            label agri.strategy_label_release;
            policy agri.strategy_selection_policy;
            actual_candidate_count integer;
            ranked_candidate_count integer;
            minimum_rank integer;
            maximum_rank integer;
            invalid_candidate_count integer;
            computed_checksum varchar;
        BEGIN
            IF p_expected_checksum IS NULL OR p_expected_checksum !~ '^[0-9a-f]{64}$' THEN
                RAISE EXCEPTION 'strategy selection receipt checksum must be SHA-256';
            END IF;

            SELECT * INTO receipt
              FROM agri.strategy_selection_receipt
             WHERE id = p_selection_receipt_id
             FOR UPDATE;
            IF NOT FOUND OR receipt.status NOT IN ('staging', 'finalized') THEN
                RAISE EXCEPTION 'strategy selection receipt is missing or not eligible for finalization';
            END IF;
            IF receipt.audit_state <> 'clear' THEN
                RAISE EXCEPTION
                    'strategy selection receipt is flagged % and cannot be finalized', receipt.audit_state;
            END IF;

            SELECT * INTO training
              FROM agri.forecast_training_run
             WHERE id = receipt.training_run_id;
            SELECT * INTO model
              FROM agri.forecast_model
             WHERE id = training.model_id;
            SELECT * INTO feature
              FROM agri.forecast_feature_snapshot
             WHERE id = receipt.feature_snapshot_id;
            SELECT * INTO label
              FROM agri.strategy_label_release
             WHERE id = training.strategy_label_release_id;
            SELECT * INTO policy
              FROM agri.strategy_selection_policy
             WHERE id = receipt.selection_policy_id;

            IF training.status <> 'validated'
               OR model.model_purpose <> 'strategy_selection'
               OR training.feature_snapshot_id <> receipt.feature_snapshot_id
               OR training.strategy_label_release_id IS NULL
               OR training.strategy_label_checksum IS DISTINCT FROM label.receipt_checksum
               OR feature.status <> 'validated'
               OR feature.job_output_id IS NULL
               OR label.status <> 'validated'
               OR policy.review_state <> 'approved' THEN
                RAISE EXCEPTION 'strategy selection lineage is not validated and policy-approved';
            END IF;
            IF policy.policy_checksum IS DISTINCT FROM
                agri.strategy_selection_policy_checksum(policy) THEN
                RAISE EXCEPTION 'strategy selection policy checksum mismatch';
            END IF;
            IF label.as_of_time > receipt.data_cutoff
               OR feature.training_window_end > receipt.data_cutoff THEN
                RAISE EXCEPTION 'strategy selection inputs became available after the declared cutoff';
            END IF;

            IF receipt.execution_mode = 'evaluation_only' THEN
                IF NOT EXISTS (
                    SELECT 1
                      FROM agri.forecast_iteration AS iteration
                     WHERE iteration.id = receipt.forecast_iteration_id
                       AND iteration.status = 'finalized'
                       AND iteration.as_of_time = receipt.issue_time
                ) THEN
                    RAISE EXCEPTION 'evaluation-only strategy selection requires its finalized forecast iteration';
                END IF;
                IF agri.strategy_selection_cutoff_violation(receipt.id) THEN
                    RAISE EXCEPTION
                        'strategy selection forecast iteration cutoff is later than the declared data cutoff';
                END IF;
            ELSIF NOT EXISTS (
                SELECT 1
                  FROM agri.forecast_receipt AS forecast
                  INNER JOIN agri.forecast_publication_item AS item
                    ON item.forecast_receipt_id = forecast.id
                  INNER JOIN agri.forecast_publication AS publication
                    ON publication.id = item.publication_id
                 WHERE forecast.id = receipt.forecast_receipt_id
                   AND forecast.status = 'finalized'
                   AND forecast.issue_time = receipt.issue_time
                   AND publication.state = 'published'
            ) THEN
                RAISE EXCEPTION 'publishable strategy selection requires a published finalized forecast receipt';
            END IF;

            IF NOT agri.strategy_selection_quality_evidence(receipt.id) THEN
                IF receipt.execution_mode = 'evaluation_only' THEN
                    RAISE EXCEPTION
                        'strategy selection requires a finalized quality-passed hindcast for its backing series';
                ELSE
                    RAISE EXCEPTION
                        'strategy selection requires a finalized quality-passed hindcast for its backing series and model';
                END IF;
            END IF;

            SELECT
                count(*),
                count(*) FILTER (WHERE candidate.rank IS NOT NULL),
                min(candidate.rank),
                max(candidate.rank),
                count(*) FILTER (
                    WHERE candidate.strategy_snapshot ->> 'strategy_id' IS DISTINCT FROM candidate.strategy_id::text
                       OR candidate.strategy_snapshot_checksum <> encode(
                            digest(candidate.strategy_snapshot::text, 'sha256'),
                            'hex'
                       )
                       OR candidate.candidate_checksum IS DISTINCT FROM
                            agri.strategy_selection_candidate_checksum(candidate.id)
                       OR (candidate.rank IS NOT NULL AND candidate.eligibility_state <> 'eligible')
                )
              INTO
                actual_candidate_count,
                ranked_candidate_count,
                minimum_rank,
                maximum_rank,
                invalid_candidate_count
              FROM agri.strategy_selection_candidate AS candidate
             WHERE candidate.selection_receipt_id = receipt.id;

            IF actual_candidate_count <> receipt.candidate_count THEN
                RAISE EXCEPTION 'strategy selection candidate count mismatch';
            END IF;
            IF invalid_candidate_count > 0 THEN
                RAISE EXCEPTION 'strategy selection candidate snapshot, checksum, eligibility, or rank is invalid';
            END IF;
            IF receipt.decision_state = 'ranked'
               AND (
                    ranked_candidate_count < 1
                    OR minimum_rank <> 1
                    OR maximum_rank <> ranked_candidate_count
               ) THEN
                RAISE EXCEPTION 'ranked strategy selection requires contiguous eligible ranks';
            END IF;
            IF receipt.decision_state = 'abstained' AND ranked_candidate_count <> 0 THEN
                RAISE EXCEPTION 'abstained strategy selection cannot retain ranked candidates';
            END IF;
            IF receipt.claim_tier = 'feasibility_candidate'
               AND EXISTS (
                    SELECT 1
                      FROM agri.strategy_selection_candidate
                     WHERE selection_receipt_id = receipt.id
                       AND evidence_tier <> 'feasibility_candidate'
               ) THEN
                RAISE EXCEPTION 'feasibility receipt cannot contain effect-tier candidates';
            END IF;

            IF receipt.claim_tier = 'effect_candidate' THEN
                -- A later revision must add cluster-bootstrap, placebo,
                -- negative-control, and best-vs-second lower-bound gates.
                RAISE EXCEPTION
                    'effect_candidate finalization is disabled in strategy_selection_v1';
            END IF;

            computed_checksum := agri.strategy_selection_receipt_checksum(receipt.id);
            IF computed_checksum IS DISTINCT FROM p_expected_checksum THEN
                RAISE EXCEPTION 'strategy selection receipt checksum mismatch';
            END IF;

            IF receipt.status = 'staging' THEN
                UPDATE agri.strategy_selection_receipt
                   SET status = 'finalized',
                       receipt_checksum = computed_checksum,
                       finalized_at = now()
                 WHERE id = receipt.id
                 RETURNING * INTO receipt;
            ELSIF receipt.receipt_checksum IS DISTINCT FROM computed_checksum THEN
                RAISE EXCEPTION 'finalized strategy selection no longer matches its receipt';
            END IF;
            RETURN receipt;
        END
    $_$;
