-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.finalize_forecast_receipt(p_receipt_id uuid, p_expected_checksum character varying) RETURNS agri.forecast_receipt
    LANGUAGE plpgsql
    AS $_$
        DECLARE
            receipt agri.forecast_receipt;
            run_status varchar;
            run_issue_time timestamptz;
            run_valid_from timestamptz;
            run_valid_to timestamptz;
            run_horizon_steps integer;
            run_step_interval interval;
            required_quantiles double precision[];
            output_state varchar;
            output_run_id uuid;
            output_checksum varchar;
            output_row_count bigint;
            actual_count integer;
            actual_min_time timestamptz;
            actual_max_time timestamptz;
            actual_checksum varchar;
            missing_band_count integer;
            invalid_grid_count integer;
            state_series_id uuid;
            state_valid_from timestamptz;
            state_valid_to timestamptz;
            state_available_at timestamptz;
        BEGIN
            IF p_expected_checksum !~ '^[0-9a-f]{64}$' THEN
                RAISE EXCEPTION 'receipt checksum must be SHA-256';
            END IF;
            SELECT * INTO receipt
              FROM agri.forecast_receipt
             WHERE id = p_receipt_id
             FOR UPDATE;
            IF NOT FOUND OR receipt.status NOT IN ('staging', 'finalized') THEN
                RAISE EXCEPTION 'forecast receipt is missing or not eligible for finalization';
            END IF;
            SELECT
                run.status, run.issue_time, run.valid_from, run.valid_to,
                run.horizon_steps, run.step_interval, policy.required_quantiles
              INTO
                run_status, run_issue_time, run_valid_from, run_valid_to,
                run_horizon_steps, run_step_interval, required_quantiles
              FROM agri.forecast_run AS run
              INNER JOIN agri.forecast_quality_policy AS policy ON policy.id = run.quality_policy_id
             WHERE run.id = receipt.forecast_run_id;
            IF run_status <> 'validated' THEN
                RAISE EXCEPTION 'forecast receipt requires a validated forecast run';
            END IF;
            IF NOT EXISTS (
                SELECT 1
                FROM agri.forecast_backtest_metric AS metric
                INNER JOIN agri.job_output AS output ON output.id = metric.job_output_id
                WHERE metric.forecast_run_id = receipt.forecast_run_id
                  AND metric.series_id = receipt.series_id
                  AND metric.passed
                  AND output.state IN ('validated', 'published')
                  AND output.checksum_sha256 = metric.metrics_checksum
                  AND output.row_count = 1
            ) THEN
                RAISE EXCEPTION 'forecast receipt series has no passing backtest evidence';
            END IF;
            IF receipt.issue_time <> run_issue_time
               OR receipt.valid_from <> run_valid_from
               OR receipt.valid_to <> run_valid_to
               OR receipt.expected_value_count <> run_horizon_steps
               OR NOT receipt.quantile_levels @> required_quantiles THEN
                RAISE EXCEPTION 'forecast receipt issue, valid-time, or quantile policy mismatch';
            END IF;
            IF receipt.entity_state_id IS NOT NULL THEN
                SELECT series_id, valid_from, valid_to, data_available_at
                  INTO state_series_id, state_valid_from, state_valid_to, state_available_at
                  FROM agri.forecast_entity_state
                 WHERE id = receipt.entity_state_id;
                IF state_series_id <> receipt.series_id
                   OR state_available_at > receipt.issue_time
                   OR receipt.issue_time < state_valid_from
                   OR (state_valid_to IS NOT NULL AND receipt.issue_time >= state_valid_to) THEN
                    RAISE EXCEPTION 'forecast receipt entity state lineage mismatch';
                END IF;
            END IF;
            SELECT state, job_run_id, checksum_sha256, row_count
              INTO output_state, output_run_id, output_checksum, output_row_count
              FROM agri.job_output
             WHERE id = receipt.job_output_id;
            IF output_state NOT IN ('validated', 'published')
               OR output_run_id <> (SELECT job_run_id FROM agri.forecast_run WHERE id = receipt.forecast_run_id)
               OR output_checksum <> p_expected_checksum
               OR output_row_count IS NULL
               OR output_row_count <> receipt.expected_value_count THEN
                RAISE EXCEPTION 'forecast receipt job output lineage mismatch';
            END IF;

            SELECT
                count(*),
                min(value.valid_time),
                max(value.valid_time),
                count(*) FILTER (
                    WHERE value.horizon_step < 1
                       OR value.horizon_step > run_horizon_steps
                       OR value.valid_time <> receipt.issue_time + (run_step_interval * value.horizon_step)
                ),
                count(*) FILTER (
                    WHERE EXISTS (
                        SELECT 1
                        FROM unnest(receipt.quantile_levels) AS required(quantile)
                        WHERE NOT (value.quantile_values ? required.quantile::text)
                           OR jsonb_typeof(value.quantile_values -> required.quantile::text) <> 'number'
                           OR CASE
                               WHEN jsonb_typeof(value.quantile_values -> required.quantile::text) = 'number'
                               THEN ((value.quantile_values ->> required.quantile::text)::double precision)::text
                                    IN ('NaN', 'Infinity', '-Infinity')
                               ELSE false
                           END
                    )
                       OR EXISTS (
                           SELECT 1
                           FROM unnest(receipt.quantile_levels) AS lower(quantile)
                           CROSS JOIN unnest(receipt.quantile_levels) AS upper(quantile)
                           WHERE lower.quantile < upper.quantile
                             AND CASE
                                 WHEN jsonb_typeof(value.quantile_values -> lower.quantile::text) = 'number'
                                  AND jsonb_typeof(value.quantile_values -> upper.quantile::text) = 'number'
                                 THEN (value.quantile_values ->> lower.quantile::text)::double precision
                                      > (value.quantile_values ->> upper.quantile::text)::double precision
                                 ELSE false
                             END
                       )
                       OR (
                           0.1 = ANY(receipt.quantile_levels)
                           AND (value.quantile_values ->> '0.1')::double precision IS DISTINCT FROM value.p10_value
                       )
                       OR (
                           0.5 = ANY(receipt.quantile_levels)
                           AND (value.quantile_values ->> '0.5')::double precision IS DISTINCT FROM value.p50_value
                       )
                       OR (
                           0.9 = ANY(receipt.quantile_levels)
                           AND (value.quantile_values ->> '0.9')::double precision IS DISTINCT FROM value.p90_value
                       )
                ),
                encode(
                    digest(
                        coalesce(string_agg(
                            concat_ws('|',
                                to_char(value.valid_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
                                value.horizon_step::text,
                                value.point_value::text,
                                coalesce(value.p10_value::text, ''),
                                coalesce(value.p50_value::text, ''),
                                coalesce(value.p90_value::text, ''),
                                value.quantile_values::text
                            ), E'\n' ORDER BY value.horizon_step), ''),
                        'sha256'
                    ),
                    'hex'
                )
              INTO
                actual_count, actual_min_time, actual_max_time,
                invalid_grid_count, missing_band_count, actual_checksum
              FROM agri.forecast_value AS value
             WHERE value.forecast_receipt_id = receipt.id;

            IF actual_count <> receipt.expected_value_count
               OR actual_min_time < receipt.valid_from
               OR actual_max_time >= receipt.valid_to
               OR invalid_grid_count > 0
               OR missing_band_count > 0 THEN
                RAISE EXCEPTION 'forecast receipt count or valid-time extent mismatch';
            END IF;
            IF actual_checksum <> p_expected_checksum THEN
                RAISE EXCEPTION 'forecast receipt checksum mismatch';
            END IF;

            IF receipt.status = 'staging' THEN
                UPDATE agri.forecast_receipt
                   SET status = 'finalized', receipt_checksum = actual_checksum, finalized_at = now()
                 WHERE id = receipt.id
                 RETURNING * INTO receipt;
            ELSIF receipt.receipt_checksum <> actual_checksum THEN
                RAISE EXCEPTION 'finalized forecast receipt checksum changed';
            END IF;
            RETURN receipt;
        END
        $_$;
