-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_aligned_daily_series(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_window_start timestamp with time zone, p_window_end timestamp with time zone, p_gap_policy character varying DEFAULT 'strict'::character varying) RETURNS TABLE(grain_index integer, bucket_start timestamp with time zone, bucket_end timestamp with time zone, metric_value double precision, source_sample_count bigint, is_missing boolean, is_imputed boolean, source_release_ids uuid[], observation_checksums text[], data_available_at timestamp with time zone, alignment_checksum text)
    LANGUAGE plpgsql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        DECLARE
            source_support interval;
            desired_grain interval;
            configured_aggregation text;
        BEGIN
            IF p_gap_policy NOT IN ('strict', 'locf') THEN
                RAISE EXCEPTION 'daily alignment gap policy must be strict or locf';
            END IF;

            SELECT
                contract.source_temporal_support,
                contract.desired_temporal_grain,
                contract.aggregation_method
              INTO source_support, desired_grain, configured_aggregation
              FROM agri.v_forecast_timeseries_contract AS contract
             WHERE contract.series_id = p_series_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'forecast series % is not registered', p_series_id;
            END IF;
            IF source_support > interval '1 day' OR desired_grain > interval '1 day' THEN
                RAISE EXCEPTION
                    'daily alignment refuses to fabricate daily precision from source support % or desired grain %',
                    source_support,
                    desired_grain;
            END IF;
            IF source_support < interval '1 day'
               AND lower(coalesce(configured_aggregation, ''))
                    NOT IN ('mean', 'avg', 'daily_mean') THEN
                RAISE EXCEPTION
                    'daily alignment v1 requires explicit mean aggregation for subdaily sources';
            END IF;

            RETURN QUERY
            WITH daily AS (
                SELECT
                    spine.grain_index,
                    spine.bucket_start,
                    spine.bucket_end,
                    avg(contract.metric_value) AS metric_value,
                    count(contract.metric_value) AS source_sample_count,
                    coalesce(
                        array_agg(DISTINCT contract.source_release_id ORDER BY contract.source_release_id)
                            FILTER (WHERE contract.source_release_id IS NOT NULL),
                        ARRAY[]::uuid[]
                    ) AS source_release_ids,
                    coalesce(
                        array_agg(DISTINCT contract.observation_checksum ORDER BY contract.observation_checksum)
                            FILTER (WHERE contract.observation_checksum IS NOT NULL),
                        ARRAY[]::text[]
                    ) AS observation_checksums,
                    max(contract.data_available_at) AS data_available_at
                FROM agri.forecast_date_spine(
                    p_window_start,
                    p_window_end,
                    interval '1 day'
                ) AS spine
                LEFT JOIN agri.forecast_timeseries_contract(
                    p_release_set_id,
                    p_as_of_time
                ) AS contract
                  ON contract.series_id = p_series_id
                 AND contract.observed_at >= spine.bucket_start
                 AND contract.observed_at < spine.bucket_end
                GROUP BY spine.grain_index, spine.bucket_start, spine.bucket_end
            ),
            selected AS (
                SELECT
                    daily.grain_index,
                    daily.bucket_start,
                    daily.bucket_end,
                    coalesce(daily.metric_value, carried.metric_value) AS metric_value,
                    daily.source_sample_count,
                    coalesce(daily.metric_value, carried.metric_value) IS NULL AS is_missing,
                    daily.metric_value IS NULL AND carried.metric_value IS NOT NULL AS is_imputed,
                    CASE
                        WHEN daily.metric_value IS NOT NULL THEN daily.source_release_ids
                        ELSE coalesce(carried.source_release_ids, ARRAY[]::uuid[])
                    END AS source_release_ids,
                    CASE
                        WHEN daily.metric_value IS NOT NULL THEN daily.observation_checksums
                        ELSE coalesce(carried.observation_checksums, ARRAY[]::text[])
                    END AS observation_checksums,
                    coalesce(daily.data_available_at, carried.data_available_at) AS data_available_at
                FROM daily
                LEFT JOIN LATERAL (
                    SELECT
                        previous.metric_value,
                        previous.source_release_ids,
                        previous.observation_checksums,
                        previous.data_available_at
                    FROM daily AS previous
                    WHERE p_gap_policy = 'locf'
                      AND daily.metric_value IS NULL
                      AND previous.bucket_start = daily.bucket_start - interval '1 day'
                      AND previous.metric_value IS NOT NULL
                    LIMIT 1
                ) AS carried ON true
            )
            SELECT
                selected.grain_index,
                selected.bucket_start,
                selected.bucket_end,
                selected.metric_value,
                selected.source_sample_count,
                selected.is_missing,
                selected.is_imputed,
                selected.source_release_ids,
                selected.observation_checksums,
                selected.data_available_at,
                encode(
                    digest(
                        concat_ws(
                            '|',
                            'forecast_daily_alignment_v1',
                            p_series_id::text,
                            p_release_set_id::text,
                            selected.bucket_start::text,
                            coalesce(selected.metric_value::text, ''),
                            selected.source_sample_count::text,
                            selected.is_missing::text,
                            selected.is_imputed::text,
                            selected.source_release_ids::text,
                            selected.observation_checksums::text,
                            coalesce(selected.data_available_at::text, ''),
                            p_gap_policy,
                            source_support::text,
                            desired_grain::text,
                            coalesce(configured_aggregation, '')
                        ),
                        'sha256'
                    ),
                    'hex'
                )
            FROM selected
            ORDER BY selected.bucket_start;
        END
        $$;
