-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_normalized_series(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_window_start timestamp with time zone, p_window_end timestamp with time zone, p_bucket_interval interval) RETURNS TABLE(bucket_start timestamp with time zone, bucket_end timestamp with time zone, sample_count bigint, metric_value double precision, minimum_value double precision, maximum_value double precision, is_missing boolean, serving_representation text)
    LANGUAGE plpgsql STABLE
    AS $$
        BEGIN
            IF p_window_end <= p_window_start THEN
                RAISE EXCEPTION 'normalization window must be non-empty';
            END IF;
            IF p_bucket_interval <= interval '0'
               OR extract(year FROM p_bucket_interval) <> 0
               OR extract(month FROM p_bucket_interval) <> 0 THEN
                RAISE EXCEPTION 'normalization bucket must be a positive fixed interval without months';
            END IF;

            RETURN QUERY
            SELECT
                bucket.bucket_start,
                bucket.bucket_start + p_bucket_interval,
                count(base.metric_value),
                avg(base.metric_value),
                min(base.metric_value),
                max(base.metric_value),
                count(base.metric_value) = 0,
                'normalized_bucket'::text
            FROM generate_series(
                p_window_start,
                p_window_end - p_bucket_interval,
                p_bucket_interval
            ) AS bucket(bucket_start)
            LEFT JOIN agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
              ON base.series_id = p_series_id
             AND base.observed_at >= bucket.bucket_start
             AND base.observed_at < bucket.bucket_start + p_bucket_interval
            GROUP BY bucket.bucket_start
            ORDER BY bucket.bucket_start;
        END
        $$;
