-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_timeseries_base(p_release_set_id uuid, p_as_of_time timestamp with time zone) RETURNS TABLE(observation_id bigint, series_id uuid, series_key text, source_variant_key text, entity_type text, entity_key text, entity_state_id uuid, entity_state_checksum text, metric_name text, metric_unit text, observed_at timestamp with time zone, metric_value double precision, representation_kind text, spatial_support_kind text, source_spatial_resolution_m integer, output_spatial_resolution_m integer, source_temporal_support interval, output_temporal_support interval, aggregation_method text, spatial_cell_id uuid, source_release_id uuid, input_release_checksum text, observation_checksum text)
    LANGUAGE sql STABLE
    AS $$
            SELECT
                NULL::bigint,
                series.id,
                series.series_key::text,
                series.source_variant_key::text,
                series.entity_type::text,
                series.entity_key::text,
                NULL::uuid,
                NULL::text,
                series.metric_name::text,
                series.metric_unit::text,
                source_contract.observed_at,
                source_contract.normalized_value,
                series.representation_kind::text,
                source_contract.spatial_support_kind,
                source_contract.native_resolution_m,
                source_contract.analysis_resolution_m,
                series.source_temporal_support,
                series.output_temporal_support,
                series.aggregation_method::text,
                source_contract.cell_id,
                source_contract.source_release_id,
                release_set.manifest_checksum::text,
                encode(digest(concat_ws('|',
                    source_release.payload_checksum,
                    source_contract.cell_id::text,
                    source_contract.signal_name,
                    source_contract.source_parameter,
                    source_contract.support_key,
                    source_contract.observed_at::text,
                    source_contract.normalized_value::text
                ), 'sha256'), 'hex')
            FROM agri.forecast_series AS series
            INNER JOIN agri.v_signal_timeseries_contract(p_as_of_time, p_release_set_id) AS source_contract
                ON source_contract.cell_id = series.spatial_cell_id
               AND source_contract.signal_name = series.signal_name
               AND source_contract.source_parameter = series.source_parameter
               AND source_contract.support_key = series.support_key
               AND source_contract.transform_version = series.source_transform_version
               AND source_contract.normalized_unit = series.metric_unit
            INNER JOIN agri.source_release AS source_release
                ON source_release.id = source_contract.source_release_id
               AND source_release.data_source_id = series.data_source_id
            INNER JOIN agri.release_set AS release_set
                ON release_set.id = p_release_set_id
            WHERE series.input_adapter = 'signal_observation'
              AND source_contract.normalized_value IS NOT NULL

            UNION ALL

            SELECT
                observation.id,
                series.id,
                series.series_key::text,
                series.source_variant_key::text,
                series.entity_type::text,
                series.entity_key::text,
                state.id,
                state.state_checksum::text,
                series.metric_name::text,
                series.metric_unit::text,
                observation.observed_at,
                observation.metric_value,
                series.representation_kind::text,
                series.spatial_support_kind::text,
                series.source_spatial_resolution_m,
                series.output_spatial_resolution_m,
                series.source_temporal_support,
                series.output_temporal_support,
                series.aggregation_method::text,
                series.spatial_cell_id,
                observation.source_release_id,
                release_set.manifest_checksum::text,
                observation.observation_checksum::text
            FROM agri.forecast_observation AS observation
            INNER JOIN agri.forecast_series AS series ON series.id = observation.series_id
            LEFT JOIN agri.forecast_entity_state AS state ON state.id = observation.entity_state_id
            INNER JOIN agri.source_release AS source_release
                ON source_release.id = observation.source_release_id
               AND source_release.data_source_id = series.data_source_id
               AND source_release.transform_version = series.source_transform_version
            INNER JOIN agri.release_set_item AS member
                ON member.source_release_id = source_release.id
            INNER JOIN agri.release_set AS release_set
                ON release_set.id = member.release_set_id
            WHERE release_set.id = p_release_set_id
              AND series.input_adapter = 'forecast_observation'
              AND release_set.state IN ('validated', 'published')
              AND release_set.validated_at <= p_as_of_time
              AND release_set.as_of_time <= p_as_of_time
              AND source_release.validation_state = 'valid'
              AND source_release.data_available_at <= p_as_of_time
              AND observation.data_available_at <= p_as_of_time
              AND (
                    state.id IS NULL
                    OR (
                        state.source_release_id = observation.source_release_id
                        AND state.series_id = series.id
                        AND state.data_available_at <= p_as_of_time
                        AND observation.observed_at >= state.valid_from
                        AND (state.valid_to IS NULL OR observation.observed_at < state.valid_to)
                    )
              )
        $$;
