-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_linear_residual_bands(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_cutoff_time timestamp with time zone, p_horizon_steps integer, p_step_interval interval, p_min_training_points integer DEFAULT 30) RETURNS TABLE(training_point_count bigint, backtest_point_count bigint, residual_p10 double precision, residual_p50 double precision, residual_p90 double precision, eligible boolean, gate_reason text)
    LANGUAGE sql STABLE
    AS $$
            WITH predictions AS (
                SELECT *
                FROM agri.forecast_linear_regression(
                    p_series_id,
                    p_release_set_id,
                    p_as_of_time,
                    p_cutoff_time,
                    p_horizon_steps,
                    p_step_interval,
                    p_min_training_points
                )
            ),
            actuals AS (
                SELECT base.observed_at, base.metric_value
                FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                WHERE base.series_id = p_series_id
                  AND base.observed_at > p_cutoff_time
                  AND base.observed_at <= p_cutoff_time + (p_step_interval * p_horizon_steps)
            ),
            residuals AS (
                SELECT
                    prediction.training_point_count,
                    prediction.eligible,
                    prediction.gate_reason,
                    actual.metric_value - prediction.forecast_value AS residual
                FROM predictions AS prediction
                LEFT JOIN actuals AS actual ON actual.observed_at = prediction.valid_time
            )
            SELECT
                max(residuals.training_point_count),
                count(residuals.residual),
                percentile_cont(0.1) WITHIN GROUP (ORDER BY residuals.residual),
                percentile_cont(0.5) WITHIN GROUP (ORDER BY residuals.residual),
                percentile_cont(0.9) WITHIN GROUP (ORDER BY residuals.residual),
                bool_and(residuals.eligible) AND count(residuals.residual) > 0,
                CASE
                    WHEN NOT bool_and(residuals.eligible) THEN min(residuals.gate_reason)
                    WHEN count(residuals.residual) = 0 THEN 'no_aligned_holdout_points'
                    ELSE 'passed'
                END
            FROM residuals
        $$;
