-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_derived_signal_snapshot_eligible(p_snapshot_id uuid) RETURNS TABLE(derived_value_id bigint, signal_definition_id uuid, signal_key character varying, series_key character varying, valid_time timestamp with time zone, origin_cutoff_time timestamp with time zone, availability_time timestamp with time zone, lineage_depth integer, signal_value double precision, value_checksum character varying)
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET search_path TO 'pg_catalog', 'agri'
    AS $$
        WITH RECURSIVE snapshot AS (
            -- The gate: only a validated snapshot admits anything, and its own training window end
            -- is the as-of every derived value and its whole ancestry must already satisfy.
            SELECT
                feature_snapshot.id,
                feature_snapshot.training_window_end AS as_of_time
            FROM agri.forecast_feature_snapshot AS feature_snapshot
            WHERE feature_snapshot.id = p_snapshot_id
              AND feature_snapshot.status = 'validated'
        ),
        ancestry AS (
            SELECT
                value.id AS root_id,
                value.id AS node_id,
                value.availability_time AS availability_time,
                0 AS traversal_depth
            FROM agri.forecast_derived_signal_value AS value
            CROSS JOIN snapshot
            UNION ALL
            SELECT
                ancestry.root_id,
                parent.id AS node_id,
                parent.availability_time AS availability_time,
                ancestry.traversal_depth + 1 AS traversal_depth
            FROM ancestry
            JOIN agri.forecast_signal_lineage_edge AS edge
                ON edge.child_value_id = ancestry.node_id
            JOIN agri.forecast_derived_signal_value AS parent
                ON parent.id = edge.parent_value_id
            WHERE ancestry.traversal_depth < 64
        ),
        admissible AS (
            SELECT
                ancestry.root_id,
                max(ancestry.availability_time) AS latest_ancestry_availability
            FROM ancestry
            GROUP BY ancestry.root_id
        )
        SELECT
            value.id AS derived_value_id,
            value.signal_definition_id AS signal_definition_id,
            definition.signal_key AS signal_key,
            value.series_key AS series_key,
            value.valid_time AS valid_time,
            value.origin_cutoff_time AS origin_cutoff_time,
            value.availability_time AS availability_time,
            value.lineage_depth AS lineage_depth,
            value.signal_value AS signal_value,
            value.value_checksum AS value_checksum
        FROM agri.forecast_derived_signal_value AS value
        JOIN agri.forecast_signal_definition AS definition
            ON definition.id = value.signal_definition_id
        JOIN admissible ON admissible.root_id = value.id
        CROSS JOIN snapshot
        WHERE admissible.latest_ancestry_availability <= snapshot.as_of_time
          AND value.evaluation_only
          AND definition.evaluation_only
          AND NOT definition.publication_authorized
        ORDER BY value.series_key, value.valid_time, value.id
    $$;
