-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_quantiles_valid(p_quantiles double precision[]) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$
            SELECT p_quantiles IS NOT NULL
               AND cardinality(p_quantiles) >= 1
               AND array_position(p_quantiles, NULL) IS NULL
               AND NOT EXISTS (
                    SELECT 1 FROM unnest(p_quantiles) AS quantile
                    WHERE quantile < 0 OR quantile > 1
               )
               AND (
                    SELECT count(*) = count(DISTINCT quantile)
                    FROM unnest(p_quantiles) AS quantile
               )
        $$;
