-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_date_spine(p_start_time timestamp with time zone, p_end_time timestamp with time zone, p_grain interval DEFAULT '1 day'::interval) RETURNS TABLE(grain_index integer, bucket_start timestamp with time zone, bucket_end timestamp with time zone)
    LANGUAGE plpgsql IMMUTABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        BEGIN
            IF p_grain <> interval '1 day' THEN
                RAISE EXCEPTION 'forecast date spine v1 supports exactly one-day UTC grain';
            END IF;
            IF p_start_time <> date_trunc('day', p_start_time AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
               OR p_end_time <> date_trunc('day', p_end_time AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' THEN
                RAISE EXCEPTION 'forecast date spine boundaries must be UTC day starts';
            END IF;
            IF p_end_time <= p_start_time THEN
                RAISE EXCEPTION 'forecast date spine window must be non-empty';
            END IF;

            RETURN QUERY
            SELECT
                generated.grain_index,
                p_start_time + make_interval(days => generated.grain_index),
                p_start_time + make_interval(days => generated.grain_index + 1)
            FROM generate_series(
                0,
                ((extract(epoch FROM (p_end_time - p_start_time)) / 86400)::integer - 1)
            ) AS generated(grain_index)
            ORDER BY generated.grain_index;
        END
        $$;
