-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_daily_bootstrap(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_cutoff_time timestamp with time zone, p_history_start timestamp with time zone DEFAULT NULL::timestamp with time zone, p_horizon_days integer DEFAULT 30, p_simulation_count integer DEFAULT 1000, p_seed bigint DEFAULT 0, p_gap_policy character varying DEFAULT 'strict'::character varying, p_lower_bound double precision DEFAULT NULL::double precision, p_upper_bound double precision DEFAULT NULL::double precision) RETURNS TABLE(horizon_step integer, valid_time timestamp with time zone, low_value double precision, median_value double precision, high_value double precision, increment_count integer, parameter_checksum text)
    LANGUAGE plpgsql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        DECLARE
            effective_history_start timestamptz;
            baseline_value double precision;
            available_increment_count integer;
            release_checksum text;
            series_contract_checksum text;
            aligned_history_checksum text;
            computed_parameter_checksum text;
        BEGIN
            IF p_cutoff_time <> date_trunc('day', p_cutoff_time AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
               OR (
                    p_history_start IS NOT NULL
                    AND p_history_start <>
                        date_trunc('day', p_history_start AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
               ) THEN
                RAISE EXCEPTION 'bootstrap cutoff and history start must be UTC day starts';
            END IF;
            IF p_cutoff_time > p_as_of_time THEN
                RAISE EXCEPTION 'bootstrap cutoff cannot be later than the as-of boundary';
            END IF;
            IF p_horizon_days < 1 OR p_horizon_days > 366 THEN
                RAISE EXCEPTION 'bootstrap horizon must be between 1 and 366 days';
            END IF;
            IF p_simulation_count < 100 OR p_simulation_count > 10000 THEN
                RAISE EXCEPTION 'bootstrap simulation count must be between 100 and 10000';
            END IF;
            IF p_as_of_time > clock_timestamp() THEN
                RAISE EXCEPTION 'bootstrap as-of boundary cannot be in the future';
            END IF;
            IF p_gap_policy NOT IN ('strict', 'locf') THEN
                RAISE EXCEPTION 'bootstrap gap policy must be strict or locf';
            END IF;
            IF p_lower_bound IS NOT NULL AND p_upper_bound IS NOT NULL
               AND p_lower_bound > p_upper_bound THEN
                RAISE EXCEPTION 'bootstrap lower bound cannot exceed upper bound';
            END IF;
            IF p_lower_bound::text IN ('NaN', 'Infinity', '-Infinity')
               OR p_upper_bound::text IN ('NaN', 'Infinity', '-Infinity') THEN
                RAISE EXCEPTION 'bootstrap bounds must be finite when supplied';
            END IF;

            SELECT release_set.manifest_checksum
              INTO release_checksum
              FROM agri.release_set AS release_set
             WHERE release_set.id = p_release_set_id
               AND release_set.state IN ('validated', 'published')
               AND release_set.validated_at <= p_as_of_time
               AND release_set.as_of_time <= p_as_of_time;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'bootstrap release set is not validated by the as-of boundary';
            END IF;

            SELECT contract.contract_checksum
              INTO series_contract_checksum
              FROM agri.v_forecast_timeseries_contract AS contract
             WHERE contract.series_id = p_series_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'bootstrap series % is not registered', p_series_id;
            END IF;

            SELECT coalesce(
                       p_history_start,
                       min(
                           date_trunc('day', contract.observed_at AT TIME ZONE 'UTC')
                               AT TIME ZONE 'UTC'
                       )
                   )
              INTO effective_history_start
              FROM agri.forecast_timeseries_contract(
                  p_release_set_id,
                  p_as_of_time
              ) AS contract
             WHERE contract.series_id = p_series_id
               AND contract.observed_at < p_cutoff_time + interval '1 day';
            IF effective_history_start IS NULL OR effective_history_start > p_cutoff_time THEN
                RAISE EXCEPTION 'bootstrap history is empty at the requested cutoff';
            END IF;

            SELECT aligned.metric_value
              INTO baseline_value
              FROM agri.forecast_aligned_daily_series(
                  p_series_id,
                  p_release_set_id,
                  p_as_of_time,
                  effective_history_start,
                  p_cutoff_time + interval '1 day',
                  p_gap_policy
              ) AS aligned
             WHERE aligned.bucket_start = p_cutoff_time
               AND NOT aligned.is_missing;
            IF baseline_value IS NULL THEN
                RAISE EXCEPTION 'bootstrap cutoff day has no eligible value under gap policy %', p_gap_policy;
            END IF;

            WITH aligned AS (
                SELECT *
                FROM agri.forecast_aligned_daily_series(
                    p_series_id,
                    p_release_set_id,
                    p_as_of_time,
                    effective_history_start,
                    p_cutoff_time + interval '1 day',
                    p_gap_policy
                )
            ),
            lagged AS (
                SELECT
                    bucket_start,
                    metric_value,
                    lag(bucket_start) OVER (ORDER BY bucket_start) AS previous_bucket,
                    lag(metric_value) OVER (ORDER BY bucket_start) AS previous_value
                FROM aligned
                WHERE NOT is_missing
            )
            SELECT count(*)::integer
              INTO available_increment_count
              FROM lagged
             WHERE previous_value IS NOT NULL
               AND bucket_start = previous_bucket + interval '1 day';
            IF available_increment_count < 2 THEN
                RAISE EXCEPTION 'bootstrap requires at least two consecutive daily increments';
            END IF;

            SELECT encode(
                       digest(
                           string_agg(
                               aligned.alignment_checksum,
                               '|'
                               ORDER BY aligned.bucket_start
                           ),
                           'sha256'
                       ),
                       'hex'
                   )
              INTO aligned_history_checksum
              FROM agri.forecast_aligned_daily_series(
                  p_series_id,
                  p_release_set_id,
                  p_as_of_time,
                  effective_history_start,
                  p_cutoff_time + interval '1 day',
                  p_gap_policy
              ) AS aligned;

            computed_parameter_checksum := encode(
                digest(
                    concat_ws(
                        '|',
                        'forecast_daily_bootstrap_v1',
                        p_series_id::text,
                        p_release_set_id::text,
                        release_checksum,
                        series_contract_checksum,
                        aligned_history_checksum,
                        p_as_of_time::text,
                        p_cutoff_time::text,
                        effective_history_start::text,
                        p_horizon_days::text,
                        p_simulation_count::text,
                        p_seed::text,
                        p_gap_policy,
                        coalesce(p_lower_bound::text, ''),
                        coalesce(p_upper_bound::text, ''),
                        'daily_mean',
                        'p10_p50_p90'
                    ),
                    'sha256'
                ),
                'hex'
            );

            RETURN QUERY
            WITH aligned AS (
                SELECT *
                FROM agri.forecast_aligned_daily_series(
                    p_series_id,
                    p_release_set_id,
                    p_as_of_time,
                    effective_history_start,
                    p_cutoff_time + interval '1 day',
                    p_gap_policy
                )
            ),
            lagged AS (
                SELECT
                    bucket_start,
                    metric_value,
                    lag(bucket_start) OVER (ORDER BY bucket_start) AS previous_bucket,
                    lag(metric_value) OVER (ORDER BY bucket_start) AS previous_value
                FROM aligned
                WHERE NOT is_missing
            ),
            increments AS (
                SELECT
                    row_number() OVER (ORDER BY bucket_start)::bigint AS increment_index,
                    metric_value - previous_value AS increment_value
                FROM lagged
                WHERE previous_value IS NOT NULL
                  AND bucket_start = previous_bucket + interval '1 day'
            ),
            sample_hashes AS (
                SELECT
                    simulation_id,
                    generated_horizon,
                    (
                        ('x' || substr(
                            encode(
                                digest(
                                    concat_ws(
                                        '|',
                                        'forecast_bootstrap_sample_v1',
                                        p_seed::text,
                                        p_series_id::text,
                                        p_release_set_id::text,
                                        computed_parameter_checksum,
                                        simulation_id::text,
                                        generated_horizon::text
                                    ),
                                    'sha256'
                                ),
                                'hex'
                            ),
                            1,
                            15
                        ))::bit(60)::bigint
                    ) AS sample_hash
                FROM generate_series(1, p_simulation_count) AS simulation(simulation_id)
                CROSS JOIN generate_series(1, p_horizon_days) AS horizon(generated_horizon)
            ),
            sampled AS (
                SELECT
                    sample_hashes.simulation_id,
                    sample_hashes.generated_horizon,
                    increments.increment_value
                FROM sample_hashes
                INNER JOIN increments
                  ON increments.increment_index =
                     1 + mod(sample_hashes.sample_hash, available_increment_count::bigint)
            ),
            paths AS (
                SELECT
                    sampled.simulation_id,
                    sampled.generated_horizon,
                    baseline_value
                        + sum(sampled.increment_value) OVER (
                            PARTITION BY sampled.simulation_id
                            ORDER BY sampled.generated_horizon
                            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                        ) AS path_value
                FROM sampled
            ),
            bounded AS (
                SELECT
                    paths.generated_horizon,
                    least(
                        coalesce(p_upper_bound, 'Infinity'::double precision),
                        greatest(
                            coalesce(p_lower_bound, '-Infinity'::double precision),
                            paths.path_value
                        )
                    ) AS path_value
                FROM paths
            )
            SELECT
                bounded.generated_horizon,
                p_cutoff_time + make_interval(days => bounded.generated_horizon),
                percentile_cont(0.1) WITHIN GROUP (ORDER BY bounded.path_value),
                percentile_cont(0.5) WITHIN GROUP (ORDER BY bounded.path_value),
                percentile_cont(0.9) WITHIN GROUP (ORDER BY bounded.path_value),
                available_increment_count,
                computed_parameter_checksum
            FROM bounded
            GROUP BY bounded.generated_horizon
            ORDER BY bounded.generated_horizon;
        END
        $$;
