-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_linear_backtest(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_cutoff_time timestamp with time zone, p_horizon_steps integer, p_step_interval interval, p_min_training_points integer DEFAULT 30) RETURNS TABLE(training_point_count bigint, backtest_point_count bigint, expected_point_count integer, mae double precision, rmse double precision, naive_rmse double precision, skill_score double precision, bias double precision, mape double precision, coverage_fraction double precision, eligible boolean, gate_reason text)
    LANGUAGE sql STABLE
    AS $$
            WITH predictions AS (
                SELECT *
                FROM agri.forecast_linear_regression(
                    p_series_id,
                    p_release_set_id,
                    p_as_of_time,
                    p_cutoff_time,
                    p_horizon_steps,
                    p_step_interval,
                    p_min_training_points
                )
            ),
            actuals AS (
                SELECT base.observed_at, base.metric_value
                FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                WHERE base.series_id = p_series_id
                  AND base.observed_at > p_cutoff_time
                  AND base.observed_at <= p_cutoff_time + (p_step_interval * p_horizon_steps)
            ),
            last_training AS (
                SELECT (
                    SELECT base.metric_value
                    FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                    WHERE base.series_id = p_series_id
                      AND base.observed_at <= p_cutoff_time
                    ORDER BY base.observed_at DESC, base.observation_id DESC
                    LIMIT 1
                ) AS naive_value
            ),
            compared AS (
                SELECT
                    prediction.training_point_count,
                    prediction.eligible,
                    prediction.gate_reason,
                    prediction.forecast_value,
                    actual.metric_value AS actual_value,
                    prediction.forecast_value - actual.metric_value AS error,
                    last_training.naive_value - actual.metric_value AS naive_error
                FROM predictions AS prediction
                CROSS JOIN last_training
                LEFT JOIN actuals AS actual ON actual.observed_at = prediction.valid_time
            ),
            aggregated AS (
                SELECT
                    max(compared.training_point_count) AS training_point_count,
                    count(compared.actual_value) AS backtest_point_count,
                    avg(abs(compared.error)) FILTER (WHERE compared.actual_value IS NOT NULL) AS mae,
                    sqrt(avg(compared.error * compared.error)
                        FILTER (WHERE compared.actual_value IS NOT NULL)) AS rmse,
                    sqrt(avg(compared.naive_error * compared.naive_error)
                        FILTER (WHERE compared.actual_value IS NOT NULL)) AS naive_rmse,
                    avg(compared.error) FILTER (WHERE compared.actual_value IS NOT NULL) AS bias,
                    avg(abs(compared.error / NULLIF(compared.actual_value, 0)))
                        FILTER (WHERE compared.actual_value IS NOT NULL AND compared.actual_value <> 0) AS mape,
                    bool_and(compared.eligible) AS regression_eligible,
                    min(compared.gate_reason) AS regression_gate_reason
                FROM compared
            )
            SELECT
                aggregated.training_point_count,
                aggregated.backtest_point_count,
                p_horizon_steps,
                aggregated.mae,
                aggregated.rmse,
                aggregated.naive_rmse,
                CASE
                    WHEN aggregated.naive_rmse IS NULL OR aggregated.naive_rmse = 0 THEN NULL
                    ELSE 1 - (aggregated.rmse / aggregated.naive_rmse)
                END,
                aggregated.bias,
                aggregated.mape,
                aggregated.backtest_point_count::double precision / p_horizon_steps,
                aggregated.regression_eligible AND aggregated.backtest_point_count > 0,
                CASE
                    WHEN NOT aggregated.regression_eligible THEN aggregated.regression_gate_reason
                    WHEN aggregated.backtest_point_count = 0 THEN 'no_aligned_holdout_points'
                    ELSE 'passed'
                END
            FROM aggregated
        $$;
