-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_hindcast_signal_timeseries(p_series_id uuid, p_model_id uuid, p_signal_kind character varying, p_horizon_step integer, p_as_of_time timestamp with time zone) RETURNS TABLE(observed_at timestamp with time zone, metric_value double precision, signal_kind text, hindcast_run_id uuid, simulated_cutoff_time timestamp with time zone, horizon_step integer, signal_available_at timestamp with time zone, receipt_checksum text, value_checksum text, quality_passed boolean)
    LANGUAGE sql STABLE
    AS $$
            SELECT
                outcome.valid_time,
                CASE p_signal_kind
                    WHEN 'forecast_point' THEN outcome.point_value
                    WHEN 'actual' THEN outcome.actual_value
                    WHEN 'residual_actual_minus_forecast' THEN outcome.residual_value
                    WHEN 'absolute_error' THEN outcome.absolute_error
                    WHEN 'squared_error' THEN outcome.squared_error
                    WHEN 'interval_covered' THEN CASE WHEN outcome.interval_covered THEN 1.0 ELSE 0.0 END
                END,
                p_signal_kind::text,
                outcome.hindcast_run_id,
                outcome.simulated_cutoff_time,
                outcome.horizon_step,
                outcome.signal_available_at,
                outcome.receipt_checksum::text,
                outcome.value_checksum::text,
                outcome.quality_passed
            FROM agri.v_forecast_hindcast_outcome AS outcome
            WHERE outcome.series_id = p_series_id
              AND outcome.model_id = p_model_id
              AND outcome.horizon_step = p_horizon_step
              AND outcome.signal_available_at <= p_as_of_time
              AND p_signal_kind IN (
                  'forecast_point', 'actual', 'residual_actual_minus_forecast',
                  'absolute_error', 'squared_error', 'interval_covered'
              )
            ORDER BY outcome.valid_time, outcome.hindcast_run_id
        $$;
