-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_linear_regression(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_cutoff_time timestamp with time zone, p_horizon_steps integer, p_step_interval interval, p_min_training_points integer DEFAULT 30) RETURNS TABLE(horizon_step integer, valid_time timestamp with time zone, forecast_value double precision, training_point_count bigint, slope_per_second double precision, intercept double precision, eligible boolean, gate_reason text)
    LANGUAGE plpgsql STABLE
    AS $$
        BEGIN
            IF p_horizon_steps < 1 OR p_horizon_steps > 10000 THEN
                RAISE EXCEPTION 'forecast horizon must be between 1 and 10000 steps';
            END IF;
            IF p_step_interval <= interval '0' THEN
                RAISE EXCEPTION 'forecast step interval must be positive';
            END IF;
            IF p_min_training_points < 3 THEN
                RAISE EXCEPTION 'linear regression requires at least three training points';
            END IF;

            RETURN QUERY
            WITH training AS (
                SELECT
                    extract(epoch FROM base.observed_at)::double precision AS x,
                    base.metric_value AS y
                FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                WHERE base.series_id = p_series_id
                  AND base.observed_at <= p_cutoff_time
            ),
            coefficients AS (
                SELECT
                    count(*) AS point_count,
                    count(DISTINCT x) AS distinct_time_count,
                    regr_slope(y, x) AS slope,
                    regr_intercept(y, x) AS intercept
                FROM training
            )
            SELECT
                step.step_number,
                p_cutoff_time + (p_step_interval * step.step_number),
                CASE
                    WHEN coefficients.point_count >= p_min_training_points
                     AND coefficients.distinct_time_count >= 2
                     AND coefficients.slope IS NOT NULL
                     AND coefficients.intercept IS NOT NULL
                    THEN coefficients.intercept
                       + coefficients.slope * extract(
                           epoch FROM p_cutoff_time + (p_step_interval * step.step_number)
                         )
                    ELSE NULL
                END,
                coefficients.point_count,
                coefficients.slope,
                coefficients.intercept,
                coefficients.point_count >= p_min_training_points
                    AND coefficients.distinct_time_count >= 2
                    AND coefficients.slope IS NOT NULL
                    AND coefficients.intercept IS NOT NULL,
                CASE
                    WHEN coefficients.point_count < p_min_training_points THEN 'insufficient_training_points'
                    WHEN coefficients.distinct_time_count < 2 THEN 'insufficient_distinct_timestamps'
                    WHEN coefficients.slope IS NULL OR coefficients.intercept IS NULL THEN 'singular_regression'
                    ELSE 'passed'
                END
            FROM coefficients
            CROSS JOIN generate_series(1, p_horizon_steps) AS step(step_number);
        END
        $$;
