-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_quality_policy_contract_v2(p_policy agri.forecast_quality_policy) RETURNS jsonb
    LANGUAGE sql STABLE
    SET extra_float_digits TO '1'
    AS $$
        SELECT jsonb_build_array(
            'plantgeo-forecast-quality-policy-v2',
            (p_policy.is_active)::text,
            (p_policy.min_training_points)::text,
            (p_policy.min_backtest_points)::text,
            (p_policy.min_coverage_fraction)::text,
            (p_policy.min_interval_coverage_fraction)::text,
            (p_policy.max_mae)::text,
            (p_policy.max_rmse)::text,
            (p_policy.max_mape)::text,
            (p_policy.min_skill_score)::text,
            to_jsonb(p_policy.required_quantiles)
        )
    $$;
