-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_hindcast_value_checksum(p_valid_time timestamp with time zone, p_horizon_step integer, p_point_value double precision, p_p10_value double precision, p_p50_value double precision, p_p90_value double precision, p_naive_value double precision, p_actual_value double precision, p_actual_source_release_id uuid, p_actual_observation_checksum character varying) RETURNS character varying
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
            SELECT encode(public.digest(concat_ws('|',
                to_char(p_valid_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
                p_horizon_step::text,
                p_point_value::text,
                p_p10_value::text,
                p_p50_value::text,
                p_p90_value::text,
                p_naive_value::text,
                p_actual_value::text,
                p_actual_source_release_id::text,
                p_actual_observation_checksum
            ), 'sha256'), 'hex')::varchar
        $$;
