-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_signal_lineage_audit(p_root_value_id bigint) RETURNS TABLE(root_value_id bigint, ancestor_count integer, traversed_depth integer, declared_max_depth integer, depth_bound_exceeded boolean, cycle_detected boolean, earliest_ancestor_availability timestamp with time zone, latest_ancestor_availability timestamp with time zone, root_origin_cutoff_time timestamp with time zone, availability_violation_count integer)
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET search_path TO 'pg_catalog', 'agri'
    AS $$
        WITH RECURSIVE root AS (
            SELECT
                value.id,
                value.origin_cutoff_time,
                value.availability_time,
                value.max_dependency_depth
            FROM agri.forecast_derived_signal_value AS value
            WHERE value.id = p_root_value_id
        ),
        walk AS (
            SELECT
                root.id AS value_id,
                0 AS traversal_depth,
                root.availability_time AS availability_time,
                ARRAY[root.id] AS visited
            FROM root
            UNION ALL
            SELECT
                parent.id AS value_id,
                walk.traversal_depth + 1 AS traversal_depth,
                parent.availability_time AS availability_time,
                walk.visited || parent.id AS visited
            FROM walk
            JOIN agri.forecast_signal_lineage_edge AS edge
                ON edge.child_value_id = walk.value_id
            JOIN agri.forecast_derived_signal_value AS parent
                ON parent.id = edge.parent_value_id
            -- The bound terminates the walk even on a graph that somehow held a cycle; the
            -- `visited` membership test is what turns that into a reported fact instead of a hang.
            WHERE walk.traversal_depth < 64
              AND NOT parent.id = ANY(walk.visited)
        ),
        cycle AS (
            SELECT count(*) AS cycle_edges
            FROM walk
            JOIN agri.forecast_signal_lineage_edge AS edge
                ON edge.child_value_id = walk.value_id
            WHERE edge.parent_value_id = ANY(walk.visited)
        )
        SELECT
            root.id AS root_value_id,
            (count(*) FILTER (WHERE walk.traversal_depth > 0))::integer AS ancestor_count,
            coalesce(max(walk.traversal_depth), 0)::integer AS traversed_depth,
            root.max_dependency_depth AS declared_max_depth,
            coalesce(max(walk.traversal_depth), 0) > root.max_dependency_depth AS depth_bound_exceeded,
            bool_or(cycle.cycle_edges > 0) AS cycle_detected,
            min(walk.availability_time) FILTER (WHERE walk.traversal_depth > 0) AS earliest_ancestor_availability,
            max(walk.availability_time) FILTER (WHERE walk.traversal_depth > 0) AS latest_ancestor_availability,
            root.origin_cutoff_time AS root_origin_cutoff_time,
            (count(*) FILTER (
                WHERE walk.traversal_depth > 0 AND walk.availability_time > root.origin_cutoff_time
            ))::integer AS availability_violation_count
        FROM root
        CROSS JOIN cycle
        LEFT JOIN walk ON true
        GROUP BY root.id, root.max_dependency_depth, root.origin_cutoff_time
    $$;
