-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_timeseries_contract(p_release_set_id uuid, p_as_of_time timestamp with time zone) RETURNS TABLE(observation_id bigint, series_id uuid, series_key text, source_variant_key text, input_adapter text, data_source_id uuid, data_source_key text, data_source_name text, data_source_owner text, data_source_review_state text, license_name text, license_url text, citation text, entity_type text, entity_key text, entity_state_id uuid, entity_state_checksum text, metric_name text, metric_unit text, observed_at timestamp with time zone, metric_value double precision, data_available_at timestamp with time zone, representation_kind text, spatial_support_kind text, source_spatial_resolution_m integer, output_spatial_resolution_m integer, source_temporal_support interval, desired_temporal_grain interval, aggregation_method text, spatial_cell_id uuid, source_release_id uuid, source_release_license_snapshot text, input_release_checksum text, observation_checksum text, series_metadata jsonb, contract_snapshot jsonb, contract_checksum text, contract_version text)
    LANGUAGE plpgsql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                INNER JOIN agri.v_forecast_timeseries_contract AS contract
                    ON contract.series_id = base.series_id
                WHERE base.spatial_support_kind IS DISTINCT FROM contract.spatial_support_kind
                   OR base.source_spatial_resolution_m
                        IS DISTINCT FROM contract.source_spatial_resolution_m
                   OR base.output_spatial_resolution_m
                        IS DISTINCT FROM contract.output_spatial_resolution_m
            ) THEN
                RAISE EXCEPTION
                    'governed source support conflicts with the registered forecast series contract';
            END IF;

            RETURN QUERY
            SELECT
                base.observation_id,
                contract.series_id,
                contract.series_key::text,
                contract.source_variant_key::text,
                contract.input_adapter::text,
                contract.data_source_id,
                contract.data_source_key::text,
                contract.data_source_name::text,
                contract.data_source_owner::text,
                contract.data_source_review_state::text,
                contract.license_name::text,
                contract.license_url::text,
                contract.citation::text,
                contract.entity_type::text,
                contract.entity_key::text,
                base.entity_state_id,
                base.entity_state_checksum,
                contract.metric_name::text,
                contract.metric_unit::text,
                base.observed_at,
                base.metric_value,
                greatest(
                    source_release.data_available_at,
                    source_release_record.recorded_at,
                    coalesce(observation.data_available_at, source_release.data_available_at),
                    coalesce(signal_observation.data_available_at, source_release.data_available_at),
                    coalesce(entity_state.data_available_at, source_release.data_available_at),
                    release_set.as_of_time,
                    release_set.validated_at,
                    release_set_record.recorded_at,
                    contract.data_source_recorded_at::timestamptz,
                    contract.contract_recorded_at::timestamptz
                ),
                base.representation_kind::text,
                base.spatial_support_kind::text,
                base.source_spatial_resolution_m,
                base.output_spatial_resolution_m,
                base.source_temporal_support,
                base.output_temporal_support,
                contract.aggregation_method::text,
                base.spatial_cell_id,
                base.source_release_id,
                source_release.license_snapshot::text,
                base.input_release_checksum,
                base.observation_checksum,
                contract.metadata_json,
                contract.contract_snapshot,
                contract.contract_checksum,
                contract.contract_version
            FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
            INNER JOIN agri.v_forecast_timeseries_contract AS contract
                ON contract.series_id = base.series_id
            INNER JOIN agri.source_release AS source_release
                ON source_release.id = base.source_release_id
            INNER JOIN agri.forecast_input_recorded_at AS source_release_record
                ON source_release_record.input_kind = 'source_release'
               AND source_release_record.input_key = source_release.id::text
            INNER JOIN agri.release_set AS release_set
                ON release_set.id = p_release_set_id
            INNER JOIN agri.forecast_input_recorded_at AS release_set_record
                ON release_set_record.input_kind = 'release_set'
               AND release_set_record.input_key = release_set.id::text
            LEFT JOIN agri.forecast_observation AS observation
                ON observation.id = base.observation_id
            LEFT JOIN agri.forecast_entity_state AS entity_state
                ON entity_state.id = base.entity_state_id
            LEFT JOIN agri.signal_observation AS signal_observation
                ON contract.input_adapter = 'signal_observation'
               AND signal_observation.source_release_id = base.source_release_id
               AND signal_observation.cell_id = base.spatial_cell_id
               AND signal_observation.signal_name = contract.signal_name
               AND signal_observation.source_parameter = contract.source_parameter
               AND signal_observation.support_key = contract.support_key
               AND signal_observation.observed_at = base.observed_at
               AND signal_observation.normalized_value IS NOT DISTINCT FROM base.metric_value
            WHERE source_release_record.recorded_at <= p_as_of_time
              AND release_set_record.recorded_at <= p_as_of_time
              AND contract.data_source_recorded_at::timestamptz <= p_as_of_time
              AND contract.contract_recorded_at::timestamptz <= p_as_of_time
              AND (
                    contract.input_adapter <> 'signal_observation'
                    OR signal_observation.id IS NOT NULL
              )
              AND (
                    contract.input_adapter <> 'forecast_observation'
                    OR observation.id IS NOT NULL
              );
        END
        $$;
