-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_percentile(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_window_start timestamp with time zone, p_window_end timestamp with time zone, p_percentile double precision) RETURNS double precision
    LANGUAGE plpgsql STABLE
    AS $$
        DECLARE
            result_value double precision;
        BEGIN
            IF p_percentile < 0 OR p_percentile > 1 THEN
                RAISE EXCEPTION 'percentile must be between zero and one';
            END IF;
            IF p_window_end <= p_window_start THEN
                RAISE EXCEPTION 'percentile window must be non-empty';
            END IF;

            SELECT percentile_cont(p_percentile) WITHIN GROUP (ORDER BY base.metric_value)
              INTO result_value
              FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
             WHERE base.series_id = p_series_id
               AND base.observed_at >= p_window_start
               AND base.observed_at < p_window_end;
            RETURN result_value;
        END
        $$;
