-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_rolling_stats(p_series_id uuid, p_release_set_id uuid, p_as_of_time timestamp with time zone, p_window_rows integer DEFAULT 30) RETURNS TABLE(observed_at timestamp with time zone, metric_value double precision, sample_count bigint, rolling_mean double precision, rolling_stddev double precision, rolling_p10 double precision, rolling_p50 double precision, rolling_p90 double precision)
    LANGUAGE plpgsql STABLE
    AS $$
        BEGIN
            IF p_window_rows < 2 OR p_window_rows > 10000 THEN
                RAISE EXCEPTION 'rolling window rows must be between 2 and 10000';
            END IF;

            RETURN QUERY
            WITH ordered AS (
                SELECT
                    base.observed_at,
                    base.metric_value,
                    row_number() OVER (ORDER BY base.observed_at, base.observation_id) AS row_number
                FROM agri.forecast_timeseries_base(p_release_set_id, p_as_of_time) AS base
                WHERE base.series_id = p_series_id
            )
            SELECT
                current_row.observed_at,
                current_row.metric_value,
                window_stats.sample_count,
                window_stats.rolling_mean,
                window_stats.rolling_stddev,
                window_stats.rolling_p10,
                window_stats.rolling_p50,
                window_stats.rolling_p90
            FROM ordered AS current_row
            CROSS JOIN LATERAL (
                SELECT
                    count(*) AS sample_count,
                    avg(window_row.metric_value) AS rolling_mean,
                    stddev_samp(window_row.metric_value) AS rolling_stddev,
                    percentile_cont(0.1) WITHIN GROUP (ORDER BY window_row.metric_value) AS rolling_p10,
                    percentile_cont(0.5) WITHIN GROUP (ORDER BY window_row.metric_value) AS rolling_p50,
                    percentile_cont(0.9) WITHIN GROUP (ORDER BY window_row.metric_value) AS rolling_p90
                FROM ordered AS window_row
                WHERE window_row.row_number BETWEEN
                    greatest(1, current_row.row_number - p_window_rows + 1)
                    AND current_row.row_number
            ) AS window_stats
            ORDER BY current_row.observed_at;
        END
        $$;
