-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.forecast_iteration_signal_timeseries(p_series_id uuid, p_signal_kind character varying, p_horizon_step integer, p_as_of_time timestamp with time zone) RETURNS TABLE(observed_at timestamp with time zone, metric_value double precision, signal_kind text, iteration_id uuid, cutoff_time timestamp with time zone, horizon_step integer, signal_available_at timestamp with time zone, receipt_checksum text, value_checksum text, actual_checksum text)
    LANGUAGE sql STABLE
    AS $$
            SELECT
                outcome.valid_time,
                CASE p_signal_kind
                    WHEN 'forecast_low' THEN outcome.low_value
                    WHEN 'forecast_median' THEN outcome.median_value
                    WHEN 'forecast_high' THEN outcome.high_value
                    WHEN 'actual' THEN outcome.actual_value
                    WHEN 'residual_actual_minus_forecast' THEN
                        outcome.residual_actual_minus_forecast
                    WHEN 'forecast_error' THEN outcome.forecast_error
                    WHEN 'absolute_error' THEN outcome.absolute_error
                    WHEN 'squared_error' THEN outcome.squared_error
                    WHEN 'interval_covered' THEN
                        CASE WHEN outcome.interval_covered THEN 1.0 ELSE 0.0 END
                END,
                p_signal_kind::text,
                outcome.iteration_id,
                outcome.cutoff_time,
                outcome.horizon_step,
                CASE
                    WHEN p_signal_kind IN (
                        'actual',
                        'residual_actual_minus_forecast',
                        'forecast_error',
                        'absolute_error',
                        'squared_error',
                        'interval_covered'
                    ) THEN outcome.actual_recorded_at
                    ELSE outcome.forecast_available_at
                END,
                outcome.receipt_checksum::text,
                outcome.value_checksum::text,
                outcome.actual_checksum::text
            FROM agri.v_forecast_iteration_outcome AS outcome
            WHERE outcome.series_id = p_series_id
              AND outcome.horizon_step = p_horizon_step
              AND p_signal_kind IN (
                  'forecast_low',
                  'forecast_median',
                  'forecast_high',
                  'actual',
                  'residual_actual_minus_forecast',
                  'forecast_error',
                  'absolute_error',
                  'squared_error',
                  'interval_covered'
              )
              AND CASE
                    WHEN p_signal_kind IN (
                        'actual',
                        'residual_actual_minus_forecast',
                        'forecast_error',
                        'absolute_error',
                        'squared_error',
                        'interval_covered'
                    ) THEN
                        outcome.actual_recorded_at IS NOT NULL
                        AND outcome.actual_recorded_at <= p_as_of_time
                    ELSE outcome.forecast_available_at <= p_as_of_time
                  END
            ORDER BY outcome.valid_time, outcome.iteration_id
        $$;
