-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_forecast_iteration_actual_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'forecast iteration actual evidence is append-only';
            END IF;
            IF TG_TABLE_NAME = 'forecast_iteration_actual'
               AND NEW.actual_digest_version <> 'forecast_iteration_actual_v2' THEN
                RAISE EXCEPTION 'new forecast iteration actuals require digest version v2';
            END IF;
            RETURN NEW;
        END
        $$;
