-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_forecast_quality_policy_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM agri.forecast_run AS parent
                INNER JOIN agri.forecast_hindcast_run AS hindcast
                    ON hindcast.forecast_run_id = parent.id
                WHERE parent.quality_policy_id = OLD.id
                  AND hindcast.status = 'finalized'
            ) THEN
                RAISE EXCEPTION
                    'quality policies referenced by finalized hindcast receipts are immutable';
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END
        $$;
