-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_forecast_hindcast_run_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF TG_OP = 'DELETE' OR OLD.status = 'finalized' THEN
                RAISE EXCEPTION 'finalized hindcast runs are immutable';
            END IF;
            IF ROW(
                NEW.id, NEW.hindcast_key, NEW.forecast_run_id, NEW.series_id,
                NEW.release_set_id, NEW.simulated_cutoff_time,
                NEW.uncertainty_calibration_cutoff_time, NEW.horizon_steps,
                NEW.step_interval, NEW.minimum_training_points, NEW.training_point_count,
                NEW.expected_value_count,
                NEW.availability_mode, NEW.input_release_checksum, NEW.model_checksum,
                NEW.parameter_checksum, NEW.receipt_digest_version, NEW.created_at
            ) IS DISTINCT FROM ROW(
                OLD.id, OLD.hindcast_key, OLD.forecast_run_id, OLD.series_id,
                OLD.release_set_id, OLD.simulated_cutoff_time,
                OLD.uncertainty_calibration_cutoff_time, OLD.horizon_steps,
                OLD.step_interval, OLD.minimum_training_points, OLD.training_point_count,
                OLD.expected_value_count,
                OLD.availability_mode, OLD.input_release_checksum, OLD.model_checksum,
                OLD.parameter_checksum, OLD.receipt_digest_version, OLD.created_at
            ) OR NEW.status <> 'finalized' THEN
                RAISE EXCEPTION 'hindcast identity is immutable and only finalization may update a staged run';
            END IF;
            RETURN NEW;
        END
        $$;
