-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_forecast_value_write() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE receipt_status varchar;
        BEGIN
            SELECT status INTO receipt_status
              FROM agri.forecast_receipt
             WHERE id = coalesce(NEW.forecast_receipt_id, OLD.forecast_receipt_id)
             FOR SHARE;
            IF TG_OP = 'INSERT' AND receipt_status = 'staging' THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'forecast values are writable only while their receipt is staging';
        END
        $$;
