-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_forecast_terminal_lineage() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF TG_OP = 'DELETE' OR OLD.status IN ('validated', 'rejected') THEN
                RAISE EXCEPTION 'terminal % rows are immutable', TG_TABLE_NAME;
            END IF;
            RETURN NEW;
        END
        $$;
