-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_strategy_review_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF TG_OP = 'DELETE'
               OR OLD.review_state <> 'draft'
               OR NEW.review_state NOT IN ('approved', 'rejected')
               OR NEW.reviewed_at IS NULL
               OR NEW.reviewed_by IS NULL THEN
                RAISE EXCEPTION '% permits only an immutable draft-to-reviewed transition', TG_TABLE_NAME;
            END IF;

            IF TG_TABLE_NAME = 'strategy_outcome_definition' THEN
                IF (
                    to_jsonb(NEW)
                    - 'review_state'
                    - 'reviewed_at'
                    - 'reviewed_by'
                    - 'definition_checksum'
                ) IS DISTINCT FROM (
                    to_jsonb(OLD)
                    - 'review_state'
                    - 'reviewed_at'
                    - 'reviewed_by'
                    - 'definition_checksum'
                ) THEN
                    RAISE EXCEPTION 'outcome review cannot alter draft semantics';
                END IF;
                NEW.definition_checksum :=
                    agri.strategy_outcome_definition_checksum(NEW);
            ELSIF TG_TABLE_NAME = 'strategy_selection_policy' THEN
                IF (
                    to_jsonb(NEW)
                    - 'review_state'
                    - 'reviewed_at'
                    - 'reviewed_by'
                    - 'policy_checksum'
                ) IS DISTINCT FROM (
                    to_jsonb(OLD)
                    - 'review_state'
                    - 'reviewed_at'
                    - 'reviewed_by'
                    - 'policy_checksum'
                ) THEN
                    RAISE EXCEPTION 'selection-policy review cannot alter draft thresholds';
                END IF;
                NEW.policy_checksum :=
                    agri.strategy_selection_policy_checksum(NEW);
            ELSE
                RAISE EXCEPTION 'unsupported strategy review table: %', TG_TABLE_NAME;
            END IF;
            RETURN NEW;
        END
    $$;
