-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.guard_strategy_child_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            parent_status varchar;
        BEGIN
            IF TG_TABLE_NAME = 'strategy_label_episode' THEN
                SELECT status INTO parent_status
                  FROM agri.strategy_label_release
                 WHERE id = NEW.label_release_id
                 FOR UPDATE;
                IF parent_status IS DISTINCT FROM 'staging' THEN
                    RAISE EXCEPTION 'strategy label episodes require a staging label release';
                END IF;
            ELSIF TG_TABLE_NAME = 'strategy_selection_candidate' THEN
                SELECT status INTO parent_status
                  FROM agri.strategy_selection_receipt
                 WHERE id = NEW.selection_receipt_id
                 FOR UPDATE;
                IF parent_status IS DISTINCT FROM 'staging' THEN
                    RAISE EXCEPTION 'strategy selection candidates require a staging receipt';
                END IF;
            ELSE
                RAISE EXCEPTION 'unsupported strategy child-insert trigger table: %', TG_TABLE_NAME;
            END IF;
            RETURN NEW;
        END
    $$;
