-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.publish_forecast_publication(p_publication_id uuid, p_expected_manifest_checksum character varying) RETURNS agri.forecast_publication
    LANGUAGE plpgsql
    AS $_$
        DECLARE
            publication agri.forecast_publication;
            item_count integer;
            invalid_count integer;
            actual_checksum varchar;
            output_state varchar;
            output_run_id uuid;
            output_checksum varchar;
            output_row_count bigint;
            mismatched_release_count integer;
        BEGIN
            IF p_expected_manifest_checksum !~ '^[0-9a-f]{64}$' THEN
                RAISE EXCEPTION 'publication manifest checksum must be SHA-256';
            END IF;
            SELECT * INTO publication
              FROM agri.forecast_publication
             WHERE id = p_publication_id
             FOR UPDATE;
            IF NOT FOUND OR publication.state NOT IN ('draft', 'published') THEN
                RAISE EXCEPTION 'forecast publication is missing or not eligible for publication';
            END IF;

            SELECT
                count(*),
                count(*) FILTER (WHERE receipt.status <> 'finalized'),
                count(*) FILTER (WHERE snapshot.release_set_id <> publication.release_set_id),
                encode(
                    digest(
                        coalesce(string_agg(receipt.receipt_checksum, E'\n' ORDER BY receipt.receipt_checksum), ''),
                        'sha256'
                    ),
                    'hex'
                )
              INTO item_count, invalid_count, mismatched_release_count, actual_checksum
              FROM agri.forecast_publication_item AS item
              INNER JOIN agri.forecast_receipt AS receipt ON receipt.id = item.forecast_receipt_id
              INNER JOIN agri.forecast_run AS run ON run.id = receipt.forecast_run_id
              INNER JOIN agri.forecast_feature_snapshot AS snapshot ON snapshot.id = run.feature_snapshot_id
             WHERE item.publication_id = publication.id;
            IF item_count = 0 OR invalid_count > 0 OR mismatched_release_count > 0 THEN
                RAISE EXCEPTION 'forecast publication requires finalized receipts';
            END IF;
            IF actual_checksum <> p_expected_manifest_checksum THEN
                RAISE EXCEPTION 'forecast publication manifest checksum mismatch';
            END IF;
            SELECT state, job_run_id, checksum_sha256, row_count
              INTO output_state, output_run_id, output_checksum, output_row_count
              FROM agri.job_output
             WHERE id = publication.job_output_id;
            IF output_state NOT IN ('validated', 'published')
               OR output_run_id <> publication.job_run_id
               OR output_checksum <> actual_checksum
               OR output_row_count IS NULL
               OR output_row_count <> item_count THEN
                RAISE EXCEPTION 'forecast publication job output lineage mismatch';
            END IF;
            IF publication.release_set_id <> (
                SELECT release_set_id FROM agri.job_run WHERE id = publication.job_run_id
            ) THEN
                RAISE EXCEPTION 'forecast publication release set does not match its job';
            END IF;

            IF publication.state = 'draft' THEN
                UPDATE agri.forecast_publication
                   SET state = 'published', manifest_checksum = actual_checksum, published_at = now()
                 WHERE id = publication.id
                 RETURNING * INTO publication;
            ELSIF publication.manifest_checksum <> actual_checksum THEN
                RAISE EXCEPTION 'published forecast manifest checksum changed';
            END IF;
            RETURN publication;
        END
        $_$;
