-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.record_forecast_input_change() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'agri'
    AS $$
        BEGIN
            INSERT INTO agri.forecast_input_recorded_at(
                input_kind,
                input_key,
                recorded_at
            )
            VALUES (TG_TABLE_NAME, NEW.id::text, clock_timestamp())
            ON CONFLICT (input_kind, input_key) DO UPDATE
                SET recorded_at = EXCLUDED.recorded_at;
            RETURN NEW;
        END
        $$;
