-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.require_initial_forecast_state() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE initial_state text;
        BEGIN
            initial_state := coalesce(to_jsonb(NEW) ->> 'status', to_jsonb(NEW) ->> 'state');
            IF (TG_TABLE_NAME = 'forecast_feature_snapshot' AND initial_state <> 'draft')
               OR (TG_TABLE_NAME = 'forecast_training_run' AND initial_state <> 'gated')
               OR (TG_TABLE_NAME = 'forecast_run' AND initial_state <> 'staged')
               OR (TG_TABLE_NAME = 'forecast_receipt' AND initial_state <> 'staging')
               OR (TG_TABLE_NAME = 'forecast_publication' AND initial_state <> 'draft') THEN
                RAISE EXCEPTION '% must be inserted in its non-terminal initial state', TG_TABLE_NAME;
            END IF;
            RETURN NEW;
        END
        $$;
