-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.require_strategy_initial_state() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF TG_TABLE_NAME = 'strategy_outcome_definition' THEN
                IF NEW.review_state <> 'draft'
                   OR NEW.reviewed_at IS NOT NULL
                   OR NEW.reviewed_by IS NOT NULL
                   OR NEW.definition_checksum IS NOT NULL THEN
                    RAISE EXCEPTION 'strategy_outcome_definition must be inserted as an unhashed draft';
                END IF;
            ELSIF TG_TABLE_NAME = 'strategy_selection_policy' THEN
                IF NEW.review_state <> 'draft'
                   OR NEW.reviewed_at IS NOT NULL
                   OR NEW.reviewed_by IS NOT NULL
                   OR NEW.policy_checksum IS NOT NULL THEN
                    RAISE EXCEPTION 'strategy_selection_policy must be inserted as an unhashed draft';
                END IF;
            ELSIF TG_TABLE_NAME = 'strategy_label_release' THEN
                IF NEW.status <> 'staging'
                   OR NEW.receipt_checksum IS NOT NULL
                   OR NEW.validated_at IS NOT NULL THEN
                    RAISE EXCEPTION 'strategy_label_release must be inserted in staging state';
                END IF;
            ELSIF TG_TABLE_NAME = 'strategy_selection_receipt' THEN
                IF NEW.status <> 'staging'
                   OR NEW.receipt_checksum IS NOT NULL
                   OR NEW.finalized_at IS NOT NULL
                   OR NEW.audit_state <> 'clear'
                   OR NEW.audit_reason IS NOT NULL
                   OR NEW.audit_flagged_at IS NOT NULL THEN
                    RAISE EXCEPTION 'strategy_selection_receipt must be inserted in staging state';
                END IF;
            ELSE
                RAISE EXCEPTION 'unsupported strategy initial-state trigger table: %', TG_TABLE_NAME;
            END IF;
            RETURN NEW;
        END
    $$;
