-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_selection_policy_checksum(p_policy agri.strategy_selection_policy) RETURNS character varying
    LANGUAGE sql IMMUTABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        SELECT encode(
            digest(
                concat_ws(
                    '|',
                    'strategy_selection_policy_v1',
                    (p_policy).policy_key,
                    (p_policy).policy_version,
                    (p_policy).min_treated_per_strategy::text,
                    (p_policy).min_control_count::text,
                    (p_policy).min_spatial_blocks::text,
                    (p_policy).min_effective_sample_size::text,
                    (p_policy).min_overlap_score::text,
                    (p_policy).max_weighted_smd::text,
                    (p_policy).min_coverage_fraction::text,
                    (p_policy).max_data_age::text,
                    (p_policy).min_conservative_value_gain::text,
                    (p_policy).max_model_disagreement::text,
                    (p_policy).max_ood_score::text,
                    (p_policy).score_weights::text,
                    (p_policy).allow_effect_claims::text
                ),
                'sha256'
            ),
            'hex'
        )::varchar
    $$;
