-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_outcome_definition_checksum(p_definition agri.strategy_outcome_definition) RETURNS character varying
    LANGUAGE sql IMMUTABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    SET search_path TO 'public', 'pg_catalog'
    AS $$
        SELECT encode(
            digest(
                concat_ws(
                    '|',
                    'strategy_outcome_definition_v1',
                    (p_definition).definition_key,
                    (p_definition).definition_version,
                    (p_definition).metric_name,
                    (p_definition).metric_unit,
                    (p_definition).benefit_direction,
                    (p_definition).smallest_meaningful_effect::text,
                    (p_definition).baseline_window::text,
                    (p_definition).outcome_window::text,
                    (p_definition).aggregation_method,
                    (p_definition).transform_method,
                    (p_definition).eligibility_policy::text
                ),
                'sha256'
            ),
            'hex'
        )::varchar
    $$;
