-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_label_bundle_checksum(p_label_release_id uuid) RETURNS character varying
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET extra_float_digits TO '1'
    AS $$
        SELECT encode(
            public.digest(
                agri.export_strategy_label_bundle(p_label_release_id)::text,
                'sha256'
            ),
            'hex'
        )::varchar
    $$;
