-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_selection_candidate_checksum(p_candidate_id uuid) RETURNS character varying
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    SET search_path TO 'public', 'pg_catalog'
    AS $$
        SELECT encode(
            digest(
                concat_ws(
                    '|',
                    'strategy_selection_candidate_v1',
                    candidate.selection_receipt_id::text,
                    candidate.strategy_id::text,
                    candidate.strategy_snapshot::text,
                    candidate.strategy_snapshot_checksum,
                    candidate.eligibility_state,
                    coalesce(candidate.exclusion_reason, ''),
                    coalesce(candidate.predicted_control_outcome::text, ''),
                    coalesce(candidate.predicted_strategy_outcome::text, ''),
                    coalesce(candidate.expected_effect::text, ''),
                    coalesce(candidate.effect_lower_bound::text, ''),
                    coalesce(candidate.effect_upper_bound::text, ''),
                    coalesce(candidate.overlap_score::text, ''),
                    coalesce(candidate.effective_sample_size::text, ''),
                    coalesce(candidate.weighted_smd::text, ''),
                    coalesce(candidate.coverage_fraction::text, ''),
                    coalesce(candidate.model_disagreement::text, ''),
                    coalesce(candidate.ood_score::text, ''),
                    coalesce(candidate.conservative_score::text, ''),
                    coalesce(candidate.rank::text, ''),
                    candidate.evidence_tier,
                    candidate.score_components::text
                ),
                'sha256'
            ),
            'hex'
        )::varchar
        FROM agri.strategy_selection_candidate AS candidate
        WHERE candidate.id = p_candidate_id
    $$;
