-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_selection_quality_evidence(p_selection_receipt_id uuid) RETURNS boolean
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    AS $$
        SELECT EXISTS (
            SELECT 1
              FROM agri.strategy_selection_receipt AS receipt
              INNER JOIN agri.forecast_iteration AS iteration
                  ON iteration.id = receipt.forecast_iteration_id
              INNER JOIN agri.v_forecast_hindcast_outcome AS outcome
                  ON outcome.series_id = iteration.series_id
             WHERE receipt.id = p_selection_receipt_id
               AND outcome.quality_passed
               AND outcome.simulated_cutoff_time <= receipt.data_cutoff
               AND outcome.signal_available_at <= receipt.issue_time
        ) OR EXISTS (
            SELECT 1
              FROM agri.strategy_selection_receipt AS receipt
              INNER JOIN agri.forecast_receipt AS forecast
                  ON forecast.id = receipt.forecast_receipt_id
              INNER JOIN agri.forecast_run AS run
                  ON run.id = forecast.forecast_run_id
              INNER JOIN agri.v_forecast_hindcast_outcome AS outcome
                  ON outcome.series_id = forecast.series_id
                 AND outcome.model_id = run.model_id
             WHERE receipt.id = p_selection_receipt_id
               AND outcome.quality_passed
               AND outcome.simulated_cutoff_time <= receipt.data_cutoff
               AND outcome.signal_available_at <= receipt.issue_time
        )
    $$;
