-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_selection_cutoff_violation(p_selection_receipt_id uuid) RETURNS boolean
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    AS $$
        SELECT EXISTS (
            SELECT 1
              FROM agri.strategy_selection_receipt AS receipt
              INNER JOIN agri.forecast_iteration AS iteration
                  ON iteration.id = receipt.forecast_iteration_id
             WHERE receipt.id = p_selection_receipt_id
               AND iteration.cutoff_time > receipt.data_cutoff
        )
    $$;
