-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.strategy_label_release_checksum(p_label_release_id uuid) RETURNS character varying
    LANGUAGE sql STABLE
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        SELECT encode(
            digest(
                concat_ws(
                    '|',
                    'strategy_label_release_v1',
                    label.release_key,
                    label.release_set_id::text,
                    label.outcome_definition_id::text,
                    label.as_of_time::text,
                    label.strategy_taxonomy_snapshot::text,
                    label.strategy_taxonomy_checksum,
                    label.feature_schema::text,
                    label.feature_schema_checksum,
                    label.extraction_plan_checksum,
                    label.extraction_code_checksum,
                    label.spatial_block_scheme,
                    label.row_count::text,
                    label.treated_count::text,
                    label.control_count::text,
                    label.strategy_count::text,
                    label.spatial_block_count::text,
                    outcome.definition_checksum,
                    string_agg(episode.episode_checksum, '|' ORDER BY episode.episode_key)
                ),
                'sha256'
            ),
            'hex'
        )::varchar
        FROM agri.strategy_label_release AS label
        INNER JOIN agri.strategy_outcome_definition AS outcome
            ON outcome.id = label.outcome_definition_id
        INNER JOIN agri.strategy_label_episode AS episode
            ON episode.label_release_id = label.id
        WHERE label.id = p_label_release_id
        GROUP BY label.id, outcome.definition_checksum
    $$;
