-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.v_signal_timeseries_contract(p_as_of_time timestamp with time zone, p_release_set_id uuid) RETURNS TABLE(cell_id uuid, signal_name text, source_parameter text, support_key text, observed_at timestamp with time zone, valid_from timestamp with time zone, valid_to timestamp with time zone, original_value double precision, original_unit text, normalized_value double precision, normalized_unit text, quality_flag text, coverage_fraction double precision, is_observed boolean, source_release_id uuid, data_available_at timestamp with time zone, transform_version text, grid_name text, analysis_resolution_m integer, spatial_support_kind text, native_resolution_m integer, mapping_method text, mapping_coverage_fraction double precision, is_acre_scale_compatible boolean)
    LANGUAGE sql STABLE
    AS $$
            SELECT
                observation.cell_id,
                observation.signal_name,
                observation.source_parameter,
                observation.support_key,
                observation.observed_at,
                observation.valid_from,
                observation.valid_to,
                observation.original_value,
                observation.original_unit,
                observation.normalized_value,
                observation.normalized_unit,
                observation.quality_flag,
                observation.coverage_fraction,
                observation.is_observed,
                observation.source_release_id,
                observation.data_available_at,
                source_release.transform_version,
                spatial_cell.grid_name,
                spatial_cell.resolution_m,
                source_support.spatial_support_kind,
                source_support.native_resolution_m,
                source_support.mapping_method,
                source_support.coverage_fraction,
                source_support.spatial_support_kind = 'native_grid_cell'
                    AND source_support.native_resolution_m <= 64
                    AND source_support.coverage_fraction = 1
                    AND observation.coverage_fraction = 1 AS is_acre_scale_compatible
            FROM agri.signal_observation AS observation
            INNER JOIN agri.source_release AS source_release
                ON source_release.id = observation.source_release_id
            INNER JOIN agri.spatial_cell AS spatial_cell
                ON spatial_cell.id = observation.cell_id
            INNER JOIN LATERAL (
                SELECT
                    count(*)::integer AS crosswalk_count,
                    min(crosswalk.spatial_support_kind) AS spatial_support_kind,
                    min(crosswalk.native_resolution_m) AS native_resolution_m,
                    min(crosswalk.mapping_method) AS mapping_method,
                    min(crosswalk.coverage_fraction) AS coverage_fraction
                FROM agri.cell_source_crosswalk AS crosswalk
                WHERE crosswalk.source_release_id = observation.source_release_id
                  AND crosswalk.cell_id = observation.cell_id
            ) AS source_support
                ON source_support.crosswalk_count = 1
            INNER JOIN agri.release_set_item AS member
                ON member.source_release_id = source_release.id
            INNER JOIN agri.release_set AS release_set
                ON release_set.id = member.release_set_id
            WHERE release_set.id = p_release_set_id
              AND release_set.state IN ('validated', 'published')
              AND release_set.as_of_time <= p_as_of_time
              AND release_set.validated_at <= p_as_of_time
              AND source_release.validation_state = 'valid'
              AND source_release.data_available_at <= p_as_of_time
              AND observation.data_available_at <= p_as_of_time
        $$;
