-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.verify_forecast_iteration_finalization() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            value_count integer;
            minimum_horizon integer;
            maximum_horizon integer;
            expected_checksum varchar;
        BEGIN
            IF NEW.status = 'finalized' AND OLD.status <> 'finalized' THEN
                SELECT count(*), min(horizon_step), max(horizon_step)
                  INTO value_count, minimum_horizon, maximum_horizon
                  FROM agri.forecast_iteration_value
                 WHERE iteration_id = NEW.id;
                IF value_count <> NEW.expected_value_count
                   OR minimum_horizon <> 1
                   OR maximum_horizon <> NEW.horizon_days THEN
                    RAISE EXCEPTION 'forecast iteration value extent is incomplete';
                END IF;
                expected_checksum := agri.forecast_iteration_receipt_checksum(NEW.id);
                IF expected_checksum IS DISTINCT FROM NEW.receipt_checksum THEN
                    RAISE EXCEPTION 'forecast iteration receipt checksum mismatch';
                END IF;
            END IF;
            RETURN NEW;
        END
        $$;
