-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.verify_forecast_hindcast_finalization() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF NEW.status = 'finalized' AND OLD.status <> 'finalized' THEN
                PERFORM agri.finalize_forecast_hindcast_run(NEW.id, NEW.receipt_checksum);
            END IF;
            RETURN NEW;
        END
        $$;
