-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE FUNCTION agri.verify_forecast_validated_transition() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'validated' THEN
                IF TG_TABLE_NAME = 'forecast_feature_snapshot' THEN
                    PERFORM agri.validate_forecast_feature_snapshot(NEW.id);
                ELSIF TG_TABLE_NAME = 'forecast_training_run' THEN
                    PERFORM agri.validate_forecast_training_run(
                        NEW.id,
                        NEW.model_checksum,
                        NEW.validation_checksum,
                        NEW.validation_metrics
                    );
                ELSIF TG_TABLE_NAME = 'forecast_run' THEN
                    PERFORM agri.validate_forecast_run(NEW.id);
                END IF;
            END IF;
            RETURN NEW;
        END
        $$;
