-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

CREATE PROCEDURE agri.materialize_forecast_iteration(INOUT p_iteration_id uuid, IN p_iteration_key character varying, IN p_series_id uuid, IN p_release_set_id uuid, IN p_as_of_time timestamp with time zone, IN p_cutoff_time timestamp with time zone, IN p_history_start timestamp with time zone DEFAULT NULL::timestamp with time zone, IN p_horizon_days integer DEFAULT 30, IN p_simulation_count integer DEFAULT 1000, IN p_seed bigint DEFAULT 0, IN p_gap_policy character varying DEFAULT 'strict'::character varying, IN p_lower_bound double precision DEFAULT NULL::double precision, IN p_upper_bound double precision DEFAULT NULL::double precision)
    LANGUAGE plpgsql
    SET "TimeZone" TO 'UTC'
    SET "DateStyle" TO 'ISO, MDY'
    SET "IntervalStyle" TO 'postgres'
    SET extra_float_digits TO '1'
    AS $$
        DECLARE
            existing agri.forecast_iteration;
            effective_history_start timestamptz;
            release_checksum varchar;
            series_contract_checksum varchar;
            series_contract_snapshot jsonb;
            computed_license_snapshots jsonb;
            licenses_match_approved_contract boolean;
            computed_history_checksum varchar;
            computed_parameter_checksum varchar;
            computed_increment_count integer;
            computed_training_day_count integer;
            computed_value_count integer;
            computed_receipt_checksum varchar;
        BEGIN
            IF p_iteration_key IS NULL OR btrim(p_iteration_key) = '' THEN
                RAISE EXCEPTION 'forecast iteration key is required';
            END IF;
            IF p_as_of_time > clock_timestamp() THEN
                RAISE EXCEPTION 'forecast iteration as-of boundary cannot be in the future';
            END IF;

            PERFORM pg_advisory_xact_lock(
                pg_catalog.hashtextextended(
                    'forecast_iteration|' || p_iteration_key,
                    0
                )
            );
            SELECT *
              INTO existing
              FROM agri.forecast_iteration
             WHERE iteration_key = p_iteration_key
             FOR SHARE;

            SELECT
                release_set.manifest_checksum,
                contract.contract_checksum,
                contract.contract_snapshot
              INTO
                release_checksum,
                series_contract_checksum,
                series_contract_snapshot
              FROM agri.release_set AS release_set
              CROSS JOIN agri.v_forecast_timeseries_contract AS contract
             WHERE release_set.id = p_release_set_id
               AND contract.series_id = p_series_id
               AND contract.data_source_review_state = 'approved'
               AND btrim(contract.license_name) <> ''
               AND btrim(coalesce(contract.license_url, '')) <> ''
               AND btrim(contract.citation) <> ''
               AND release_set.state IN ('validated', 'published')
               AND release_set.validated_at <= p_as_of_time
               AND release_set.as_of_time <= p_as_of_time
               AND release_set.created_at <= p_as_of_time
               AND contract.data_source_recorded_at::timestamptz <= p_as_of_time
               AND contract.contract_recorded_at::timestamptz <= p_as_of_time;
            IF NOT FOUND THEN
                RAISE EXCEPTION
                    'forecast iteration requires approved free/open source governance at the as-of boundary';
            END IF;

            SELECT coalesce(
                       p_history_start,
                       min(
                           date_trunc('day', contract.observed_at AT TIME ZONE 'UTC')
                               AT TIME ZONE 'UTC'
                       )
                   )
              INTO effective_history_start
              FROM agri.forecast_timeseries_contract(
                  p_release_set_id,
                  p_as_of_time
              ) AS contract
             WHERE contract.series_id = p_series_id
               AND contract.observed_at < p_cutoff_time + interval '1 day';
            IF effective_history_start IS NULL THEN
                RAISE EXCEPTION 'forecast iteration has no time-honest observations';
            END IF;

            SELECT
                jsonb_agg(
                    jsonb_build_object(
                        'source_release_id',
                        governed.source_release_id,
                        'license_snapshot',
                        governed.source_release_license_snapshot
                    )
                    ORDER BY governed.source_release_id
                ),
                bool_and(
                    btrim(governed.source_release_license_snapshot) <> ''
                    AND governed.source_release_license_snapshot = governed.license_name
                )
              INTO computed_license_snapshots, licenses_match_approved_contract
              FROM (
                    SELECT DISTINCT
                        contract.source_release_id,
                        contract.source_release_license_snapshot,
                        contract.license_name
                    FROM agri.forecast_timeseries_contract(
                        p_release_set_id,
                        p_as_of_time
                    ) AS contract
                    WHERE contract.series_id = p_series_id
                      AND contract.observed_at >= effective_history_start
                      AND contract.observed_at < p_cutoff_time + interval '1 day'
              ) AS governed;
            IF computed_license_snapshots IS NULL
               OR licenses_match_approved_contract IS DISTINCT FROM true THEN
                RAISE EXCEPTION
                    'forecast iteration source-release license snapshots do not match the approved contract';
            END IF;

            SELECT
                count(*)::integer,
                min(bootstrap.increment_count),
                min(bootstrap.parameter_checksum)
              INTO
                computed_value_count,
                computed_increment_count,
                computed_parameter_checksum
              FROM agri.forecast_daily_bootstrap(
                  p_series_id,
                  p_release_set_id,
                  p_as_of_time,
                  p_cutoff_time,
                  effective_history_start,
                  p_horizon_days,
                  p_simulation_count,
                  p_seed,
                  p_gap_policy,
                  p_lower_bound,
                  p_upper_bound
              ) AS bootstrap;
            IF computed_value_count <> p_horizon_days THEN
                RAISE EXCEPTION 'bootstrap did not return its declared horizon';
            END IF;

            SELECT count(*)::integer
              INTO computed_training_day_count
              FROM agri.forecast_aligned_daily_series(
                  p_series_id,
                  p_release_set_id,
                  p_as_of_time,
                  effective_history_start,
                  p_cutoff_time + interval '1 day',
                  p_gap_policy
              ) AS aligned
             WHERE NOT aligned.is_missing;

            SELECT encode(
                       digest(
                           string_agg(
                               aligned.alignment_checksum,
                               '|'
                               ORDER BY aligned.bucket_start
                           ),
                           'sha256'
                       ),
                       'hex'
                   )
              INTO computed_history_checksum
              FROM agri.forecast_aligned_daily_series(
                  p_series_id,
                  p_release_set_id,
                  p_as_of_time,
                  effective_history_start,
                  p_cutoff_time + interval '1 day',
                  p_gap_policy
              ) AS aligned;

            IF existing.id IS NOT NULL THEN
                IF existing.status <> 'finalized'
                   OR (p_iteration_id IS NOT NULL AND p_iteration_id <> existing.id)
                   OR existing.series_id <> p_series_id
                   OR existing.release_set_id <> p_release_set_id
                   OR existing.as_of_time <> p_as_of_time
                   OR existing.cutoff_time <> p_cutoff_time
                   OR existing.history_start <> effective_history_start
                   OR existing.horizon_days <> p_horizon_days
                   OR existing.simulation_count <> p_simulation_count
                   OR existing.simulation_seed <> p_seed
                   OR existing.gap_policy <> p_gap_policy
                   OR existing.lower_bound IS DISTINCT FROM p_lower_bound
                   OR existing.upper_bound IS DISTINCT FROM p_upper_bound
                   OR existing.input_release_checksum <> release_checksum
                   OR existing.input_license_snapshots IS DISTINCT FROM computed_license_snapshots
                   OR existing.contract_snapshot IS DISTINCT FROM series_contract_snapshot
                   OR existing.contract_checksum <> series_contract_checksum
                   OR existing.history_checksum <> computed_history_checksum
                   OR existing.parameter_checksum <> computed_parameter_checksum
                   OR existing.training_day_count <> computed_training_day_count
                   OR existing.increment_count <> computed_increment_count THEN
                    RAISE EXCEPTION
                        'forecast iteration key already has different immutable parameters or evidence';
                END IF;
                p_iteration_id := existing.id;
                RETURN;
            END IF;

            p_iteration_id := coalesce(p_iteration_id, gen_random_uuid());
            INSERT INTO agri.forecast_iteration(
                id,
                iteration_key,
                series_id,
                release_set_id,
                availability_mode,
                as_of_time,
                cutoff_time,
                history_start,
                horizon_days,
                simulation_count,
                simulation_seed,
                gap_policy,
                lower_bound,
                upper_bound,
                input_release_checksum,
                input_license_snapshots,
                contract_snapshot,
                contract_checksum,
                history_checksum,
                parameter_checksum,
                training_day_count,
                increment_count,
                expected_value_count
            )
            VALUES (
                p_iteration_id,
                p_iteration_key,
                p_series_id,
                p_release_set_id,
                CASE
                    WHEN p_as_of_time > p_cutoff_time + interval '1 day'
                        THEN 'retrospective_pinned_release'
                    ELSE 'as_of_pinned_release'
                END,
                p_as_of_time,
                p_cutoff_time,
                effective_history_start,
                p_horizon_days,
                p_simulation_count,
                p_seed,
                p_gap_policy,
                p_lower_bound,
                p_upper_bound,
                release_checksum,
                computed_license_snapshots,
                series_contract_snapshot,
                series_contract_checksum,
                computed_history_checksum,
                computed_parameter_checksum,
                computed_training_day_count,
                computed_increment_count,
                p_horizon_days
            );

            INSERT INTO agri.forecast_iteration_value(
                iteration_id,
                valid_time,
                horizon_step,
                low_value,
                median_value,
                high_value,
                increment_count,
                parameter_checksum
            )
            SELECT
                p_iteration_id,
                bootstrap.valid_time,
                bootstrap.horizon_step,
                bootstrap.low_value,
                bootstrap.median_value,
                bootstrap.high_value,
                bootstrap.increment_count,
                bootstrap.parameter_checksum
            FROM agri.forecast_daily_bootstrap(
                p_series_id,
                p_release_set_id,
                p_as_of_time,
                p_cutoff_time,
                effective_history_start,
                p_horizon_days,
                p_simulation_count,
                p_seed,
                p_gap_policy,
                p_lower_bound,
                p_upper_bound
            ) AS bootstrap;

            computed_receipt_checksum :=
                agri.forecast_iteration_receipt_checksum(p_iteration_id);
            UPDATE agri.forecast_iteration
               SET
                   receipt_checksum = computed_receipt_checksum,
                   recorded_at = clock_timestamp(),
                   status = 'finalized'
             WHERE id = p_iteration_id;
        END
        $$;
