"""Seed data for 10 regenerative agriculture strategies."""

from agri_data_service.models.strategy import ImpactLevel, LaborIntensity, WaterRequirement

STRATEGY_SEEDS = [
    {
        "name": "Silvopasture",
        "slug": "silvopasture",
        "category": "agroforestry",
        "description": "Intentional integration of trees, forage, and livestock on the same land unit to create productive, ecologically sound systems.",
        "min_precip_mm": 600, "max_precip_mm": 1500,
        "min_temp_c": 5, "max_temp_c": 25,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam"],
        "suitable_drainage": ["well_drained", "moderately_well_drained"],
        "max_slope_pct": 30, "min_organic_matter_pct": 1.5,
        "water_requirement": WaterRequirement.MEDIUM,
        "labor_intensity": LaborIntensity.MEDIUM,
        "time_to_yield_years": 3,
        "carbon_seq_potential": ImpactLevel.VERY_HIGH,
        "biodiversity_impact": ImpactLevel.HIGH,
    },
    {
        "name": "Agroforestry",
        "slug": "agroforestry",
        "category": "agroforestry",
        "description": "Land use management combining trees or shrubs with crops and/or livestock in a spatially and temporally deliberate arrangement.",
        "min_precip_mm": 500, "max_precip_mm": 2000,
        "min_temp_c": 0, "max_temp_c": 30,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam", "clay"],
        "suitable_drainage": ["well_drained", "moderately_well_drained", "somewhat_poorly_drained"],
        "max_slope_pct": 40, "min_organic_matter_pct": 1.0,
        "water_requirement": WaterRequirement.MEDIUM,
        "labor_intensity": LaborIntensity.HIGH,
        "time_to_yield_years": 4,
        "carbon_seq_potential": ImpactLevel.VERY_HIGH,
        "biodiversity_impact": ImpactLevel.VERY_HIGH,
    },
    {
        "name": "Hydroponics",
        "slug": "hydroponics",
        "category": "controlled_environment",
        "description": "Soilless plant cultivation using mineral nutrient solutions in water, suitable for controlled indoor environments.",
        "min_precip_mm": None, "max_precip_mm": None,
        "min_temp_c": 15, "max_temp_c": 30,
        "suitable_soil_types": None,
        "suitable_drainage": None,
        "max_slope_pct": None, "min_organic_matter_pct": None,
        "water_requirement": WaterRequirement.LOW,
        "labor_intensity": LaborIntensity.HIGH,
        "time_to_yield_years": 0.25,
        "carbon_seq_potential": ImpactLevel.LOW,
        "biodiversity_impact": ImpactLevel.LOW,
    },
    {
        "name": "Aquaponics",
        "slug": "aquaponics",
        "category": "controlled_environment",
        "description": "Symbiotic system combining aquaculture with hydroponics where fish waste provides nutrients for plant growth.",
        "min_precip_mm": None, "max_precip_mm": None,
        "min_temp_c": 18, "max_temp_c": 28,
        "suitable_soil_types": None,
        "suitable_drainage": None,
        "max_slope_pct": None, "min_organic_matter_pct": None,
        "water_requirement": WaterRequirement.LOW,
        "labor_intensity": LaborIntensity.HIGH,
        "time_to_yield_years": 0.5,
        "carbon_seq_potential": ImpactLevel.LOW,
        "biodiversity_impact": ImpactLevel.MEDIUM,
    },
    {
        "name": "Cover Cropping",
        "slug": "cover-cropping",
        "category": "soil_health",
        "description": "Planting non-cash crops to cover soil between production seasons, improving soil health, preventing erosion, and building organic matter.",
        "min_precip_mm": 300, "max_precip_mm": 2000,
        "min_temp_c": -5, "max_temp_c": 35,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam", "sand", "clay"],
        "suitable_drainage": ["well_drained", "moderately_well_drained", "somewhat_poorly_drained"],
        "max_slope_pct": 20, "min_organic_matter_pct": 0.5,
        "water_requirement": WaterRequirement.LOW,
        "labor_intensity": LaborIntensity.LOW,
        "time_to_yield_years": 0.5,
        "carbon_seq_potential": ImpactLevel.MEDIUM,
        "biodiversity_impact": ImpactLevel.MEDIUM,
    },
    {
        "name": "Keyline Design",
        "slug": "keyline-design",
        "category": "water_management",
        "description": "Landscape-scale water harvesting system using contour plowing patterns to distribute water from valleys to ridges, building soil depth.",
        "min_precip_mm": 250, "max_precip_mm": 1200,
        "min_temp_c": -10, "max_temp_c": 35,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam"],
        "suitable_drainage": ["well_drained", "moderately_well_drained"],
        "max_slope_pct": 15, "min_organic_matter_pct": 0.5,
        "water_requirement": WaterRequirement.LOW,
        "labor_intensity": LaborIntensity.MEDIUM,
        "time_to_yield_years": 1,
        "carbon_seq_potential": ImpactLevel.HIGH,
        "biodiversity_impact": ImpactLevel.MEDIUM,
    },
    {
        "name": "Biochar Application",
        "slug": "biochar-application",
        "category": "soil_amendment",
        "description": "Application of pyrolyzed biomass to soil for long-term carbon sequestration, improved water retention, and enhanced microbial activity.",
        "min_precip_mm": 200, "max_precip_mm": 2500,
        "min_temp_c": -15, "max_temp_c": 40,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam", "sand", "clay"],
        "suitable_drainage": ["well_drained", "moderately_well_drained", "somewhat_poorly_drained", "poorly_drained"],
        "max_slope_pct": 25, "min_organic_matter_pct": 0.0,
        "water_requirement": WaterRequirement.LOW,
        "labor_intensity": LaborIntensity.LOW,
        "time_to_yield_years": 0.5,
        "carbon_seq_potential": ImpactLevel.VERY_HIGH,
        "biodiversity_impact": ImpactLevel.MEDIUM,
    },
    {
        "name": "Contour Farming",
        "slug": "contour-farming",
        "category": "erosion_control",
        "description": "Farming along the natural contours of slopes to reduce water runoff, prevent soil erosion, and improve water infiltration.",
        "min_precip_mm": 300, "max_precip_mm": 1500,
        "min_temp_c": -5, "max_temp_c": 35,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam"],
        "suitable_drainage": ["well_drained", "moderately_well_drained"],
        "max_slope_pct": 20, "min_organic_matter_pct": 1.0,
        "water_requirement": WaterRequirement.MEDIUM,
        "labor_intensity": LaborIntensity.MEDIUM,
        "time_to_yield_years": 1,
        "carbon_seq_potential": ImpactLevel.MEDIUM,
        "biodiversity_impact": ImpactLevel.LOW,
    },
    {
        "name": "Managed Grazing",
        "slug": "managed-grazing",
        "category": "livestock",
        "description": "Rotational or adaptive multi-paddock grazing that mimics natural herbivore patterns to improve pasture health and soil carbon.",
        "min_precip_mm": 400, "max_precip_mm": 1800,
        "min_temp_c": -10, "max_temp_c": 30,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam"],
        "suitable_drainage": ["well_drained", "moderately_well_drained"],
        "max_slope_pct": 35, "min_organic_matter_pct": 1.5,
        "water_requirement": WaterRequirement.MEDIUM,
        "labor_intensity": LaborIntensity.MEDIUM,
        "time_to_yield_years": 1,
        "carbon_seq_potential": ImpactLevel.HIGH,
        "biodiversity_impact": ImpactLevel.HIGH,
    },
    {
        "name": "Permaculture Food Forest",
        "slug": "permaculture-food-forest",
        "category": "agroforestry",
        "description": "Multi-layered perennial food production system mimicking natural forest structure with canopy, understory, shrub, herb, ground cover, vine, and root layers.",
        "min_precip_mm": 600, "max_precip_mm": 2500,
        "min_temp_c": 0, "max_temp_c": 30,
        "suitable_soil_types": ["loam", "clay_loam", "sandy_loam", "silt_loam"],
        "suitable_drainage": ["well_drained", "moderately_well_drained"],
        "max_slope_pct": 25, "min_organic_matter_pct": 2.0,
        "water_requirement": WaterRequirement.HIGH,
        "labor_intensity": LaborIntensity.HIGH,
        "time_to_yield_years": 5,
        "carbon_seq_potential": ImpactLevel.VERY_HIGH,
        "biodiversity_impact": ImpactLevel.VERY_HIGH,
    },
]
