-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: cell_source_crosswalk fk_cell_source_crosswalk_cell_id_spatial_cell
ALTER TABLE ONLY agri.cell_source_crosswalk
    ADD CONSTRAINT fk_cell_source_crosswalk_cell_id_spatial_cell FOREIGN KEY (cell_id) REFERENCES agri.spatial_cell(id);

-- FK CONSTRAINT: cell_source_crosswalk fk_cell_source_crosswalk_source_release_id_source_release
ALTER TABLE ONLY agri.cell_source_crosswalk
    ADD CONSTRAINT fk_cell_source_crosswalk_source_release_id_source_release FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
