-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: expert_label fk_expert_label_release
ALTER TABLE ONLY agri.expert_label
    ADD CONSTRAINT fk_expert_label_release FOREIGN KEY (release_id) REFERENCES agri.expert_label_release(id);

-- FK CONSTRAINT: expert_label fk_expert_label_source
ALTER TABLE ONLY agri.expert_label
    ADD CONSTRAINT fk_expert_label_source FOREIGN KEY (source_id) REFERENCES agri.expert_label_source(id);
