-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_value forecast_value_forecast_receipt_id_fkey
ALTER TABLE ONLY agri.forecast_value
    ADD CONSTRAINT forecast_value_forecast_receipt_id_fkey FOREIGN KEY (forecast_receipt_id) REFERENCES agri.forecast_receipt(id);
