-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_receipt forecast_receipt_entity_state_id_fkey
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT forecast_receipt_entity_state_id_fkey FOREIGN KEY (entity_state_id) REFERENCES agri.forecast_entity_state(id);

-- FK CONSTRAINT: forecast_receipt forecast_receipt_forecast_run_id_fkey
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT forecast_receipt_forecast_run_id_fkey FOREIGN KEY (forecast_run_id) REFERENCES agri.forecast_run(id);

-- FK CONSTRAINT: forecast_receipt forecast_receipt_job_output_id_fkey
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT forecast_receipt_job_output_id_fkey FOREIGN KEY (job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: forecast_receipt forecast_receipt_series_id_fkey
ALTER TABLE ONLY agri.forecast_receipt
    ADD CONSTRAINT forecast_receipt_series_id_fkey FOREIGN KEY (series_id) REFERENCES agri.forecast_series(id);
