-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_model forecast_model_artifact_id_fkey
ALTER TABLE ONLY agri.forecast_model
    ADD CONSTRAINT forecast_model_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES agri.artifact(id);
