-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_hindcast_value forecast_hindcast_value_actual_source_release_id_fkey
ALTER TABLE ONLY agri.forecast_hindcast_value
    ADD CONSTRAINT forecast_hindcast_value_actual_source_release_id_fkey FOREIGN KEY (actual_source_release_id) REFERENCES agri.source_release(id);

-- FK CONSTRAINT: forecast_hindcast_value forecast_hindcast_value_hindcast_run_id_fkey
ALTER TABLE ONLY agri.forecast_hindcast_value
    ADD CONSTRAINT forecast_hindcast_value_hindcast_run_id_fkey FOREIGN KEY (hindcast_run_id) REFERENCES agri.forecast_hindcast_run(id);
