-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_run forecast_run_feature_snapshot_id_fkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_feature_snapshot_id_fkey FOREIGN KEY (feature_snapshot_id) REFERENCES agri.forecast_feature_snapshot(id);

-- FK CONSTRAINT: forecast_run forecast_run_job_run_id_fkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_job_run_id_fkey FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id);

-- FK CONSTRAINT: forecast_run forecast_run_model_id_fkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_model_id_fkey FOREIGN KEY (model_id) REFERENCES agri.forecast_model(id);

-- FK CONSTRAINT: forecast_run forecast_run_quality_policy_id_fkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_quality_policy_id_fkey FOREIGN KEY (quality_policy_id) REFERENCES agri.forecast_quality_policy(id);

-- FK CONSTRAINT: forecast_run forecast_run_training_run_id_fkey
ALTER TABLE ONLY agri.forecast_run
    ADD CONSTRAINT forecast_run_training_run_id_fkey FOREIGN KEY (training_run_id) REFERENCES agri.forecast_training_run(id);
