-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_training_run fk_forecast_training_run_strategy_label_release_id_stra_4f7c
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT fk_forecast_training_run_strategy_label_release_id_stra_4f7c FOREIGN KEY (strategy_label_release_id) REFERENCES agri.strategy_label_release(id);

-- FK CONSTRAINT: forecast_training_run forecast_training_run_feature_snapshot_id_fkey
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_feature_snapshot_id_fkey FOREIGN KEY (feature_snapshot_id) REFERENCES agri.forecast_feature_snapshot(id);

-- FK CONSTRAINT: forecast_training_run forecast_training_run_job_output_id_fkey
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_job_output_id_fkey FOREIGN KEY (job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: forecast_training_run forecast_training_run_job_run_id_fkey
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_job_run_id_fkey FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id);

-- FK CONSTRAINT: forecast_training_run forecast_training_run_model_id_fkey
ALTER TABLE ONLY agri.forecast_training_run
    ADD CONSTRAINT forecast_training_run_model_id_fkey FOREIGN KEY (model_id) REFERENCES agri.forecast_model(id);
