-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_iteration_actual forecast_iteration_actual_actual_release_set_id_fkey
ALTER TABLE ONLY agri.forecast_iteration_actual
    ADD CONSTRAINT forecast_iteration_actual_actual_release_set_id_fkey FOREIGN KEY (actual_release_set_id) REFERENCES agri.release_set(id);

-- FK CONSTRAINT: forecast_iteration_actual forecast_iteration_actual_iteration_value_id_fkey
ALTER TABLE ONLY agri.forecast_iteration_actual
    ADD CONSTRAINT forecast_iteration_actual_iteration_value_id_fkey FOREIGN KEY (iteration_value_id) REFERENCES agri.forecast_iteration_value(id);
