-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_feature_snapshot forecast_feature_snapshot_job_run_id_fkey
ALTER TABLE ONLY agri.forecast_feature_snapshot
    ADD CONSTRAINT forecast_feature_snapshot_job_run_id_fkey FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id);

-- FK CONSTRAINT: forecast_feature_snapshot forecast_feature_snapshot_release_set_id_fkey
ALTER TABLE ONLY agri.forecast_feature_snapshot
    ADD CONSTRAINT forecast_feature_snapshot_release_set_id_fkey FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id);
