-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_entity_state forecast_entity_state_series_id_fkey
ALTER TABLE ONLY agri.forecast_entity_state
    ADD CONSTRAINT forecast_entity_state_series_id_fkey FOREIGN KEY (series_id) REFERENCES agri.forecast_series(id);

-- FK CONSTRAINT: forecast_entity_state forecast_entity_state_source_release_id_fkey
ALTER TABLE ONLY agri.forecast_entity_state
    ADD CONSTRAINT forecast_entity_state_source_release_id_fkey FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
