-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_backtest_metric forecast_backtest_metric_forecast_run_id_fkey
ALTER TABLE ONLY agri.forecast_backtest_metric
    ADD CONSTRAINT forecast_backtest_metric_forecast_run_id_fkey FOREIGN KEY (forecast_run_id) REFERENCES agri.forecast_run(id);

-- FK CONSTRAINT: forecast_backtest_metric forecast_backtest_metric_job_output_id_fkey
ALTER TABLE ONLY agri.forecast_backtest_metric
    ADD CONSTRAINT forecast_backtest_metric_job_output_id_fkey FOREIGN KEY (job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: forecast_backtest_metric forecast_backtest_metric_series_id_fkey
ALTER TABLE ONLY agri.forecast_backtest_metric
    ADD CONSTRAINT forecast_backtest_metric_series_id_fkey FOREIGN KEY (series_id) REFERENCES agri.forecast_series(id);
