-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_publication_item forecast_publication_item_forecast_receipt_id_fkey
ALTER TABLE ONLY agri.forecast_publication_item
    ADD CONSTRAINT forecast_publication_item_forecast_receipt_id_fkey FOREIGN KEY (forecast_receipt_id) REFERENCES agri.forecast_receipt(id);

-- FK CONSTRAINT: forecast_publication_item forecast_publication_item_publication_id_fkey
ALTER TABLE ONLY agri.forecast_publication_item
    ADD CONSTRAINT forecast_publication_item_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES agri.forecast_publication(id);
