-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: forecast_iteration_value forecast_iteration_value_iteration_id_fkey
ALTER TABLE ONLY agri.forecast_iteration_value
    ADD CONSTRAINT forecast_iteration_value_iteration_id_fkey FOREIGN KEY (iteration_id) REFERENCES agri.forecast_iteration(id);
