-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: historical_promotion_chunk_receipt fk_historical_promotion_chunk_receipt_bundle_id_histori_eddc
ALTER TABLE ONLY agri.historical_promotion_chunk_receipt
    ADD CONSTRAINT fk_historical_promotion_chunk_receipt_bundle_id_histori_eddc FOREIGN KEY (bundle_id) REFERENCES agri.historical_promotion_bundle(id) ON DELETE CASCADE;
