-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: historical_promotion_bundle fk_historical_promotion_bundle_release_set_id_release_set
ALTER TABLE ONLY agri.historical_promotion_bundle
    ADD CONSTRAINT fk_historical_promotion_bundle_release_set_id_release_set FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id);
