-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: historical_promotion_artifact_receipt fk_historical_promotion_artifact_receipt_artifact_id_artifact
ALTER TABLE ONLY agri.historical_promotion_artifact_receipt
    ADD CONSTRAINT fk_historical_promotion_artifact_receipt_artifact_id_artifact FOREIGN KEY (artifact_id) REFERENCES agri.artifact(id);

-- FK CONSTRAINT: historical_promotion_artifact_receipt fk_historical_promotion_artifact_receipt_bundle_id_hist_c1b6
ALTER TABLE ONLY agri.historical_promotion_artifact_receipt
    ADD CONSTRAINT fk_historical_promotion_artifact_receipt_bundle_id_hist_c1b6 FOREIGN KEY (bundle_id) REFERENCES agri.historical_promotion_bundle(id) ON DELETE CASCADE;

-- FK CONSTRAINT: historical_promotion_artifact_receipt fk_historical_promotion_artifact_receipt_source_release_d18c
ALTER TABLE ONLY agri.historical_promotion_artifact_receipt
    ADD CONSTRAINT fk_historical_promotion_artifact_receipt_source_release_d18c FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
