-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: intervention_evidence_lineage fk_intervention_evidence_lineage_evidence_input_id_inte_2b5e
ALTER TABLE ONLY agri.intervention_evidence_lineage
    ADD CONSTRAINT fk_intervention_evidence_lineage_evidence_input_id_inte_2b5e FOREIGN KEY (evidence_input_id) REFERENCES agri.intervention_evidence_input(id);

-- FK CONSTRAINT: intervention_evidence_lineage fk_intervention_evidence_lineage_feature_release
ALTER TABLE ONLY agri.intervention_evidence_lineage
    ADD CONSTRAINT fk_intervention_evidence_lineage_feature_release FOREIGN KEY (source_feature_id, source_release_id) REFERENCES agri.normalized_source_feature(id, source_release_id);

-- FK CONSTRAINT: intervention_evidence_lineage fk_intervention_evidence_lineage_source_release_id_sour_bfaa
ALTER TABLE ONLY agri.intervention_evidence_lineage
    ADD CONSTRAINT fk_intervention_evidence_lineage_source_release_id_sour_bfaa FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
