-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: job_event fk_job_event_job_attempt_id_job_attempt
ALTER TABLE agri.job_event
    ADD CONSTRAINT fk_job_event_job_attempt_id_job_attempt FOREIGN KEY (job_attempt_id) REFERENCES agri.job_attempt(id) ON DELETE CASCADE;

-- FK CONSTRAINT: job_event fk_job_event_job_run_id_job_run
ALTER TABLE agri.job_event
    ADD CONSTRAINT fk_job_event_job_run_id_job_run FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id) ON DELETE CASCADE;

-- FK CONSTRAINT: job_event fk_job_event_job_work_item_id_job_work_item
ALTER TABLE agri.job_event
    ADD CONSTRAINT fk_job_event_job_work_item_id_job_work_item FOREIGN KEY (job_work_item_id) REFERENCES agri.job_work_item(id) ON DELETE CASCADE;
