-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: job_attempt fk_job_attempt_job_work_item_id_job_work_item
ALTER TABLE ONLY agri.job_attempt
    ADD CONSTRAINT fk_job_attempt_job_work_item_id_job_work_item FOREIGN KEY (job_work_item_id) REFERENCES agri.job_work_item(id) ON DELETE CASCADE;
