-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: job_dependency fk_job_dependency_depends_on_run_id_job_run
ALTER TABLE ONLY agri.job_dependency
    ADD CONSTRAINT fk_job_dependency_depends_on_run_id_job_run FOREIGN KEY (depends_on_run_id) REFERENCES agri.job_run(id);

-- FK CONSTRAINT: job_dependency fk_job_dependency_job_run_id_job_run
ALTER TABLE ONLY agri.job_dependency
    ADD CONSTRAINT fk_job_dependency_job_run_id_job_run FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id) ON DELETE CASCADE;
