-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: job_run fk_job_run_job_definition_id_job_definition
ALTER TABLE ONLY agri.job_run
    ADD CONSTRAINT fk_job_run_job_definition_id_job_definition FOREIGN KEY (job_definition_id) REFERENCES agri.job_definition(id);

-- FK CONSTRAINT: job_run fk_job_run_release_set_id_release_set
ALTER TABLE ONLY agri.job_run
    ADD CONSTRAINT fk_job_run_release_set_id_release_set FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id);
