-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: land_use_snapshots fk_land_use_snapshots_location_id_locations
ALTER TABLE ONLY agri.land_use_snapshots
    ADD CONSTRAINT fk_land_use_snapshots_location_id_locations FOREIGN KEY (location_id) REFERENCES agri.locations(id);
