-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: normalized_source_feature fk_normalized_source_feature_artifact_id_artifact
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT fk_normalized_source_feature_artifact_id_artifact FOREIGN KEY (artifact_id) REFERENCES agri.artifact(id);

-- FK CONSTRAINT: normalized_source_feature fk_normalized_source_feature_source_release_id_source_release
ALTER TABLE ONLY agri.normalized_source_feature
    ADD CONSTRAINT fk_normalized_source_feature_source_release_id_source_release FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
