-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: publication_pointer fk_publication_pointer_job_output_id_job_output
ALTER TABLE ONLY agri.publication_pointer
    ADD CONSTRAINT fk_publication_pointer_job_output_id_job_output FOREIGN KEY (job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: publication_pointer fk_publication_pointer_previous_job_output_id_job_output
ALTER TABLE ONLY agri.publication_pointer
    ADD CONSTRAINT fk_publication_pointer_previous_job_output_id_job_output FOREIGN KEY (previous_job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: publication_pointer fk_publication_pointer_release_set_id_release_set
ALTER TABLE ONLY agri.publication_pointer
    ADD CONSTRAINT fk_publication_pointer_release_set_id_release_set FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id);
