-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: recommendation_training_receipt fk_recommendation_training_receipt_artifact
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT fk_recommendation_training_receipt_artifact FOREIGN KEY (artifact_id) REFERENCES agri.artifact(id);

-- FK CONSTRAINT: recommendation_training_receipt fk_recommendation_training_receipt_job_output
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT fk_recommendation_training_receipt_job_output FOREIGN KEY (job_output_id) REFERENCES agri.job_output(id);

-- FK CONSTRAINT: recommendation_training_receipt fk_recommendation_training_receipt_job_run
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT fk_recommendation_training_receipt_job_run FOREIGN KEY (job_run_id) REFERENCES agri.job_run(id);

-- FK CONSTRAINT: recommendation_training_receipt fk_recommendation_training_receipt_release
ALTER TABLE ONLY agri.recommendation_training_receipt
    ADD CONSTRAINT fk_recommendation_training_receipt_release FOREIGN KEY (label_release_id) REFERENCES agri.expert_label_release(id);
