-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: release_set_item fk_release_set_item_release_set_id_release_set
ALTER TABLE ONLY agri.release_set_item
    ADD CONSTRAINT fk_release_set_item_release_set_id_release_set FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id) ON DELETE CASCADE;

-- FK CONSTRAINT: release_set_item fk_release_set_item_source_release_id_source_release
ALTER TABLE ONLY agri.release_set_item
    ADD CONSTRAINT fk_release_set_item_source_release_id_source_release FOREIGN KEY (source_release_id) REFERENCES agri.source_release(id);
