-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: source_release fk_source_release_data_source_id_data_source
ALTER TABLE ONLY agri.source_release
    ADD CONSTRAINT fk_source_release_data_source_id_data_source FOREIGN KEY (data_source_id) REFERENCES agri.data_source(id);

-- FK CONSTRAINT: source_release fk_source_release_supersedes_release_id_source_release
ALTER TABLE ONLY agri.source_release
    ADD CONSTRAINT fk_source_release_supersedes_release_id_source_release FOREIGN KEY (supersedes_release_id) REFERENCES agri.source_release(id);
