-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: strategy_label_release fk_strategy_label_release_outcome_definition_id_strateg_f9fc
ALTER TABLE ONLY agri.strategy_label_release
    ADD CONSTRAINT fk_strategy_label_release_outcome_definition_id_strateg_f9fc FOREIGN KEY (outcome_definition_id) REFERENCES agri.strategy_outcome_definition(id);

-- FK CONSTRAINT: strategy_label_release fk_strategy_label_release_release_set_id_release_set
ALTER TABLE ONLY agri.strategy_label_release
    ADD CONSTRAINT fk_strategy_label_release_release_set_id_release_set FOREIGN KEY (release_set_id) REFERENCES agri.release_set(id);
