-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: strategy_label_episode fk_strategy_label_episode_analysis_subject_id_analysis_subject
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT fk_strategy_label_episode_analysis_subject_id_analysis_subject FOREIGN KEY (analysis_subject_id) REFERENCES agri.analysis_subject(id);

-- FK CONSTRAINT: strategy_label_episode fk_strategy_label_episode_baseline_evidence_input_id_in_d3ac
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT fk_strategy_label_episode_baseline_evidence_input_id_in_d3ac FOREIGN KEY (baseline_evidence_input_id) REFERENCES agri.intervention_evidence_input(id);

-- FK CONSTRAINT: strategy_label_episode fk_strategy_label_episode_label_release_id_strategy_lab_b3d1
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT fk_strategy_label_episode_label_release_id_strategy_lab_b3d1 FOREIGN KEY (label_release_id) REFERENCES agri.strategy_label_release(id);

-- FK CONSTRAINT: strategy_label_episode fk_strategy_label_episode_outcome_evidence_input_id_int_8116
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT fk_strategy_label_episode_outcome_evidence_input_id_int_8116 FOREIGN KEY (outcome_evidence_input_id) REFERENCES agri.intervention_evidence_input(id);

-- FK CONSTRAINT: strategy_label_episode fk_strategy_label_episode_strategy_id_strategies
ALTER TABLE ONLY agri.strategy_label_episode
    ADD CONSTRAINT fk_strategy_label_episode_strategy_id_strategies FOREIGN KEY (strategy_id) REFERENCES agri.strategies(id);
