-- GENERATED by db/tools/split_schema.py from the Alembic migration head.
-- Canonical declarative source of truth. Do NOT hand-edit to change the
-- live schema: edit here AND add a migration that loads this file
-- (see db/AGENTS.md, 'Forward-load workflow'). Regenerate with
-- db/tools/regenerate.py; the schema-parity test guards drift.

-- FK CONSTRAINT: strategy_selection_candidate fk_strategy_selection_candidate_selection_receipt_id_st_d3e8
ALTER TABLE ONLY agri.strategy_selection_candidate
    ADD CONSTRAINT fk_strategy_selection_candidate_selection_receipt_id_st_d3e8 FOREIGN KEY (selection_receipt_id) REFERENCES agri.strategy_selection_receipt(id);

-- FK CONSTRAINT: strategy_selection_candidate fk_strategy_selection_candidate_strategy_id_strategies
ALTER TABLE ONLY agri.strategy_selection_candidate
    ADD CONSTRAINT fk_strategy_selection_candidate_strategy_id_strategies FOREIGN KEY (strategy_id) REFERENCES agri.strategies(id);
